COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE OR ALTER PROCEDURE COPY_QUESTIONS (WK_FROM_TYPE SSN_TYPE, WK_TO_TYPE SSN_TYPE)
AS 
                                                       
  DECLARE VARIABLE WK_QUESTION VARCHAR(70);
  DECLARE VARIABLE WK_SEQUENCE INTEGER;
  DECLARE VARIABLE WK_QUESTION_ID INTEGER;
  DECLARE VARIABLE WK_NEW_QUESTION_ID INTEGER;
  DECLARE VARIABLE WK_INSPECT_CATEGORY VARCHAR(1);
     
  DECLARE VARIABLE WK_VALID_RESPONSE VARCHAR(50);
  DECLARE VARIABLE WK_BRANCH_TO INTEGER;
  DECLARE VARIABLE WK_NEW_BRANCH_TO INTEGER;
  DECLARE VARIABLE WK_REQUIRE_ENTRY CHAR(1);
  DECLARE VARIABLE WK_FIELD_TYPE INTEGER;
  DECLARE VARIABLE WK_HIGH_DATE_LIM TIMESTAMP;
  DECLARE VARIABLE WK_HIGH_NUM_LIM FLOAT;
  DECLARE VARIABLE WK_LOW_DATE_LIM TIMESTAMP;
  DECLARE VARIABLE WK_LOW_NUM_LIM FLOAT;
  DECLARE VARIABLE WK_MANDATORY_INPUT CHAR(1);
  DECLARE VARIABLE WK_RUN_PROCEDURE VARCHAR(30);
  DECLARE VARIABLE WK_UPDATE_FIELD VARCHAR(30);
  DECLARE VARIABLE WK_VALID_SELECTION BLOB;
  DECLARE VARIABLE WK_VR_INSPECT_CATEGORY VARCHAR(1);
  DECLARE VARIABLE WK_INSPECT_DESCRIPTION VARCHAR(25);
  DECLARE VARIABLE WK_INSPECT_PASS_CRITERIA VARCHAR(6);
  DECLARE VARIABLE WK_RESPONSE_ID INTEGER;

BEGIN
	UPDATE TEST_QUESTIONS SET ORIGINAL_QUESTION_ID = NULL
		WHERE SSN_TYPE = :WK_TO_TYPE;
	FOR SELECT 
        	SEQUENCE ,
        	QUESTION_ID ,
        	QUESTION ,
        	INSPECT_CATEGORY 
		FROM TEST_QUESTIONS WHERE SSN_TYPE = :WK_FROM_TYPE
                INTO	:WK_SEQUENCE,
			:WK_QUESTION_ID,
			:WK_QUESTION,
			:WK_INSPECT_CATEGORY
	DO
	BEGIN
/*		WK_NEW_QUESTION_ID = GEN_ID(TEST_QUESTIONS_RECORD_ID_GEN, 1); */
		WK_NEW_QUESTION_ID = NEXT VALUE FOR TEST_QUESTIONS_RECORD_ID_GEN;
		INSERT INTO TEST_QUESTIONS (
        	SEQUENCE ,
        	ORIGINAL_QUESTION_ID ,
        	QUESTION ,
        	INSPECT_CATEGORY, 
		SSN_TYPE,
		QUESTION_ID)
		VALUES (
        	:WK_SEQUENCE ,
        	:WK_QUESTION_ID ,
        	:WK_QUESTION ,
        	:WK_INSPECT_CATEGORY, 
		:WK_TO_TYPE,
		:WK_NEW_QUESTION_ID);

		FOR SELECT 
		        VALID_RESPONSE ,
		        BRANCH_TO ,
		        REQUIRE_ENTRY ,
		        FIELD_TYPE ,
		        HIGH_DATE_LIM ,
		        HIGH_NUM_LIM ,
		        LOW_DATE_LIM ,
		        LOW_NUM_LIM ,
		        MANDATORY_INPUT ,
		        RUN_PROCEDURE ,
		        UPDATE_FIELD ,
		        VALID_SELECTION ,
		        INSPECT_CATEGORY ,
		        INSPECT_DESCRIPTION ,
		        INSPECT_PASS_CRITERIA 
			FROM VALID_RESPONSES WHERE QUESTION_ID = :WK_QUESTION_ID
	                INTO	
		        :WK_VALID_RESPONSE ,
		        :WK_BRANCH_TO ,
		        :WK_REQUIRE_ENTRY ,
		        :WK_FIELD_TYPE ,
		        :WK_HIGH_DATE_LIM , 
			:WK_HIGH_NUM_LIM , 
			:WK_LOW_DATE_LIM , 
			:WK_LOW_NUM_LIM , 
			:WK_MANDATORY_INPUT , 
			:WK_RUN_PROCEDURE ,
		        :WK_UPDATE_FIELD ,
		        :WK_VALID_SELECTION ,
		        :WK_VR_INSPECT_CATEGORY ,
		        :WK_INSPECT_DESCRIPTION ,
		        :WK_INSPECT_PASS_CRITERIA 
		DO
		BEGIN
			/* calc question id for branch_to */
			WK_NEW_BRANCH_TO = 0 - WK_BRANCH_TO;
			SELECT QUESTION_ID
				FROM TEST_QUESTIONS
				WHERE ORIGINAL_QUESTION_ID = :WK_QUESTION_ID AND 
					SSN_TYPE= :WK_TO_TYPE
				INTO :WK_NEW_BRANCH_TO;
			INSERT INTO VALID_RESPONSES (
			QUESTION_ID,
		        VALID_RESPONSE ,
		        BRANCH_TO ,
		        REQUIRE_ENTRY ,
		        FIELD_TYPE ,
		        HIGH_DATE_LIM ,
		        HIGH_NUM_LIM ,
		        LOW_DATE_LIM ,
		        LOW_NUM_LIM ,
		        MANDATORY_INPUT ,
		        RUN_PROCEDURE ,
		        UPDATE_FIELD ,
		        VALID_SELECTION ,
		        INSPECT_CATEGORY ,
		        INSPECT_DESCRIPTION ,
		        INSPECT_PASS_CRITERIA )
			VALUES (
			:WK_NEW_QUESTION_ID,
		        :WK_VALID_RESPONSE ,
		        :WK_NEW_BRANCH_TO ,
		        :WK_REQUIRE_ENTRY ,
		        :WK_FIELD_TYPE ,
		        :WK_HIGH_DATE_LIM ,
		        :WK_HIGH_NUM_LIM ,
		        :WK_LOW_DATE_LIM ,
		        :WK_LOW_NUM_LIM ,
		        :WK_MANDATORY_INPUT ,
		        :WK_RUN_PROCEDURE ,
		        :WK_UPDATE_FIELD ,
		        :WK_VALID_SELECTION ,
		        :WK_VR_INSPECT_CATEGORY ,
		        :WK_INSPECT_DESCRIPTION ,
		        :WK_INSPECT_PASS_CRITERIA );
	
		END
	END
	/* now must go though valid responses for new type
	   where  branch to is negative
	*/

	FOR SELECT 
	        TQ.QUESTION_ID ,
	        VR.RESPONSE_ID ,
	        VR.VALID_RESPONSE ,
	        VR.BRANCH_TO ,
	        VR.REQUIRE_ENTRY ,
	        VR.FIELD_TYPE ,
	        VR.HIGH_DATE_LIM ,
	        VR.HIGH_NUM_LIM ,
	        VR.LOW_DATE_LIM ,
	        VR.LOW_NUM_LIM ,
	        VR.MANDATORY_INPUT ,
	        VR.RUN_PROCEDURE ,
	        VR.UPDATE_FIELD ,
	        VR.VALID_SELECTION ,
	        VR.INSPECT_CATEGORY ,
	        VR.INSPECT_DESCRIPTION ,
	        VR.INSPECT_PASS_CRITERIA 
		FROM TEST_QUESTIONS TQ JOIN VALID_RESPONSES VR 
		ON TQ.QUESTION_ID = VR.QUESTION_ID
		WHERE TQ.SSN_TYPE = :WK_TO_TYPE AND
		      VR.BRANCH_TO < 0
	                INTO	
		        :WK_QUESTION_ID ,
		        :WK_RESPONSE_ID,
		        :WK_VALID_RESPONSE ,
		        :WK_BRANCH_TO ,
		        :WK_REQUIRE_ENTRY ,
		        :WK_FIELD_TYPE ,
		        :WK_HIGH_DATE_LIM , 
			:WK_HIGH_NUM_LIM , 
			:WK_LOW_DATE_LIM , 
			:WK_LOW_NUM_LIM , 
			:WK_MANDATORY_INPUT , 
			:WK_RUN_PROCEDURE ,
		        :WK_UPDATE_FIELD ,
		        :WK_VALID_SELECTION ,
		        :WK_VR_INSPECT_CATEGORY ,
		        :WK_INSPECT_DESCRIPTION ,
		        :WK_INSPECT_PASS_CRITERIA 
	DO
	BEGIN
		/* must calc to branch to to use */
		WK_NEW_BRANCH_TO = WK_BRANCH_TO;
		SELECT QUESTION_ID
			FROM TEST_QUESTIONS
			WHERE ORIGINAL_QUESTION_ID = :WK_QUESTION_ID AND 
				SSN_TYPE= :WK_TO_TYPE
			INTO :WK_NEW_BRANCH_TO;
		UPDATE VALID_RESPONSES 
			SET BRANCH_TO = :WK_NEW_BRANCH_TO
		       	WHERE RESPONSE_ID = :WK_RESPONSE_ID;
	END
      
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
