COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER PROCEDURE GET_EMP_IMAGE_ID  RETURNS (
  IMAGE_ID INTEGER
) AS    
     
BEGIN
/* IMAGE_ID = GEN_ID(EMP_IMAGE_GEN, 1); */ 
  IMAGE_ID = NEXT VALUE FOR EMP_IMAGE_GEN ;    
END^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
