COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE OR ALTER PROCEDURE GET_LOAD_NO RETURNS (LOAD_ID ORDER_NO )
AS 

DECLARE VARIABLE WK_LOAD_NO_I INTEGER;
DECLARE VARIABLE WK_LOAD_NO_LEN INTEGER;
DECLARE VARIABLE WK_LOAD_NO_S ORDER_NO;
     
BEGIN
/*  WK_LOAD_NO_I = GEN_ID(LOAD_NO_GEN, 1) ; */
  WK_LOAD_NO_I = NEXT VALUE FOR LOAD_NO_GEN;    
/*WK_LOAD_NO_LEN = STRLEN(WK_LOAD_NO_I); */
  WK_LOAD_NO_LEN = CHAR_LENGTH(WK_LOAD_NO_I);
  
  /* Get Load Prefix from Control */
  /* WK_LOAD_NO_S = 'RPC'; */
  SELECT LOAD_PREFIX
  FROM CONTROL
  INTO :WK_LOAD_NO_S;  

  /* Padding leading with 0 */
  WHILE (WK_LOAD_NO_LEN < 6) DO
  BEGIN
        WK_LOAD_NO_S = WK_LOAD_NO_S || '0';      
        WK_LOAD_NO_LEN = WK_LOAD_NO_LEN + 1;
  END
  WK_LOAD_NO_S = WK_LOAD_NO_S || WK_LOAD_NO_I;
  
  /* Return LoadNo to the caller */
  LOAD_ID = WK_LOAD_NO_S;
  SUSPEND;
  
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
