COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

ALTER PROCEDURE GET_TRANSACTION_ID RETURNS (TRANSID INTEGER)
AS 
   
BEGIN
/* TRANSID = GEN_ID(TRANSACTION_ID,1) ; */
  TRANSID = NEXT VALUE FOR TRANSACTION_ID ;    
  SUSPEND;
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
