COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE  OR ALTER PROCEDURE GET_OBJECT_ID  RETURNS (
  UNIQUEID INTEGER
) AS  
       
BEGIN
/*  UNIQUEID = gen_id(ObjectID_Gen,1) ; */
  UNIQUEID = NEXT VALUE FOR OBJECTID_GEN;    
  IF (UNIQUEID = 10000000) THEN
  BEGIN
/*  UNIQUEID = gen_id(ObjectID_Gen, -9999999) ; */
     UNIQUEID = GEN_ID(OBJECTID_GEN, -9999999) ; 
/*    ALTER SEQUENCE OBJECTID_GEN RESTART WITH  0; */
     UNIQUEID = NEXT VALUE FOR OBJECTID_GEN;    
  END
  SUSPEND;
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
