
CREATE PROCEDURE ADD_ISSN_FROM_SSN  (
SSN_ID VARCHAR(20))
AS 
                                                       
  DECLARE VARIABLE WK_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_PROD VARCHAR(30);
  DECLARE VARIABLE WK_SSN VARCHAR(20);
  DECLARE VARIABLE WK_SSN_QTY INTEGER;
  DECLARE VARIABLE WK_FOUND   INTEGER;
     
BEGIN
   /* Update ISSN table */   
         
   WK_SSN = '';
   SELECT 
       SSN_ID, WH_ID, LOCN_ID, PROD_ID, STATUS_SSN, CURRENT_QTY
       FROM SSN 
       INTO :WK_SSN, :WK_WH_ID, :WK_LOCN_ID, :WK_PROD, :WK_STATUS, :WK_SSN_QTY;
   IF (WK_SSN <> '') THEN
   BEGIN
       WK_FOUND = 0;
       SELECT COUNT(*) FROM ISSN WHERE SSN_ID = :WK_SSN INTO :WK_FOUND;
       IF (WK_FOUND = 0) THEN
       BEGIN
           INSERT INTO ISSN 
               (SSN_ID, ORIGINAL_SSN, WH_ID, LOCN_ID, PROD_ID, ISSN_STATUS,CURRENT_QTY)
               VALUES (:WK_SSN, :WK_SSN, :WK_WH_ID, :WK_LOCN_ID, :WK_PROD, :WK_STATUS, :WK_SSN_QTY );
       END
   END
END ^
 
