UPDATE GLOBAL_CONDITIONS SET DESCRIPTION = 'EXCELLENT CONDITION' WHERE OTHER_NO = 1 AND RESULT = 'P';
UPDATE SSN SET OTHER1='EXCELLENT CONDITION' WHERE OTHER1 = 'AS NEW CONDITION';
COMMIT;
INSERT INTO OPTIONS(GROUP_CODE, CODE, DESCRIPTION) VALUES('PICK_STATU','CF','Confirmed');
INSERT INTO OPTIONS(GROUP_CODE, CODE, DESCRIPTION) VALUES('PICK_STATU','UC','Unconfirmed');

