SET TERM  ^ ;
CREATE PROCEDURE ADD_TEST_RESULTS (
    SSN VARCHAR (20),
    TESTTIME DATE,
    QUESTION VARCHAR (70),
    RESPONSE VARCHAR (50),
    NOTES BLOB sub_type 0 segment size 80,
    TEXTRESPONSE VARCHAR (30),
    NUMBERRESPONSE FLOAT,
    DATERESPONSE DATE,
    UPDATEFIELD VARCHAR (30),
    RUNPROCEDURE VARCHAR (30),
    FIELDTYPE INTEGER,
    CATEGORY VARCHAR (1),
    PASS VARCHAR (6),
    ORIGINAL VARCHAR (1),
    USERID VARCHAR (10),
    QUESTION_ID INTEGER,
    RESPONSE_ID INTEGER)
AS
BEGIN
   INSERT INTO ssn_test_results
        (SSN_ID, TIME_STAMP, question, RESPONSE, NOTES, NUMBER_RESPONSE,
         DATE_RESPONSE, FIELD_TYPE, TEXT_RESPONSE, UPDATE_FIELD, RUN_PROCEDURE,
         INSPECT_CATEGORY, INSPECT_PASS_CRITERIA, ORIGINAL_TEST, USER_ID,
         Question_ID, Response_ID)

   VALUES (:SSN, :TESTTIME, :QUESTION, :RESPONSE,:NOTES, :NUMBERRESPONSE,
          :DATERESPONSE, :FIELDTYPE, :TEXTRESPONSE, :UPDATEFIELD, :RUNPROCEDURE,
          :CATEGORY, :PASS, :ORIGINAL, :USERID, :QUESTION_ID, :RESPONSE_ID );
END ^
SET TERM ; ^ 
