ALTER TABLE PERSON ADD WK_F_NAME VARCHAR(50);
ALTER TABLE PERSON ADD WK_L_NAME VARCHAR(50);

UPDATE PERSON SET WK_F_NAME = FIRST_NAME, WK_L_NAME = LAST_NAME;

ALTER TABLE PERSON DROP FIRST_NAME;
ALTER TABLE PERSON DROP LAST_NAME;

DROP DOMAIN FIRST_NAME;
DROP DOMAIN LAST_NAME;

CREATE DOMAIN FIRST_NAME VARCHAR(50);
CREATE DOMAIN LAST_NAME VARCHAR(50);

ALTER TABLE PERSON ADD FIRST_NAME FIRST_NAME;
ALTER TABLE PERSON ADD LAST_NAME LAST_NAME;

UPDATE PERSON SET FIRST_NAME = WK_F_NAME, LAST_NAME = WK_L_NAME ;

ALTER TABLE PERSON DROP WK_F_NAME;
ALTER TABLE PERSON DROP WK_L_NAME;

ALTER TABLE PICK_ORDER ADD P_PERSON_TYPE CODE_TWO;
ALTER TABLE PICK_ORDER ADD P_FIRST_NAME FIRST_NAME;
ALTER TABLE PICK_ORDER ADD P_LAST_NAME LAST_NAME;
ALTER TABLE PICK_ORDER ADD P_ADDRESS_LINE1 ADDRESS_LINE;
ALTER TABLE PICK_ORDER ADD P_ADDRESS_LINE2 ADDRESS_LINE;
ALTER TABLE PICK_ORDER ADD P_CITY CITY;
ALTER TABLE PICK_ORDER ADD P_STATE STATE;
ALTER TABLE PICK_ORDER ADD P_POST_CODE POST_CODE;
ALTER TABLE PICK_ORDER ADD P_COUNTRY COUNTRY;

ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_PERSON_TYPE CODE_TWO;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_FIRST_NAME FIRST_NAME;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_LAST_NAME LAST_NAME;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_ADDRESS_LINE1 ADDRESS_LINE;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_ADDRESS_LINE2 ADDRESS_LINE;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_CITY CITY;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_STATE STATE;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_POST_CODE POST_CODE;
ALTER TABLE PICK_ORDER_ITEM_TEMP ADD P_COUNTRY COUNTRY;


