
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_PERSON_TYPE CODE_TWO;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_FIRST_NAME FIRST_NAME;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_LAST_NAME LAST_NAME;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_ADDRESS_LINE1 ADDRESS_LINE;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_ADDRESS_LINE2 ADDRESS_LINE;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_CITY CITY;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_STATE STATE;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_POST_CODE POST_CODE;
ALTER TABLE PURCHASE_ORDER_LINE_TEMP ADD P_COUNTRY COUNTRY;

