SET TERM ^;

CREATE GENERATOR PICK_DETAIL_GEN^

CREATE TRIGGER PICK_DETAIL_DETAIL_ID FOR PICK_ITEM_DETAIL 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.PICK_DETAIL_ID IS NULL) THEN
      NEW.PICK_DETAIL_ID = GEN_ID(PICK_DETAIL_GEN, 1);
END ^
 
