
CREATE TRIGGER SSN_MODEL FOR SSN 
ACTIVE AFTER UPDATE POSITION 2
AS
DECLARE VARIABLE WK_EXISTS INTEGER;
DECLARE VARIABLE WK_MODEL VARCHAR(40);
BEGIN
   WK_MODEL = NEW.MODEL;
   WK_EXISTS = 0;
   IF (NEW.MODEL <> OLD.MODEL) THEN
   BEGIN
      SELECT 1 FROM MODEL WHERE CODE = :WK_MODEL INTO :WK_EXISTS;
      IF (WK_EXISTS = 0) THEN
      BEGIN
         INSERT INTO MODEL (CODE, DESCRIPTION) VALUES (:WK_MODEL, :WK_MODEL);
      END
   END
END ^
 
