DROP TRIGGER RUN_TRANSACTION_QANE^
COMMIT^

CREATE TRIGGER RUN_TRANSACTION_QANE FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 43
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_ISSN_SSNID VARCHAR(30);
DECLARE VARIABLE WK_SSN_SSNID VARCHAR(30);
DECLARE VARIABLE WK_RECORD  INTEGER;
DECLARE VARIABLE WK_QUESTION  INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'QANE') THEN
  BEGIN
   /* must update passed ssn answer_id = null
      question_id = sequence 0 question for type
      and remove records from resume test for this ssn_id
   */
     WK_ISSN_SSNID = NEW.OBJECT;	
     WK_SSN_SSNID = NEW.OBJECT;	
     WK_RECORD = NEW.RECORD_ID;	
     /* get seq 0 question */
     SELECT TQ.QUESTION_ID, SN.SSN_ID 
         FROM ISSN ISS 
              JOIN SSN SN ON SN.SSN_ID = ISS.ORIGINAL_SSN 
                 JOIN TEST_QUESTIONS TQ ON TQ.SSN_TYPE = SN.SSN_TYPE
         WHERE ISS.SSN_ID = :WK_ISSN_SSNID
              AND TQ.SEQUENCE = 0
         INTO :WK_QUESTION, :WK_SSN_SSNID;
     UPDATE SSN SET ANSWER_ID = NULL,QUESTION_ID=:WK_QUESTION WHERE SSN_ID = :WK_SSN_SSNID;
     DELETE FROM RESUME_TEST WHERE SSN_ID = :WK_ISSN_SSNID;

     UPDATE TRANSACTIONS SET COMPLETE='T',ERROR_TEXT='Reset Answer ID' WHERE RECORD_ID = :WK_RECORD;

   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
