COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
CREATE OR ALTER PROCEDURE RESET_ISSN_ORDERS (PROCESS_TYPE VARCHAR(40))
AS
                                                       
  DECLARE VARIABLE WK_FROM_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_TO_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_NEW_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_NEW_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_OLD_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_OLD_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_OK CHAR(1);
  DECLARE VARIABLE WK_DOIT CHAR(1);
  DECLARE VARIABLE WK_SSN VARCHAR(20);
  DECLARE VARIABLE WK_SSN_QTY INTEGER;
  DECLARE VARIABLE WK_FOUND INTEGER;
  DECLARE VARIABLE WK_PID_FOUND INTEGER;
  DECLARE VARIABLE WK_LABEL_NO VARCHAR(7);
  DECLARE VARIABLE WK_USER VARCHAR(10);
  DECLARE VARIABLE WK_DETAIL_ID INTEGER;
  DECLARE VARIABLE WK_SSN_PICK_ORDER VARCHAR(20);
  DECLARE VARIABLE WK_MOVE_STAT CHAR(2);
  DECLARE VARIABLE WK_TO_MOVEABLE VARCHAR(2);
  DECLARE VARIABLE WK_TO_STORE_TYPE  VARCHAR(2);
  DECLARE VARIABLE WK_ALLOWED_STATUS VARCHAR(40);
  DECLARE VARIABLE WK_PI_LABEL_NO VARCHAR(10);
  DECLARE VARIABLE WK_PI_TOPICK_QTY INTEGER;
  DECLARE VARIABLE WK_IS_TOPICK_QTY INTEGER;
  DECLARE VARIABLE WK_PO_PARTIAL_PICK VARCHAR(2);
  DECLARE VARIABLE WK_DUMMY  INTEGER;
  DECLARE VARIABLE WK_IS_QTY INTEGER;
  DECLARE VARIABLE WK_IS_SSN_ID VARCHAR(20);
  DECLARE VARIABLE WK_IS_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_IS_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_PROD_ID VARCHAR(30);
  DECLARE VARIABLE WK_IS_COMPANY_ID VARCHAR(20);
  DECLARE VARIABLE WK_IS_AVAILABLE_QTY INTEGER;
  DECLARE VARIABLE WK_IS_UNPICKED_QTY INTEGER;
     
BEGIN
   /* open al pick item lines */   
         
   WK_IS_SSN_ID = NULL; 
   WK_IS_WH_ID = NULL; 
   WK_IS_LOCN_ID = NULL; 
   WK_IS_PROD_ID = NULL; 
   WK_IS_QTY = NULL;
   WK_IS_AVAILABLE_QTY = NULL;
   WK_IS_UNPICKED_QTY = NULL;
   WK_IS_COMPANY_ID = NULL;
   IF (PROCESS_TYPE = 'OP TO AS OVER PICK') THEN
   BEGIN
   /* op to al - over ordered pick item lines */   
      WK_IS_WH_ID = 'RZ';
      WK_IS_COMPANY_ID = 'PINPOINT';
      FOR SELECT P1.PROD_ID,P1.AVAILABLE_QTY, P1.UNPICKED_ORDER_QTY
      FROM PRODUCT_COMPANY_WH_STOCK_STATUS('%','PINPOINT','RZ','Admin') AS P1  
      WHERE P1.AVAILABLE_QTY < P1.UNPICKED_ORDER_QTY
      INTO :WK_IS_PROD_ID, :WK_IS_AVAILABLE_QTY, :WK_IS_UNPICKED_QTY
      DO
      BEGIN
         /* want to only update the 1st qty of pick items that match */
         WK_IS_TOPICK_QTY = WK_IS_AVAILABLE_QTY;
         FOR SELECT PICK_ITEM.PICK_LABEL_NO, (COALESCE(PICK_ITEM.PICK_ORDER_QTY, 0) - COALESCE(PICK_ITEM.PICKED_QTY,0)) AS  TOPICK_QTY, PICK_ORDER.PARTIAL_PICK_ALLOWED
         FROM  PICK_ITEM
         JOIN PICK_ORDER ON PICK_ORDER.PICK_ORDER = PICK_ITEM.PICK_ORDER
         WHERE PICK_ITEM.PROD_ID = :WK_IS_PROD_ID 
         AND   PICK_ITEM.PICK_LINE_STATUS = 'OP'
         AND PICK_ORDER.WH_ID = :WK_IS_WH_ID
         AND PICK_ORDER.COMPANY_ID = :WK_IS_COMPANY_ID
         ORDER BY  PICK_ORDER.PICK_PRIORITY, PICK_ORDER.PICK_DUE_DATE 
         INTO :WK_PI_LABEL_NO, :WK_PI_TOPICK_QTY, :WK_PO_PARTIAL_PICK
         DO
         BEGIN
            IF (WK_IS_TOPICK_QTY > 0 AND WK_PI_TOPICK_QTY > 0  ) THEN
            BEGIN
               IF (WK_PO_PARTIAL_PICK = 'T' OR WK_PI_TOPICK_QTY <= WK_IS_TOPICK_QTY) THEN
               BEGIN
   /*
                  UPDATE PICK_ITEM
                  SET PICK_LINE_STATUS = 'OP'
                  WHERE PICK_ITEM.PICK_LABEL_NO = :WK_PI_LABEL_NO ;
   */
                  WK_IS_TOPICK_QTY = WK_IS_TOPICK_QTY - WK_PI_TOPICK_QTY;
               END
            END
            ELSE
            BEGIN
               IF (WK_IS_TOPICK_QTY <= 0) THEN
               BEGIN
                  UPDATE PICK_ITEM
                  SET PICK_LINE_STATUS = 'AS'
                  WHERE PICK_ITEM.PICK_LABEL_NO = :WK_PI_LABEL_NO ;
               END
            END
         END
      END
   END
   IF (PROCESS_TYPE = 'AS TO OP HAVE STOCK') THEN
   BEGIN
   /* al to op - have some stock pick item lines */   
      WK_IS_WH_ID = 'RZ';
      WK_IS_COMPANY_ID = 'PINPOINT';

      FOR SELECT P2.PICK_LABEL_NO
      FROM PRODUCT_COMPANY_WH_STOCK_STATUS('%','PINPOINT','RZ','Admin') AS P1  
      JOIN PICK_ITEM P2 ON P2.PROD_ID = P1.PROD_ID AND P2.PICK_LINE_STATUS = 'AS' AND COALESCE(P2.PICK_ORDER_QTY,0) > COALESCE(P2.PICKED_QTY,0) 
      WHERE P1.AVAILABLE_QTY > P1.UNPICKED_ORDER_QTY AND P1.AVAILABLE_QTY > 0
      INTO :WK_PI_LABEL_NO 
      DO
      BEGIN
         UPDATE PICK_ITEM
         SET PICK_LINE_STATUS = 'OP'
         WHERE PICK_ITEM.PICK_LABEL_NO = :WK_PI_LABEL_NO ;
      END
   END
   IF (PROCESS_TYPE = 'OP TO AS NO STOCK') THEN
   BEGIN
   /* al to op - have some stock pick item lines */   
      WK_IS_WH_ID = 'RZ';
      WK_IS_COMPANY_ID = 'PINPOINT';

      FOR SELECT P2.PICK_LABEL_NO
      FROM PRODUCT_COMPANY_WH_STOCK_STATUS('%','PINPOINT','RZ','Admin') AS P1  
      JOIN PICK_ITEM P2 ON P2.PROD_ID = P1.PROD_ID AND P2.PICK_LINE_STATUS = 'OP' AND COALESCE(P2.PICK_ORDER_QTY,0) > COALESCE(P2.PICKED_QTY,0) 
      WHERE P1.AVAILABLE_QTY = 0
      INTO :WK_PI_LABEL_NO 
      DO
      BEGIN
         UPDATE PICK_ITEM
         SET PICK_LINE_STATUS = 'AS'
         WHERE PICK_ITEM.PICK_LABEL_NO = :WK_PI_LABEL_NO ;
      END
   END
  
   SUSPEND;
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
