COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
CREATE OR ALTER PROCEDURE RESET_ISSN_ORDERS (IN_SSN_ID VARCHAR(20)) RETURNS (UPDATE_STATUS VARCHAR(2))
AS
                                                       
  DECLARE VARIABLE WK_FROM_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_TO_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_NEW_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_NEW_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_OLD_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_OLD_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_OK CHAR(1);
  DECLARE VARIABLE WK_DOIT CHAR(1);
  DECLARE VARIABLE WK_SSN VARCHAR(20);
  DECLARE VARIABLE WK_SSN_QTY INTEGER;
  DECLARE VARIABLE WK_FOUND INTEGER;
  DECLARE VARIABLE WK_PID_FOUND INTEGER;
  DECLARE VARIABLE WK_LABEL_NO VARCHAR(7);
  DECLARE VARIABLE WK_USER VARCHAR(10);
  DECLARE VARIABLE WK_DETAIL_ID INTEGER;
  DECLARE VARIABLE WK_SSN_PICK_ORDER VARCHAR(20);
  DECLARE VARIABLE WK_MOVE_STAT CHAR(2);
  DECLARE VARIABLE WK_TO_MOVEABLE VARCHAR(2);
  DECLARE VARIABLE WK_TO_STORE_TYPE  VARCHAR(2);
  DECLARE VARIABLE WK_ALLOWED_STATUS VARCHAR(40);
  DECLARE VARIABLE WK_PI_LABEL_NO VARCHAR(10);
  DECLARE VARIABLE WK_PI_TOPICK_QTY INTEGER;
  DECLARE VARIABLE WK_IS_TOPICK_QTY INTEGER;
  DECLARE VARIABLE WK_PO_PARTIAL_PICK VARCHAR(2);
  DECLARE VARIABLE WK_DUMMY  INTEGER;
  DECLARE VARIABLE WK_IS_QTY INTEGER;
  DECLARE VARIABLE WK_IS_SSN_ID VARCHAR(20);
  DECLARE VARIABLE WK_IS_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_IS_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_PROD_ID VARCHAR(30);
  DECLARE VARIABLE WK_IS_COMPANY_ID VARCHAR(20);
     
BEGIN
   /* open al pick item lines */   
         
   UPDATE_STATUS = 'F';
   WK_IS_SSN_ID = NULL; 
   WK_IS_WH_ID = NULL; 
   WK_IS_LOCN_ID = NULL; 
   WK_IS_PROD_ID = NULL; 
   WK_IS_QTY = NULL;
   WK_IS_COMPANY_ID = NULL;
/*
   SELECT ISSN.SSN_ID, ISSN.WH_ID, ISSN.LOCN_ID, ISSN.PROD_ID, ISSN.CURRENT_QTY, :WK_IS_COMPANY_ID
   FROM CONTROL 
   JOIN ISSN ON ISSN.ISSN_STATUS IN ('ST','PA')
   AND ISSN.WH_ID = CONTROL.DEFAULT_WH_ID
   AND ISSN.COMPANY_ID = CONTROL.COMPANY_ID 
   AND ISSN.SSN_ID = :IN_SSN_ID
   AND ( ISSN.PROD_ID IS NOT NULL)
   AND ISSN.CURRENT_QTY > 0
   INTO :WK_IS_SSN_ID, :WK_IS_WH_ID, :WK_IS_LOCN_ID, :WK_IS_PROD_ID, :WK_IS_QTY, :WK_IS_COMPANY_ID;
   IF ((WK_IS_SSN_ID IS NOT NULL) AND
       (WK_IS_WH_ID IS NOT NULL) AND
       (WK_IS_LOCN_ID IS NOT NULL) AND
       (WK_IS_PROD_ID IS NOT NULL) AND
       (WK_IS_QTY IS NOT NULL) AND 
       (WK_IS_COMPANY_ID IS NOT NULL)) THEN
   BEGIN
*/
      /* want to only update the 1st qty of pick items that match */
      WK_IS_TOPICK_QTY = WK_IS_QTY;
/*
      FOR SELECT PICK_ITEM.PICK_LABEL_NO, (COALESCE(PICK_ITEM.PICK_ORDER_QTY, 0) - COALESCE(PICK_ITEM.PICKED_QTY,0)) AS  TOPICK_QTY, PICK_ORDER.PARTIAL_PICK_ALLOWED
      FROM  PICK_ITEM
      JOIN PICK_ORDER ON PICK_ORDER.PICK_ORDER = PICK_ITEM.PICK_ORDER
      WHERE PICK_ITEM.PROD_ID = :WK_IS_PROD_ID 
      AND   PICK_ITEM.PICK_LINE_STATUS = 'AS'
      AND PICK_ORDER.WH_ID = :WK_IS_WH_ID
      AND PICK_ORDER.COMPANY_ID = :WK_IS_COMPANY_ID
      ORDER BY  PICK_ORDER.PICK_PRIORITY, PICK_ORDER.PICK_DUE_DATE 
      INTO :WK_PI_LABEL_NO, :WK_PI_TOPICK_QTY, :WK_PO_PARTIAL_PICK
      DO
      BEGIN
         IF (WK_IS_TOPICK_QTY > 0 AND WK_PI_TOPICK_QTY > 0  ) THEN
         BEGIN
            IF (WK_PO_PARTIAL_PICK = 'T' OR WK_PI_TOPICK_QTY <= WK_IS_TOPICK_QTY) THEN
            BEGIN
               UPDATE PICK_ITEM
               SET PICK_LINE_STATUS = 'OP'
               WHERE PICK_ITEM.PICK_LABEL_NO = :WK_PI_LABEL_NO ;
               WK_IS_TOPICK_QTY = WK_IS_TOPICK_QTY - WK_PI_TOPICK_QTY;
               UPDATE_STATUS = 'T';
            END
         END
      END
   END
*/
  
   SUSPEND;
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
