CREATE TRIGGER RUN_TRANSACTION_STLX FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 73 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'STLX') THEN
  BEGIN
   EXECUTE PROCEDURE PC_STLX 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.DEVICE_ID,
    NEW.TRN_DATE;
   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
