ALTER TRIGGER INSERT_EMPLOYEE INACTIVE;
ALTER TRIGGER INSERT_SKILLS   INACTIVE;
ALTER TRIGGER INSERT_PERSON   INACTIVE;
ALTER TRIGGER INSERT_SKILL_CODES INACTIVE;
ALTER TRIGGER INSERT_TRAINING_SKILL INACTIVE;
ALTER TRIGGER INSERT_TRAINING_SKILL_CODES INACTIVE;

ALTER TRIGGER UPDATE_EMPLOYEE INACTIVE;
ALTER TRIGGER UPDATE_SKILLS   INACTIVE;
ALTER TRIGGER UPDATE_PERSON   INACTIVE;
ALTER TRIGGER UPDATE_SKILL_CODES INACTIVE;
ALTER TRIGGER UPDATE_TRAINING_SKILL INACTIVE;
ALTER TRIGGER UPDATE_TRAINING_SKILL_CODES INACTIVE;

ALTER TRIGGER DELETE_EMPLOYEE INACTIVE;
ALTER TRIGGER DELETE_PERSON   INACTIVE;
ALTER TRIGGER DELETE_TRAINING_SKILL INACTIVE;
ALTER TRIGGER DELETE_TRAINING_SKILL_CODES INACTIVE;

