UPDATE PRODUCT_COND_STATUS SET ORIGINAL_TEST = 'S'
	WHERE ORIGINAL_TEST IS NULL;

COMMIT;

UPDATE RDB$RELATION_FIELDS 
	SET RDB$NULL_FLAG = 1 
	WHERE	(RDB$FIELD_NAME = 'ORIGINAL_TEST') AND 
		(RDB$RELATION_NAME = 'PRODUCT_COND_STATUS');
COMMIT;

ALTER TABLE PRODUCT_COND_STATUS DROP CONSTRAINT INTEG_80;

COMMIT;
ALTER TABLE PRODUCT_COND_STATUS
	ADD CONSTRAINT INTEG_80
	PRIMARY KEY (SSN_ID, CODE, DESCRIPTION, ORIGINAL_TEST);

COMMIT;
