
CREATE PROCEDURE WORKTEST 
AS 
      
  DECLARE VARIABLE REC_EXIST INTEGER; 
  DECLARE VARIABLE WK_SSN VARCHAR(20); 
  DECLARE VARIABLE WK_CODE CHAR(1); 
  DECLARE VARIABLE WK_DESC VARCHAR(50); 
BEGIN
  
  /* Check if master record exists */
  FOR SELECT SSN_ID, CODE, DESCRIPTION 
      FROM PRODUCT_COND_STATUS 
      WHERE ORIGINAL_TEST = 'S'
      INTO :WK_SSN, :WK_CODE,:WK_DESC
  DO
  BEGIN
  	REC_EXIST = 0;
  	SELECT 1
  	FROM PRODUCT_COND_STATUS
  	WHERE SSN_ID = :WK_SSN
  	AND CODE = :WK_CODE
  	AND DESCRIPTION = :WK_DESC  
  	AND ORIGINAL_TEST = 'O'  
  	INTO :REC_EXIST;  
  	IF (REC_EXIST = 0) THEN
  	BEGIN
    		INSERT INTO PRODUCT_COND_STATUS   
         	(SSN_ID, CODE, DESCRIPTION, ORIGINAL_TEST)
    		VALUES (:WK_SSN, :WK_CODE, :WK_DESC, 'O');             
  	END
  END
END ^

