CREATE UNIQUE INDEX IDX_VALID_RESPONSES_2 ON VALID_RESPONSES(RESPONSE_ID);
CREATE INDEX IDX_VALID_RESPONSES_3 ON VALID_RESPONSES(VALID_RESPONSE);
CREATE INDEX IDX_TEST_RESULT_2 ON SSN_TEST_RESULTS(SSN_ID, PROCESSED, INSPECT_CATEGORY,TEST_ID);
CREATE INDEX IDX_RESUME_TEST ON RESUME_TEST(SSN_ID);
CREATE INDEX IDX_TEST_2 ON SSN_TEST(SSN_ID );
