COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 

CREATE OR ALTER  TRIGGER RUN_TRANSACTION_STIS FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 140
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_LOCN_ID VARCHAR(10);
BEGIN
  IF (NEW.TRN_TYPE = 'STIS') THEN
  BEGIN
   WK_LOCN_ID = NEW.LOCN_ID;
   EXECUTE PROCEDURE PC_STIS
    NEW.RECORD_ID ,
    NEW.WH_ID,
    :WK_LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY;
   /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
 END
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
