-- where passed :WK_PROD_ID

SELECT SH.*
FROM SSN_HIST SH
LEFT OUTER JOIN ISSN ON ISSN.SSN_ID = SH.SSN_ID
JOIN CONTROL ON CONTROL.RECORD_ID = 1
WHERE 
(SH.SSN_ID = '002003'
 OR ISSN.PROD_ID = '002003')
AND (POS(CONTROL.MOVEMENT_TRANS,SH.TRN_TYPE,0,1) > -1);
