procedures
CREATE PROCEDURE ADD_PRODUCT_COST (IN_WH_ID VARCHAR(2) CHARACTER SET NONE,
9170:CREATE PROCEDURE GET_PO_LINE_NO (PURCHASE_ORDER VARCHAR(10) CHARACTER SET NONE)
9466:CREATE PROCEDURE MDRAPI_IMPORT_PURCHASE_ORDER (H_ORDER_NO PURCHASE_ORDER,
ALTER PROCEDURE ADD_GRN (GRN VARCHAR(10) CHARACTER SET NONE,
ALTER PROCEDURE ADD_SSN_ISSN_GRCI (WH_ID VARCHAR(2) CHARACTER SET NONE,
ALTER PROCEDURE ADD_SSN_ISSN_GRNV_GRNP (WH_ID VARCHAR(2) CHARACTER SET NONE,
ALTER PROCEDURE ADD_SSN_ISSN_GRNV_SET (WH_ID VARCHAR(2) CHARACTER SET NONE,
ALTER PROCEDURE ADD_SSN_ISSN_GRNV_WEIGHT (WH_ID VARCHAR(2) CHARACTER SET NONE,
ALTER PROCEDURE ADD_SSN_ISSN_GRNV (WH_ID VARCHAR(2) CHARACTER SET NONE,

ALTER PROCEDURE GRN_CHANGE_PRODUCT_ID (OLD_GRN VARCHAR(10) CHARACTER SET NONE,
ALTER PROCEDURE PC_EXPORT_DESPATCH (WK_DESPATCH_ID INTEGER,
ALTER PROCEDURE RPT_PROD_CMP_WH_STOCK_STATUS (IN_PROD_ID VARCHAR(50) CHARACTER SET NONE,
ALTER PROCEDURE UPDATE_ISSN (OBJECT OBJECT,

ALTER PROCEDURE PRODUCT_CMP_WH_STOCK_STATUS_V (IN_PROD_ID VARCHAR(50) CHARACTER SET NONE,
ALTER PROCEDURE PRODUCT_CMP_WH_STOCK_STATUS_6 (IN_PROD_ID VARCHAR(50) CHARACTER SET NONE,
ALTER PROCEDURE PRODUCT_COMPANY_WH_STOCK_STATUS (IN_PROD_ID VARCHAR(50) CHARACTER SET NONE,
