Triggers 
CREATE TRIGGER UPDATE_PO_LINE_DETAIL_TIME FOR PURCHASE_LINE_DETAIL 
70427:CREATE TRIGGER ADD_PURCHASE_TYPE FOR PURCHASE_ORDER 
70500:CREATE TRIGGER MOD_PURCHASE_TYPE FOR PURCHASE_ORDER 
70573:CREATE TRIGGER SAVE_PURCHASE_ORDER FOR PURCHASE_ORDER 
70712:CREATE TRIGGER ADD_PURCHASE_LINE_STATUS FOR PURCHASE_ORDER_LINE 
70832:CREATE TRIGGER MOD_PURCHASE_LINE_DATE FOR PURCHASE_ORDER_LINE 
70936:CREATE TRIGGER SAVE_PURCHASE_ORDER_LINE FOR PURCHASE_ORDER_LINE 
CREATE TRIGGER SAVE_PURCHASE_SUB_LINE FOR PURCHASE_SUB_LINE 
71013:CREATE TRIGGER ADD_PURCHASE_FROM_TEMP FOR PURCHASE_ORDER_LINE_TEMP 
CREATE TRIGGER RUN_TRANSACTION_GRNX FOR TRANSACTIONS 
CREATE TRIGGER RUN_TRANSACTION_DSSS FOR TRANSACTIONS 
CREATE TRIGGER RUN_TRANSACTION_GRND FOR TRANSACTIONS 
CREATE TRIGGER RUN_TRANSACTION_PKOL FOR TRANSACTIONS 

