
CREATE TRIGGER UPDATE_SSN_LOCATION FOR SSN 
ACTIVE BEFORE UPDATE POSITION 0 
AS
                                                       
  DECLARE VARIABLE WK_FROM_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_TO_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_NEW_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_NEW_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_OLD_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_OLD_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_OK CHAR(1);
     
BEGIN
   /* Update SSN table */   
         
   WK_NEW_WH_ID = NEW.WH_ID;
   WK_NEW_LOCN_ID = NEW.LOCN_ID;
   WK_OLD_WH_ID = OLD.WH_ID;
   WK_OLD_LOCN_ID = OLD.LOCN_ID;
   IF ( (WK_NEW_WH_ID <> WK_OLD_WH_ID) OR
        (WK_NEW_LOCN_ID <> WK_OLD_LOCN_ID)) THEN
   BEGIN
      /* location changed */
      WK_FROM_STATUS = NEW.STATUS_SSN;
      WK_TO_STATUS = 'ST';
      SELECT MOVE_STAT FROM LOCATION 
         WHERE WH_ID = :WK_NEW_WH_ID AND LOCN_ID = :WK_NEW_LOCN_ID
         INTO :WK_TO_STATUS;
      /* now check on sys_moves */
      IF (WK_FROM_STATUS <> WK_TO_STATUS) THEN
      BEGIN
         WK_IS_OK = 'N';
         SELECT UPDATE_FLAG FROM SYS_MOVES
            WHERE FROM_STATUS = :WK_FROM_STATUS AND INTO_STATUS = :WK_TO_STATUS
            INTO :WK_IS_OK;
         IF (WK_IS_OK = 'T') THEN
         BEGIN
            NEW.STATUS_SSN = WK_TO_STATUS;
         END
      END
   END
END ^


CREATE TRIGGER UPDATE_ISSN_LOCATION FOR ISSN 
ACTIVE BEFORE UPDATE POSITION 0 
AS
                                                       
  DECLARE VARIABLE WK_FROM_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_TO_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_NEW_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_NEW_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_OLD_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_OLD_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_OK CHAR(1);
     
BEGIN
   /* Update ISSN table */   
         
   WK_NEW_WH_ID = NEW.WH_ID;
   WK_NEW_LOCN_ID = NEW.LOCN_ID;
   WK_OLD_WH_ID = OLD.WH_ID;
   WK_OLD_LOCN_ID = OLD.LOCN_ID;
   IF ( (WK_NEW_WH_ID <> WK_OLD_WH_ID) OR
        (WK_NEW_LOCN_ID <> WK_OLD_LOCN_ID)) THEN
   BEGIN
      /* location changed */
      WK_FROM_STATUS = NEW.ISSN_STATUS;
      WK_TO_STATUS = 'ST';
      SELECT MOVE_STAT FROM LOCATION 
         WHERE WH_ID = :WK_NEW_WH_ID AND LOCN_ID = :WK_NEW_LOCN_ID
         INTO :WK_TO_STATUS;
      IF (WK_FROM_STATUS <> WK_TO_STATUS) THEN
      BEGIN
         /* a change in status possible - so check sys_moves */
         WK_IS_OK = 'N';
         SELECT UPDATE_FLAG FROM SYS_MOVES
            WHERE FROM_STATUS = :WK_FROM_STATUS AND INTO_STATUS = :WK_TO_STATUS
            INTO :WK_IS_OK;
         IF (WK_IS_OK = 'T') THEN
         BEGIN
            NEW.ISSN_STATUS = WK_TO_STATUS;
         END
      END
   END
END ^
