
ALTER PROCEDURE UPDATE_SSN_TRIL_A (OBJECT VARCHAR(30),
WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
TRN_DATE TIMESTAMP,
QTY INTEGER)
AS 
 
                                                       
  DECLARE VARIABLE strORIGINAL_SSN VARCHAR(20);
     
BEGIN
   /* Update SSN table */   
         
   SELECT ORIGINAL_SSN FROM ISSN 
      WHERE SSN_ID = :OBJECT
      INTO :strORIGINAL_SSN;
   UPDATE ISSN
   SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE,
       CURRENT_QTY = CURRENT_QTY + :QTY
   WHERE SSN_ID = :OBJECT;
   IF (strORIGINAL_SSN = OBJECT) THEN
   BEGIN
      UPDATE SSN
         SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE
      WHERE SSN_ID = :OBJECT;
   END
      
END ^

