COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
/*
 h_purchase_order,h_person_id,h_company_id,h_po_status,h_comments,h_po_due_date,p_first_name,l_po_line,l_prod_id,l_po_line_qty,l_po_line_status

*/

/*

H_PURCHASE_ORDER                (PURCHASE_ORDER) VARCHAR(10) Not Null 
H_PERSON_ID                     (PERSON) VARCHAR(20) Nullable 
H_REQUISITION_NO                (REQUISITION_NO) VARCHAR(10) Nullable 
H_PO_DATE                       (PO_DATE) TIMESTAMP Nullable 
H_PO_REVISION_NO                (PO_REVISION_NO) CHAR(2) Nullable 
H_COMPANY_ID                    (COMPANY) VARCHAR(20) Nullable 
H_DIVISION_ID                   (DIVISION) VARCHAR(20) Nullable 
H_PO_STATUS                     (STATUS) CHAR(2) Nullable 
H_COMMENTS                      (COMMENTS) VARCHAR(512) Nullable 
H_PO_PRINTED                    (PO_PRINTED) TIMESTAMP Nullable 
H_USER_ID                       (USER_ID) VARCHAR(10) Nullable 
L_PURCHASE_ORDER                (PURCHASE_ORDER) VARCHAR(10) Not Null 
L_PO_LINE                       (PO_LINE) CHAR(4) Not Null 
L_REQUISITION_NO                (REQUISITION_NO) VARCHAR(10) Nullable 
L_PROD_ID                       (PRODUCT) VARCHAR(30) Nullable 
L_PO_LINE_QTY                   (QTY_DECIMAL) DOUBLE PRECISION Nullable 
L_UNIT_PRICE                    (UNIT_PRICE) DOUBLE PRECISION Nullable 
L_UOM_ORDER                     (CODE_TWO) CHAR(2) Nullable 
L_PO_LINE_DUE_DATE              (PO_LINE_DUE_DATE) TIMESTAMP Nullable 
L_PO_LINE_STATUS                (STATUS) CHAR(2) Nullable 
L_COMMENTS                      (COMMENTS) VARCHAR(512) Nullable 
L_GST_VALUE                     (GST_VALUE) INTEGER Nullable 
L_GST_RATE                      (GST_RATE) INTEGER Nullable 
L_GST_CODE                      (GST_CODE) VARCHAR(3) Nullable 
P_PERSON_TYPE                   (CODE_TWO) CHAR(2) Nullable 
P_FIRST_NAME                    (FIRST_NAME) VARCHAR(50) Nullable 
P_LAST_NAME                     (LAST_NAME) VARCHAR(50) Nullable 
P_ADDRESS_LINE2                 (ADDRESS_LINE) VARCHAR(50) Nullable 
P_CITY                          (CITY) VARCHAR(25) Nullable 
P_STATE                         (STATE) VARCHAR(15) Nullable 
P_POST_CODE                     (POST_CODE) VARCHAR(10) Nullable 
P_COUNTRY                       (COUNTRY) VARCHAR(25) Nullable 
H_ORDER_TYPE                    (CODE_TWO) CHAR(2) Nullable 
P_ADDRESS_LINE1                 VARCHAR(100) Nullable 
H_COST_CENTER                   (CODE) VARCHAR(40) Nullable 
H_PO_LEGACY_MEMO                VARCHAR(1024) Nullable 
H_PO_LEGACY_RECEIVE_WH_NAME     VARCHAR(50) Nullable 
H_PO_LEGACY_DATE                (PO_DATE) TIMESTAMP Nullable 
H_PO_DUE_DATE                   (PO_DATE) TIMESTAMP Nullable 
PP_SHORT_DESC                   (SHORT_DESC) VARCHAR(255) Nullable 
H_PO_LEGACY_RECV_QTY            (QTY) INTEGER Nullable 
H_PO_LEGACY_RECV_DATE           (PO_DATE) TIMESTAMP Nullable 
H_PO_RECEIVE_WH_ID              (WH_ID) CHAR(2) Nullable 
H_PO_SALE_CHANNEL_CODE          (CODE) VARCHAR(40) Nullable 
L_PO_SALE_CHANNEL_CODE          (CODE) VARCHAR(40) Nullable 

*/


CREATE OR ALTER PROCEDURE MDRAPI_IMPORT_PURCHASE_ORDER  (
H_ORDER_NO PURCHASE_ORDER ,
H_PERSON_ID   PERSON ,
H_COMPANY_ID  COMPANY ,
H_PO_STATUS  STATUS ,
H_COMMENTS COMMENTS ,
H_ORDER_DUE_DATE PO_DUE_DATE ,
P_FIRST_NAME   FIRST_NAME ,
L_PO_LINE PO_LINE,
L_PROD_ID PRODUCT,
L_PO_LINE_QTY QTY,
L_PO_LINE_STATUS  STATUS ,

H_ORDER_TYPE  VARCHAR(2) ,
H_CREATE_DATE TIMESTAMP 

)
AS 
DECLARE VARIABLE P_PERSON_TYPE CODE_TWO;
DECLARE VARIABLE P_LAST_NAME LAST_NAME;
DECLARE VARIABLE P_ADDRESS_LINE1 VARCHAR(100);
DECLARE VARIABLE P_ADDRESS_LINE2 ADDRESS_LINE;
DECLARE VARIABLE P_CITY CITY;
DECLARE VARIABLE P_STATE STATE;
DECLARE VARIABLE P_POST_CODE POST_CODE;
DECLARE VARIABLE P_COUNTRY COUNTRY;
DECLARE VARIABLE L_PO_LINE_DUE_DATE PO_DUE_DATE;
BEGIN 
   P_PERSON_TYPE = NULL;
   P_LAST_NAME = NULL;
   P_ADDRESS_LINE1 = NULL;
   P_ADDRESS_LINE2 = NULL;
   P_CITY = NULL;
   P_STATE = NULL;
   P_POST_CODE = NULL;
   P_COUNTRY = NULL;
   L_PO_LINE_DUE_DATE = NULL;

   L_PO_LINE_DUE_DATE = H_ORDER_DUE_DATE;

   INSERT INTO PURCHASE_ORDER_LINE_TEMP( H_PURCHASE_ORDER, H_ORDER_TYPE, H_PERSON_ID, H_COMPANY_ID, 
H_PO_DUE_DATE, P_FIRST_NAME, P_PERSON_TYPE, P_LAST_NAME, 
H_PO_DATE,  
H_COMMENTS, H_PO_STATUS, P_ADDRESS_LINE1, P_ADDRESS_LINE2, 
P_CITY, P_STATE, 
P_POST_CODE, P_COUNTRY, L_PO_LINE, 
L_PROD_ID, L_PO_LINE_QTY, L_PO_LINE_DUE_DATE , L_PO_LINE_STATUS )
      VALUES( 
:H_ORDER_NO, :H_ORDER_TYPE, :H_PERSON_ID, :H_COMPANY_ID, 
:H_ORDER_DUE_DATE, :P_FIRST_NAME, :P_PERSON_TYPE, :P_LAST_NAME,  
:H_CREATE_DATE,  
:H_COMMENTS, :H_PO_STATUS, :P_ADDRESS_LINE1, :P_ADDRESS_LINE2, 
:P_CITY, :P_STATE, 
:P_POST_CODE, :P_COUNTRY, :L_PO_LINE, 
:L_PROD_ID, :L_PO_LINE_QTY, :L_PO_LINE_DUE_DATE, :L_PO_LINE_STATUS );

   EXIT; 
END ^



SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
