
ALTER TABLE COMPANY
ADD INV_TEXT1 VARCHAR(255);

ALTER TABLE COMPANY
ADD INV_TEXT2 VARCHAR(255);

ALTER TABLE COMPANY
ADD BANK_ID_NO1 PERSON;

ALTER TABLE COMPANY
ADD BANK_ID_NO2 PERSON;

ALTER TABLE COMPANY
ADD BANK_BSB_TITLE1 VARCHAR(20);

ALTER TABLE COMPANY
ADD BANK_BSB_NO1 VARCHAR(30);

ALTER TABLE COMPANY
ADD BANK_AC_TITLE1 VARCHAR(20);

ALTER TABLE COMPANY
ADD BANK_ACCOUNT_1 VARCHAR(50);

ALTER TABLE COMPANY
ADD BANK_BSB_TITLE2 VARCHAR(20);

ALTER TABLE COMPANY
ADD BANK_BSB_NO2 VARCHAR(30);

ALTER TABLE COMPANY
ADD BANK_AC_TITLE2 VARCHAR(20);

ALTER TABLE COMPANY
ADD BANK_ACCOUNT_2 VARCHAR(50);

ALTER TABLE COMPANY
ADD CREDIT_TO_TITLE1 VARCHAR(20);

ALTER TABLE COMPANY
ADD CREDIT_TO_NAME1 VARCHAR(50);

ALTER TABLE COMPANY
ADD CREDIT_TO_TITLE2 VARCHAR(20);

ALTER TABLE COMPANY
ADD CREDIT_TO_NAME2 VARCHAR(50);

ALTER TABLE COMPANY
ADD COMPANY_UDF11 VARCHAR(50);

ALTER TABLE COMPANY
ADD COMPANY_UDF12 VARCHAR(50);

ALTER TABLE COMPANY
ADD COMPANY_UDF21 VARCHAR(50);

ALTER TABLE COMPANY
ADD COMPANY_UDF22 VARCHAR(50);
