set term ^ ;

ALTER  PROCEDURE ADD_OBJECT_LABEL (
  SSN_ID VARCHAR(20),
  WH_ID VARCHAR(2),
  GRN VARCHAR(15),
  COMPANY_ID VARCHAR(20)
)  AS     

DECLARE VARIABLE REC_EXIST INTEGER;

BEGIN
    
    REC_EXIST = 0;
    
    SELECT 1 
      FROM SSN
      WHERE SSN_ID = :SSN_ID   
    INTO :REC_EXIST;
      
    IF (REC_EXIST = 0) THEN
    BEGIN  
      INSERT INTO SSN (SSN_ID, WH_ID, LOCN_ID, STATUS_CODE, STATUS_CODE_DATE,
                             GRN, LABEL_DATE, COMPANY_ID)
      VALUES (:SSN_ID, :WH_ID, '00000000', 'RECEIVED', 'NOW', :GRN, 'NOW', :COMPANY_ID);     

      INSERT INTO ISSN (SSN_ID, ORIGINAL_SSN, WH_ID, LOCN_ID, STATUS_CODE, CREATE_DATE, CURRENT_QTY)
      VALUES (:SSN_ID, :SSN_ID, :WH_ID, '00000000', 'RECEIVED', 'NOW', 1);     
    END
             
END ^


