COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 

CREATE OR ALTER PROCEDURE PRODUCT_CMP_WH_STOCK_STATUS_V (IN_PROD_ID VARCHAR(50) ,
COMPANY_ID VARCHAR(6300) ,
WH_ID VARCHAR(300) ,
USER_ID VARCHAR(10) ,
RETURN_VARIABLES VARCHAR(310) )
RETURNS (AVAILABLE_QTY INTEGER,
RESERVED_QTY INTEGER,
ONSITE_QTY INTEGER,
UNPICKED_ORDER_QTY INTEGER,
BACK_ORDER_QTY INTEGER,
CANCELLED_ORDER_QTY INTEGER,
PO_ON_ORDER_QTY INTEGER,
TEST_QTY INTEGER,
AVAILABLE1_QTY INTEGER,
AVAILABLE1_SSN VARCHAR(20) ,
AVAILABLE2_QTY INTEGER,
AVAILABLE2_SSN VARCHAR(20) ,
AVAILABLE3_QTY INTEGER,
AVAILABLE3_SSN VARCHAR(20) ,
PO_ON_ORDER1_NO VARCHAR(10) ,
PO_ON_ORDER1_QTY INTEGER,
PO_ON_ORDER1_DUE_DATE TIMESTAMP,
PROD_ID VARCHAR(30) )
AS 
DECLARE VARIABLE IMPORTSTATUS VARCHAR(40);
DECLARE VARIABLE RESERVEDSTATUS VARCHAR(40);
DECLARE VARIABLE UNPICKEDSTATUS VARCHAR(40);
DECLARE VARIABLE WK_ORDER_QTY INTEGER;
DECLARE VARIABLE WK_PICKED_QTY INTEGER;
DECLARE VARIABLE WK_CURRENT_QTY INTEGER;
DECLARE VARIABLE WK_CURRENT_SSN VARCHAR(20);
DECLARE VARIABLE WK_COUNT INTEGER;
DECLARE VARIABLE WK_SYS_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_USER_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_USER_ADMIN CHAR(1);
DECLARE VARIABLE WK_USER_INVENTORY_OP CHAR(1);
DECLARE VARIABLE WK_CURRENT_WH CHAR(2);
DECLARE VARIABLE WK_CURRENT_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_SYS_CONFIRM_NOPROD CHAR(1);
DECLARE VARIABLE WK_LOG_FILENAME VARCHAR(200);
DECLARE VARIABLE WK_LOG_RESULT   INTEGER;
DECLARE VARIABLE WK_PI_STATUSES VARCHAR(100);
BEGIN

/* DATE: 17TH JUN 2007
SUMEER SHOREE
THERE WERE A COUPLE OF ISSUES - ADDED WH_ID TO ALL THE QUERIES.
SECOND IMPROVEMENT IS WITH CHECKING OF NULLS FOR AVAILABLE QTY, RESERVED_QTY AND ONSITE_QTY
I WOULD HAVE LIKED TO USE THE LIKE OPERATOR FOR COMPANY_ID AND WH_ID
THAT WOULD HAVE ALLOWED A SITUATION WHERE WE WANT A REPORT FOR ALL COMPANIES BUT A SINGLE WAREHOUSE
OR MANY WAHREHOUSES FOR A SINGLE COMPANY.

 */
/*Frank Leih 06 OCT 2007
I have made the wh_id and company_id a '|' or ';' or ',' delimited set of selected wh's or company's
Glen wanted the first 3 qty's in order of qty for the available_qty
I called these available1_ssn ... ,available1_qty ...
also want to add user_id incase want all for that user
if the wh_id is null -> use all available for that user
most sites have say 10 or 20 wh's
but allow for 100
similarly for company_id
allow for 100
*/
/*Frank Leih 18 MAY 2012
  use the RETURN_VARIABLES Parameter to hold which variables to calculate and return 
*/
   WK_LOG_FILENAME = '/tmp/productstock.log';
   WK_SYS_CONFIRM_NOPROD = 'F';
   SELECT CONTROL.PICK_IMPORT_SSN_STATUS,
   CONTROL.PICK_RESERVED_SSN_STATUS,
   CONTROL.PICK_UNPICKED_ITEM_STATUS,
   CONTROL.COMPANY_ID,
   CONTROL.CONFIRM_WITH_NO_PROD
   FROM CONTROL
   INTO :IMPORTSTATUS,
        :RESERVEDSTATUS,
        :UNPICKEDSTATUS,
        :WK_SYS_COMPANY,
        :WK_SYS_CONFIRM_NOPROD;
    IF (WK_SYS_CONFIRM_NOPROD IS NULL) THEN
    BEGIN
       WK_SYS_CONFIRM_NOPROD = 'F';
    END

   SELECT SYS_ADMIN, COMPANY_ID, INVENTORY_OPERATOR
   FROM SYS_USER
   WHERE USER_ID = :USER_ID
   INTO :WK_USER_ADMIN,
   :WK_USER_COMPANY,
   :WK_USER_INVENTORY_OP;
 
   IF (WK_USER_ADMIN IS NULL) THEN
   BEGIN
      WK_USER_ADMIN = 'F';
   END
   IF (WK_USER_INVENTORY_OP IS NULL) THEN
   BEGIN
      WK_USER_INVENTORY_OP = 'F';
   END

   IF (WH_ID IS NULL) THEN
   BEGIN
      WH_ID = '';
   END
   IF (WH_ID = '') THEN
   BEGIN
      IF (WK_USER_ADMIN = 'T') THEN
      BEGIN
         FOR SELECT WH_ID FROM WAREHOUSE INTO :WK_CURRENT_WH
         DO
         BEGIN
            WH_ID = WH_ID || '|' || :WK_CURRENT_WH;
         END
      END
      ELSE
      BEGIN
         FOR SELECT WH_ID FROM ACCESS_USER WHERE USER_ID = :USER_ID INTO :WK_CURRENT_WH
         DO
         BEGIN
            WH_ID = WH_ID || '|' || :WK_CURRENT_WH;
         END
      END
   END
   IF (COMPANY_ID IS NULL) THEN
   BEGIN
      COMPANY_ID = '';
   END
   IF (COMPANY_ID = '') THEN
   BEGIN
      IF ((WK_USER_ADMIN = 'T') OR (WK_USER_INVENTORY_OP = 'T')) THEN
      BEGIN
         FOR SELECT COMPANY_ID FROM COMPANY INTO :WK_CURRENT_COMPANY
         DO
         BEGIN
            COMPANY_ID = COMPANY_ID || '|' || :WK_CURRENT_COMPANY;
         END
      END
      ELSE
      BEGIN
         FOR SELECT COMPANY_ID FROM ACCESS_COMPANY WHERE USER_ID = :USER_ID INTO :WK_CURRENT_COMPANY
         DO
         BEGIN
            COMPANY_ID = COMPANY_ID || '|' || :WK_CURRENT_COMPANY;
         END
      END
   END
   COMPANY_ID = COMPANY_ID || '|ALL' ;

   AVAILABLE_QTY = NULL; 
   RESERVED_QTY = NULL;
   ONSITE_QTY = NULL;
   UNPICKED_ORDER_QTY = NULL;
   BACK_ORDER_QTY = NULL;
   CANCELLED_ORDER_QTY = NULL;
   PO_ON_ORDER_QTY = NULL;
   TEST_QTY = NULL;
   PO_ON_ORDER1_NO = NULL;
   AVAILABLE1_QTY = NULL; 
   AVAILABLE2_QTY = NULL; 
   AVAILABLE3_QTY = NULL; 
   AVAILABLE1_SSN = NULL; 
   AVAILABLE2_SSN = NULL; 
   AVAILABLE3_SSN = NULL; 
   PO_ON_ORDER1_QTY = NULL; 
   PO_ON_ORDER1_DUE_DATE = NULL; 
   PROD_ID = NULL; 

   WK_PI_STATUSES = UNPICKEDSTATUS || ',HD,AS,';
/* if in_prod_id = '%' dont use like
      in_prod_id ends in '%' and only has 1 '%' trim the '%' and use starting with
*/

   /* PROD_ID = IN_PROD_ID; */
   /* FOR SELECT PROD_ID
       FROM PROD_PROFILE
       WHERE PROD_ID LIKE :IN_PROD_ID
             OR SHORT_DESC LIKE :IN_PROD_ID 
       INTO :PROD_ID */
   FOR SELECT ISSN.PROD_ID
       FROM ISSN 
       WHERE ISSN.PROD_ID LIKE :IN_PROD_ID
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              AND ISSN.ISSN_STATUS <> 'DX'
              AND ISSN.ISSN_STATUS <> 'DI'
              AND (ISSN.ISSN_STATUS < 'X' OR ISSN.ISSN_STATUS > 'X~')
              AND (ISSN.WH_ID < 'X' OR ISSN.WH_ID > 'X~')
       GROUP BY ISSN.PROD_ID
       UNION
       SELECT PICK_ITEM.PROD_ID
       FROM PICK_ITEM 
       WHERE PICK_ITEM.PROD_ID LIKE :IN_PROD_ID
              AND (POS(:WK_PI_STATUSES,PICK_ITEM.PICK_LINE_STATUS,0,1) > -1)
       GROUP BY PICK_ITEM.PROD_ID
       UNION
       SELECT PURCHASE_ORDER_LINE.PROD_ID
       FROM PURCHASE_ORDER_LINE 
       WHERE PURCHASE_ORDER_LINE.PROD_ID LIKE :IN_PROD_ID
              AND PURCHASE_ORDER_LINE.PO_LINE_STATUS IN ( 'CF', 'OP')
       GROUP BY PURCHASE_ORDER_LINE.PROD_ID
       INTO :PROD_ID
   DO
   BEGIN
      AVAILABLE_QTY = NULL; 
      RESERVED_QTY = NULL;
      ONSITE_QTY = NULL;
      UNPICKED_ORDER_QTY = NULL;
      BACK_ORDER_QTY = NULL;
      CANCELLED_ORDER_QTY = NULL;
      PO_ON_ORDER_QTY = NULL;
      TEST_QTY = NULL;
      PO_ON_ORDER1_NO = NULL;
   
   /*
              AND ISSN.COMPANY_ID = :COMPANY_ID
              AND ISSN.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'AVAILABLE_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( ISSN.CURRENT_QTY )
              FROM ISSN
              WHERE ISSN.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              AND (POS(:IMPORTSTATUS,ISSN.ISSN_STATUS,0,1) > -1)
              GROUP BY ISSN.PROD_ID
           INTO :AVAILABLE_QTY;
      END
   
      IF (AVAILABLE_QTY IS NULL) THEN
      BEGIN
         AVAILABLE_QTY = 0;
      END
   /*
           IF (WK_SYS_CONFIRM_NOPROD = 'T') THEN
           BEGIN
              AVAILABLE_QTY = 999999999 ;
           END
   */
   
      WK_COUNT = 0;
      AVAILABLE1_QTY = 0;
      AVAILABLE1_SSN = '';
      AVAILABLE2_QTY = 0;
      AVAILABLE2_SSN = '';
      AVAILABLE3_QTY = 0;
      AVAILABLE3_SSN = '';
      PO_ON_ORDER1_QTY = 0;
      PO_ON_ORDER1_DUE_DATE = NULL;
   /*
              AND ISSN.COMPANY_ID = :COMPANY_ID
              AND ISSN.WH_ID = :WH_ID
   */
      IF ((V4POS(:RETURN_VARIABLES,'AVAILABLE1_QTY',0,1) > -1) OR
          (V4POS(:RETURN_VARIABLES,'AVAILABLE2_QTY',0,1) > -1) OR  
          (V4POS(:RETURN_VARIABLES,'AVAILABLE3_QTY',0,1) > -1) OR
          (V4POS(:RETURN_VARIABLES,'AVAILABLE1_SSN',0,1) > -1) OR
          (V4POS(:RETURN_VARIABLES,'AVAILABLE2_SSN',0,1) > -1) OR  
          (V4POS(:RETURN_VARIABLES,'AVAILABLE3_SSN',0,1) > -1)) THEN
      BEGIN
         FOR SELECT FIRST 3 ISSN.CURRENT_QTY,ISSN.SSN_ID
              FROM ISSN
              WHERE ISSN.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              AND (POS(:IMPORTSTATUS,ISSN.ISSN_STATUS,0,1) > -1)
              ORDER BY ISSN.CURRENT_QTY
              INTO :WK_CURRENT_QTY, :WK_CURRENT_SSN
         DO
         BEGIN
            WK_COUNT = WK_COUNT + 1;
            IF (WK_COUNT = 1) THEN
            BEGIN
               AVAILABLE1_QTY = WK_CURRENT_QTY;
               AVAILABLE1_SSN = WK_CURRENT_SSN;
            END
            ELSE
            IF (WK_COUNT = 2) THEN
            BEGIN
               AVAILABLE2_QTY = WK_CURRENT_QTY;
               AVAILABLE2_SSN = WK_CURRENT_SSN;
            END
            ELSE
            IF (WK_COUNT = 3) THEN
            BEGIN
               AVAILABLE3_QTY = WK_CURRENT_QTY;
               AVAILABLE3_SSN = WK_CURRENT_SSN;
            END
         END
      END
   
      IF (AVAILABLE1_QTY IS NULL) THEN
      BEGIN
         AVAILABLE1_QTY = 0;
      END
      IF (AVAILABLE2_QTY IS NULL) THEN
      BEGIN
         AVAILABLE2_QTY = 0;
      END
      IF (AVAILABLE3_QTY IS NULL) THEN
      BEGIN
         AVAILABLE3_QTY = 0;
      END
   
   /*
              AND ISSN.COMPANY_ID = :COMPANY_ID
              AND ISSN.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'RESERVED_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( ISSN.CURRENT_QTY )
              FROM ISSN
              WHERE ISSN.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              AND (POS(:RESERVEDSTATUS,ISSN.ISSN_STATUS,0,1) > -1)
              GROUP BY ISSN.PROD_ID
           INTO :RESERVED_QTY;
      END
   
      IF (RESERVED_QTY IS NULL) THEN
      BEGIN
         RESERVED_QTY = 0;
      END
   
   /*
              AND ISSN.COMPANY_ID = :COMPANY_ID
              AND ISSN.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'ONSITE_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( ISSN.CURRENT_QTY )
              FROM ISSN
              WHERE ISSN.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              AND ISSN.ISSN_STATUS <> 'DX'
              AND ISSN.ISSN_STATUS <> 'DI'
              AND (ISSN.ISSN_STATUS < 'X' OR ISSN.ISSN_STATUS > 'X~')
              AND (ISSN.WH_ID < 'X' OR ISSN.WH_ID > 'X~')
              GROUP BY ISSN.PROD_ID
           INTO :ONSITE_QTY;
      END
   
      IF (ONSITE_QTY IS NULL) THEN
      BEGIN
         ONSITE_QTY = 0;
      END
   
      WK_PICKED_QTY = 0;
      WK_ORDER_QTY = 0;
   /*
              AND PICK_ORDER.COMPANY_ID = :COMPANY_ID
              AND PICK_ORDER.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'UNPICKED_ORDER_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( PICK_ITEM.PICK_ORDER_QTY ),
             SUM( PICK_ITEM.PICKED_QTY )
              FROM PICK_ITEM JOIN PICK_ORDER
              ON PICK_ITEM.PICK_ORDER = PICK_ORDER.PICK_ORDER
              WHERE PICK_ITEM.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,PICK_ORDER.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,PICK_ORDER.WH_ID,0,1) > -1)
              AND (POS(:UNPICKEDSTATUS,PICK_ITEM.PICK_LINE_STATUS,0,1) > -1)
              GROUP BY PICK_ITEM.PROD_ID /* WHY DO WE NEED A GROUP BY CLAUSE HERE? */
           INTO :WK_ORDER_QTY, :WK_PICKED_QTY;
      END
      IF (WK_ORDER_QTY IS NULL) THEN
      BEGIN
         WK_ORDER_QTY = 0;
      END
      IF (WK_PICKED_QTY IS NULL) THEN
      BEGIN
         WK_PICKED_QTY = 0;
      END
      UNPICKED_ORDER_QTY = WK_ORDER_QTY - WK_PICKED_QTY;
      WK_PICKED_QTY = 0;
      WK_ORDER_QTY = 0;

   /*
              AND PICK_ORDER.COMPANY_ID = :COMPANY_ID
              AND PICK_ORDER.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'BACK_ORDER_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( PICK_ITEM.PICK_ORDER_QTY ),
             SUM( PICK_ITEM.PICKED_QTY )
              FROM PICK_ITEM JOIN PICK_ORDER
              ON PICK_ITEM.PICK_ORDER = PICK_ORDER.PICK_ORDER
              WHERE PICK_ITEM.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,PICK_ORDER.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,PICK_ORDER.WH_ID,0,1) > -1)
              AND PICK_ITEM.PICK_LINE_STATUS IN ( 'HD', 'AS')
              GROUP BY PICK_ITEM.PROD_ID /* WHY DO WE NEED A GROUP BY CLAUSE HERE? */
           INTO :WK_ORDER_QTY, :WK_PICKED_QTY;
      END
      IF (WK_ORDER_QTY IS NULL) THEN
      BEGIN
         WK_ORDER_QTY = 0;
      END
      IF (WK_PICKED_QTY IS NULL) THEN
      BEGIN
         WK_PICKED_QTY = 0;
      END
      BACK_ORDER_QTY = WK_ORDER_QTY - WK_PICKED_QTY;
      WK_PICKED_QTY = 0;
      WK_ORDER_QTY = 0;
   /*
              AND PICK_ORDER.COMPANY_ID = :COMPANY_ID
              AND PICK_ORDER.WH_ID = :WH_ID
   */
      IF (V4POS(:RETURN_VARIABLES,'CANCELLED_ORDER_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( PICK_ITEM.PICK_ORDER_QTY ),
             SUM( PICK_ITEM.PICKED_QTY )
              FROM PICK_ITEM JOIN PICK_ORDER
              ON PICK_ITEM.PICK_ORDER = PICK_ORDER.PICK_ORDER
              WHERE PICK_ITEM.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,PICK_ORDER.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,PICK_ORDER.WH_ID,0,1) > -1)
              AND PICK_ITEM.PICK_LINE_STATUS = 'CN'
              GROUP BY PICK_ITEM.PROD_ID
           INTO :WK_ORDER_QTY, :WK_PICKED_QTY;
      END
      IF (WK_ORDER_QTY IS NULL) THEN
      BEGIN
         WK_ORDER_QTY = 0;
      END
      IF (WK_PICKED_QTY IS NULL) THEN
      BEGIN
         WK_PICKED_QTY = 0;
      END
      CANCELLED_ORDER_QTY = WK_ORDER_QTY - WK_PICKED_QTY;
      WK_PICKED_QTY = 0;
      WK_ORDER_QTY = 0;
   
   /* po qtys */
      IF (V4POS(:RETURN_VARIABLES,'PO_ON_ORDER_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( PURCHASE_ORDER_LINE.PO_LINE_QTY )
              FROM PURCHASE_ORDER_LINE JOIN PURCHASE_ORDER
              ON PURCHASE_ORDER_LINE.PURCHASE_ORDER = PURCHASE_ORDER.PURCHASE_ORDER
              WHERE PURCHASE_ORDER_LINE.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,PURCHASE_ORDER.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,PURCHASE_ORDER.PO_RECEIVE_WH_ID,0,1) > -1)
              AND PURCHASE_ORDER_LINE.PO_LINE_STATUS IN ( 'CF', 'OP')
              AND PURCHASE_ORDER.PO_STATUS IN ( 'CF', 'OP')
              GROUP BY PURCHASE_ORDER_LINE.PROD_ID
           INTO :WK_ORDER_QTY ;
      END
      IF (WK_ORDER_QTY IS NULL) THEN
      BEGIN
         WK_ORDER_QTY = 0;
      END
      PO_ON_ORDER_QTY = WK_ORDER_QTY ;
      WK_PICKED_QTY = 0;
      WK_ORDER_QTY = 0;
   
      IF ((V4POS(:RETURN_VARIABLES,'PO_ON_ORDER1_QTY',0,1) > -1) OR
          (V4POS(:RETURN_VARIABLES,'PO_ON_ORDER1_NO',0,1) > -1) OR
          (V4POS(:RETURN_VARIABLES,'PO_ON_ORDER1_DUE_DATE',0,1) > -1)) THEN
      BEGIN
         SELECT FIRST 1 PURCHASE_ORDER_LINE.PURCHASE_ORDER, PURCHASE_ORDER.PO_DUE_DATE, PURCHASE_ORDER_LINE.PO_LINE_QTY
              FROM PURCHASE_ORDER_LINE JOIN PURCHASE_ORDER
              ON PURCHASE_ORDER_LINE.PURCHASE_ORDER = PURCHASE_ORDER.PURCHASE_ORDER
              WHERE PURCHASE_ORDER_LINE.PROD_ID = :PROD_ID
              AND (V4POS(:COMPANY_ID,PURCHASE_ORDER.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,PURCHASE_ORDER.PO_RECEIVE_WH_ID,0,1) > -1)
              AND PURCHASE_ORDER_LINE.PO_LINE_STATUS IN ( 'CF', 'OP')
              AND PURCHASE_ORDER.PO_STATUS IN ( 'CF', 'OP')
              ORDER BY PURCHASE_ORDER.PO_DUE_DATE
              INTO :PO_ON_ORDER1_NO,
                   :PO_ON_ORDER1_DUE_DATE,
                   :PO_ON_ORDER1_QTY;
      END
   
   /*
              AND ISSN.COMPANY_ID = :COMPANY_ID
              AND ISSN.WH_ID = :WH_ID
   */
      TEST_QTY = NULL;
      IF (V4POS(:RETURN_VARIABLES,'TEST_QTY',0,1) > -1) THEN
      BEGIN
         SELECT SUM( ISSN.CURRENT_QTY )
              FROM ISSN
              WHERE ISSN.PROD_ID = :PROD_ID
              AND ISSN.ISSN_STATUS = 'TS'
              AND (V4POS(:COMPANY_ID,ISSN.COMPANY_ID,0,1) > -1)
              AND (V4POS(:WH_ID,ISSN.WH_ID,0,1) > -1)
              GROUP BY ISSN.PROD_ID
           INTO :TEST_QTY;
      END
   
      IF (TEST_QTY IS NULL) THEN
      BEGIN
         TEST_QTY = 0;
      END

      SUSPEND;
   END


END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
