COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 


CREATE OR ALTER  PROCEDURE PRODUCT_COMPANY_WH_GRN_STOCK (PROD_ID PRODUCT ,
COMPANY_IDS VARCHAR(31500) ,
WH_IDS VARCHAR(1260) ,
USER_ID VARCHAR(10) )
RETURNS (WH_ID WH_ID,
COMPANY_ID COMPANY,
SUPPLIER_ID VARCHAR(10),
SSN_TYPE VARCHAR(40),
GENERIC VARCHAR(40),
BRAND VARCHAR(40),
RECEIVE_DATE TIMESTAMP,
AVAILABLE_QTY INTEGER,
SSN_ID SSN_ID)
AS 
 
DECLARE VARIABLE IMPORTSTATUS VARCHAR(40);
DECLARE VARIABLE WK_ORDER_QTY INTEGER;
DECLARE VARIABLE WK_PICKED_QTY INTEGER;
DECLARE VARIABLE WK_CURRENT_QTY INTEGER;
DECLARE VARIABLE WK_CURRENT_SSN VARCHAR(20);
DECLARE VARIABLE WK_SYS_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_USER_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_USER_ADMIN CHAR(1);
DECLARE VARIABLE WK_USER_INVENTORY_OP CHAR(1);
DECLARE VARIABLE WK_CURRENT_WH WH_ID;
DECLARE VARIABLE WK_CURRENT_COMPANY COMPANY;
BEGIN

/*Frank Leih 10 OCT 2007
I have made the company_id a '|' or ';' or ',' delimited set of selected company's
if the company_id is null -> use all available for that user
most sites have say 10 or 20 wh's
but allow for 100
similarly for the wh_id's
*/

   SELECT CONTROL.PICK_IMPORT_SSN_STATUS,
   CONTROL.COMPANY_ID
   FROM CONTROL
   INTO :IMPORTSTATUS,
        :WK_SYS_COMPANY;

   SELECT SYS_ADMIN, COMPANY_ID, INVENTORY_OPERATOR
   FROM SYS_USER
   WHERE USER_ID = :USER_ID
   INTO :WK_USER_ADMIN,
   :WK_USER_COMPANY,
   :WK_USER_INVENTORY_OP;
 
   IF (WK_USER_ADMIN IS NULL) THEN
   BEGIN
      WK_USER_ADMIN = 'F';
   END
   IF (WK_USER_INVENTORY_OP IS NULL) THEN
   BEGIN
      WK_USER_INVENTORY_OP = 'F';
   END

   IF (WH_IDS IS NULL) THEN
   BEGIN
      WH_IDS = '';
   END
   IF (WH_IDS = '') THEN
   BEGIN
      IF (WK_USER_ADMIN = 'T') THEN
      BEGIN
         FOR SELECT WH_ID FROM WAREHOUSE INTO :WK_CURRENT_WH
         DO
         BEGIN
            WH_IDS = WH_IDS || '|' || :WK_CURRENT_WH;
         END
      END
      ELSE
      BEGIN
         FOR SELECT WH_ID FROM ACCESS_USER WHERE USER_ID = :USER_ID INTO :WK_CURRENT_WH
         DO
         BEGIN
            WH_IDS = WH_IDS || '|' || :WK_CURRENT_WH;
         END
      END
   END
   IF (COMPANY_IDS IS NULL) THEN
   BEGIN
      COMPANY_IDS = '';
   END
   IF (COMPANY_IDS = '') THEN
   BEGIN
      IF ((WK_USER_ADMIN = 'T') OR (WK_USER_INVENTORY_OP = 'T')) THEN
      BEGIN
         FOR SELECT COMPANY_ID FROM COMPANY INTO :WK_CURRENT_COMPANY
         DO
         BEGIN
            COMPANY_IDS = COMPANY_IDS || '|' || :WK_CURRENT_COMPANY;
         END
      END
      ELSE
      BEGIN
         FOR SELECT COMPANY_ID FROM ACCESS_COMPANY WHERE USER_ID = :USER_ID INTO :WK_CURRENT_COMPANY
         DO
         BEGIN
            COMPANY_IDS = COMPANY_IDS || '|' || :WK_CURRENT_COMPANY;
         END
      END
   END

/*         AND (POS(:WH_IDS,ISSN.WH_ID,0,1) > -1)
           AND (POS(:COMPANY_IDS,ISSN.COMPANY_ID,0,1) > -1) */ 
/*         AND (POS(:IMPORTSTATUS,ISSN.ISSN_STATUS,0,1) > -1) */
   FOR SELECT  ISSN.CURRENT_QTY, ISSN.SSN_ID,  ISSN.COMPANY_ID, ISSN.WH_ID, SSN.SSN_TYPE, SSN.GENERIC, SSN.BRAND , GRN.GRN_DATE, GRN.RETURN_ID
           FROM ISSN
           JOIN SSN ON SSN.SSN_ID = ISSN.ORIGINAL_SSN 
           LEFT OUTER JOIN GRN ON GRN.GRN = SSN.GRN 
           WHERE ISSN.PROD_ID = :PROD_ID
              AND (POSITION(ISSN.COMPANY_ID, :COMPANY_IDS,1) > 0)
              AND (POSITION(ISSN.WH_ID, :WH_IDS,1) > 0)
              AND (POSITION(ISSN.ISSN_STATUS, :IMPORTSTATUS,1) > 0)
        INTO :AVAILABLE_QTY, :SSN_ID,  :COMPANY_ID, :WH_ID, :SSN_TYPE, :GENERIC, :BRAND, :RECEIVE_DATE, :SUPPLIER_ID
   DO
   BEGIN
       IF (AVAILABLE_QTY IS NULL) THEN
       BEGIN
            AVAILABLE_QTY = 0;
       END

       SUSPEND;
   END


END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
