COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE OR ALTER PROCEDURE RPT_PRODUCT_RECEIPT_GRN_DATA 
(
  THISPROD_LIST VARCHAR(1240),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD PRODUCT,
  QTY INTEGER,
  TRN_DATE TIMESTAMP,
  THISGRN VARCHAR(30),
  LOCN_ID VARCHAR(30),
  SHORT_DESC SHORT_DESC
)
AS
BEGIN
  /* PROCEDURE BODY */
   IF ((THISPROD_LIST IS NULL) OR (THISPROD_LIST = '')) THEN
   BEGIN
/* transactions archive has the grn in sub_locn_id */
/* now have the company in company field */
      FOR
      SELECT TRANSACTIONS_ARCHIVE.OBJECT , SUM(TRANSACTIONS_ARCHIVE.QTY), ZEROTIME(TRANSACTIONS_ARCHIVE.TRN_DATE), TRANSACTIONS_ARCHIVE.SUB_LOCN_ID , TRANSACTIONS_ARCHIVE.LOCN_ID,PROD_PROFILE.SHORT_DESC
      FROM TRANSACTIONS_ARCHIVE
      JOIN PROD_PROFILE ON TRANSACTIONS_ARCHIVE.OBJECT = PROD_PROFILE.PROD_ID
      AND TRANSACTIONS_ARCHIVE.COMPANY_ID = PROD_PROFILE.COMPANY_ID
      WHERE TRANSACTIONS_ARCHIVE.TRN_TYPE = 'GRNV' AND 
         TRANSACTIONS_ARCHIVE.TRN_CODE IN  ('P','Q') AND 
         (TRANSACTIONS_ARCHIVE.TRN_DATE BETWEEN ZEROTIME(:THISSTART) AND MAXTIME(:THISEND))
       GROUP BY TRANSACTIONS_ARCHIVE.SUB_LOCN_ID, TRANSACTIONS_ARCHIVE.OBJECT, TRANSACTIONS_ARCHIVE.LOCN_ID, ZEROTIME(TRANSACTIONS_ARCHIVE.TRN_DATE), PROD_PROFILE.SHORT_DESC
      INTO
      :PROD,
      :QTY,
      :TRN_DATE,
      :THISGRN,
      :LOCN_ID,
      :SHORT_DESC
      DO
      BEGIN
         SUSPEND;
      END
   END
   ELSE
   BEGIN
/*       (V4POS(:THISPROD_LIST,TRANSACTIONS_ARCHIVE.OBJECT,0,1) > -1) AND */
      FOR
      SELECT TRANSACTIONS_ARCHIVE.OBJECT , SUM(TRANSACTIONS_ARCHIVE.QTY), ZEROTIME(TRANSACTIONS_ARCHIVE.TRN_DATE), TRANSACTIONS_ARCHIVE.SUB_LOCN_ID , TRANSACTIONS_ARCHIVE.LOCN_ID,PROD_PROFILE.SHORT_DESC
      FROM TRANSACTIONS_ARCHIVE
      JOIN PROD_PROFILE ON TRANSACTIONS_ARCHIVE.OBJECT = PROD_PROFILE.PROD_ID
      AND TRANSACTIONS_ARCHIVE.COMPANY_ID = PROD_PROFILE.COMPANY_ID
      WHERE TRANSACTIONS_ARCHIVE.TRN_TYPE = 'GRNV' AND 
         TRANSACTIONS_ARCHIVE.TRN_CODE IN  ('P','Q') AND 
         (POSITION( TRANSACTIONS_ARCHIVE.OBJECT, :THISPROD_LIST, 1) > 0) AND
         (TRANSACTIONS_ARCHIVE.TRN_DATE BETWEEN ZEROTIME(:THISSTART) AND MAXTIME(:THISEND))
       GROUP BY TRANSACTIONS_ARCHIVE.SUB_LOCN_ID, TRANSACTIONS_ARCHIVE.OBJECT, TRANSACTIONS_ARCHIVE.LOCN_ID, ZEROTIME(TRANSACTIONS_ARCHIVE.TRN_DATE), PROD_PROFILE.SHORT_DESC
      INTO
      :PROD,
      :QTY,
      :TRN_DATE,
      :THISGRN,
      :LOCN_ID,
      :SHORT_DESC
      DO
      BEGIN
         SUSPEND;
      END
   END
END
 ^
SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
