
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER TRIGGER ADD_PACK_SSCC FOR PACK_SSCC 
ACTIVE BEFORE INSERT POSITION 10 
AS
DECLARE VARIABLE WK_SO_COMPANY_ID VARCHAR(20);
DECLARE VARIABLE WK_PC_OUT_SSCC_METHOD VARCHAR(40);
DECLARE VARIABLE WK_PS_OUT_SSCC VARCHAR(20);
DECLARE VARIABLE WK_PS_PRODUCT_CNT INTEGER;
BEGIN
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(PACK_SSCC_ID_GEN,1);
   END
   NEW.PS_LAST_UPDATE_DATE = 'NOW';
   IF ((NEW.PS_SSCC IS NULL) OR (NEW.PS_SSCC = '')) THEN
   BEGIN
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      /* SELECT SSCC_ID FROM NEXT_SSCC_ID(NEW.PS_VENDOR_IN_HOUSE_NO) INTO NEW.PS_SSCC; */
      SELECT SSCC_ID FROM NEXT_SSCC_ID(:WK_SO_COMPANY_ID) INTO NEW.PS_SSCC;
   END
   IF ((NEW.PS_OUT_SSCC IS NULL) OR (NEW.PS_OUT_SSCC = '')) THEN
   BEGIN
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      WK_PC_OUT_SSCC_METHOD = '';
      /* get method for ps_out_sscc */
      SELECT  PC_POPULATE_OUT_SSCC_METHOD
      FROM PACK_CUSTOMER
      WHERE PC_CUSTOMER_EDI_NO = NEW.PS_CUSTOMER_EDI_NO
      AND COMPANY_ID = :WK_SO_COMPANY_ID
      INTO :WK_PC_OUT_SSCC_METHOD;
      IF (WK_PC_OUT_SSCC_METHOD IS NULL) THEN
      BEGIN
         WK_PC_OUT_SSCC_METHOD = 'PRODUCT ORDER DELIVER TO';
      END
      IF (WK_PC_OUT_SSCC_METHOD = 'PRODUCT ORDER DELIVER TO') THEN
      BEGIN
         NEW.PS_OUT_SSCC = NEW.PS_SSCC;
      END
      IF (WK_PC_OUT_SSCC_METHOD = 'ORDER DELIVER TO') THEN
      BEGIN
         WK_PS_OUT_SSCC = NULL;
         SELECT FIRST 1 PS_SSCC 
         FROM PACK_SSCC
         WHERE PS_PICK_ORDER = NEW.PS_PICK_ORDER
         AND   PS_DEL_TO_STORE_IN_HOUSE_NO = NEW.PS_DEL_TO_STORE_IN_HOUSE_NO
         AND   PS_SSCC_STATUS  = 'GO'
         AND   (PS_SSCC IS NOT NULL)
         ORDER BY PS_PICK_LABEL_NO
         INTO :WK_PS_OUT_SSCC;
         IF (WK_PS_OUT_SSCC IS NULL) THEN
         BEGIN
            WK_PS_OUT_SSCC = NEW.PS_SSCC;
         END
         NEW.PS_OUT_SSCC = WK_PS_OUT_SSCC;
      END
   END
   IF ((NEW.PS_TOTAL_PRODUCTS_IN_SSCC IS NULL) OR (NEW.PS_TOTAL_PRODUCTS_IN_SSCC = 0)) THEN
   BEGIN
      WK_PS_PRODUCT_CNT = NULL;
      SELECT COUNT(*) FROM (
         SELECT P2.PS_PRODUCT_GTIN
         FROM PACK_SSCC P2
         WHERE P2.PS_OUT_SSCC = NEW.PS_OUT_SSCC
         AND P2.PS_PRODUCT_GTIN <> NEW.PS_PRODUCT_GTIN
         GROUP BY P2.PS_PRODUCT_GTIN)
      INTO :WK_PS_PRODUCT_CNT;
      IF (WK_PS_PRODUCT_CNT IS NULL) THEN
      BEGIN
         WK_PS_PRODUCT_CNT = 0;
      END
      WK_PS_PRODUCT_CNT = WK_PS_PRODUCT_CNT + 1;
      NEW.PS_TOTAL_PRODUCTS_IN_SSCC = WK_PS_PRODUCT_CNT;
      UPDATE PACK_SSCC P2 SET P2.PS_TOTAL_PRODUCTS_IN_SSCC = :WK_PS_PRODUCT_CNT
         WHERE P2.PS_OUT_SSCC = NEW.PS_OUT_SSCC;

   END
END ^

CREATE OR ALTER TRIGGER UPD_PACK_SSCC FOR PACK_SSCC 
ACTIVE BEFORE UPDATE POSITION 10 
AS
DECLARE VARIABLE WK_SO_COMPANY_ID VARCHAR(20);
DECLARE VARIABLE WK_PC_OUT_SSCC_METHOD VARCHAR(40);
DECLARE VARIABLE WK_PS_OUT_SSCC VARCHAR(20);
DECLARE VARIABLE WK_LOG_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LOG_RESULT INTEGER;
DECLARE VARIABLE WK_PS_PRODUCT_CNT INTEGER;
BEGIN
   WK_LOG_FILENAME = '/tmp/UPD_PACK_SSCC.log';
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'start update of PACK_SSCC');
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(PACK_SSCC_ID_GEN,1);
   END
   NEW.PS_LAST_UPDATE_DATE = 'NOW';
   IF ((NEW.PS_SSCC IS NULL) OR (NEW.PS_SSCC = '')) THEN
   BEGIN
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'PS_SSCC is Null');
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'Company ');
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, :WK_SO_COMPANY_ID);
      /* SELECT SSCC_ID FROM NEXT_SSCC_ID(NEW.PS_VENDOR_IN_HOUSE_NO) INTO NEW.PS_SSCC; */
      SELECT SSCC_ID FROM NEXT_SSCC_ID(:WK_SO_COMPANY_ID) INTO NEW.PS_SSCC;
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'created next SSCC');
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, NEW.PS_SSCC);
   END
   IF ((NEW.PS_OUT_SSCC IS NULL) OR (NEW.PS_OUT_SSCC = '')) THEN
   BEGIN
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'PS_OUT_SSCC is Null');
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'Company ');
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, :WK_SO_COMPANY_ID);
      WK_PC_OUT_SSCC_METHOD = '';
      /* get method for ps_out_sscc */
      SELECT  PC_POPULATE_OUT_SSCC_METHOD
      FROM PACK_CUSTOMER
      WHERE PC_CUSTOMER_EDI_NO = NEW.PS_CUSTOMER_EDI_NO
      AND COMPANY_ID = :WK_SO_COMPANY_ID
      INTO :WK_PC_OUT_SSCC_METHOD;
      IF (WK_PC_OUT_SSCC_METHOD IS NULL) THEN
      BEGIN
         WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'PC_OUT_SSCC_METHOD  is Null');
         WK_PC_OUT_SSCC_METHOD = 'PRODUCT ORDER DELIVER TO';
      END
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'PC_OUT_SSCC_METHOD');
      WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, :WK_PC_OUT_SSCC_METHOD);
      IF (WK_PC_OUT_SSCC_METHOD = 'PRODUCT ORDER DELIVER TO') THEN
      BEGIN
         WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'use current PS_SSCC');
         NEW.PS_OUT_SSCC = NEW.PS_SSCC;
      END
      IF (WK_PC_OUT_SSCC_METHOD = 'ORDER DELIVER TO') THEN
      BEGIN
         WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'use method ORDER DELIVER TO');
         WK_PS_OUT_SSCC = NULL;
         SELECT FIRST 1 PS_SSCC 
         FROM PACK_SSCC
         WHERE PS_PICK_ORDER = NEW.PS_PICK_ORDER
         AND   PS_DEL_TO_STORE_IN_HOUSE_NO = NEW.PS_DEL_TO_STORE_IN_HOUSE_NO
         AND   PS_SSCC_STATUS  IN ( 'GO','DC','DX')
         AND   (PS_SSCC IS NOT NULL)
         ORDER BY PS_PICK_LABEL_NO
         INTO :WK_PS_OUT_SSCC;
         IF (WK_PS_OUT_SSCC IS NULL) THEN
         BEGIN
            WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'got Null PS_SSCC to use so use current PS_SSCC');
            WK_PS_OUT_SSCC = NEW.PS_SSCC;
         END
         WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'use as OUT_SSCC');
         WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, :WK_PS_OUT_SSCC);
         NEW.PS_OUT_SSCC = WK_PS_OUT_SSCC;
      END
   END
   IF ((NEW.PS_TOTAL_PRODUCTS_IN_SSCC IS NULL) OR (NEW.PS_TOTAL_PRODUCTS_IN_SSCC = 0)) THEN
   BEGIN
      WK_PS_PRODUCT_CNT = NULL;
      SELECT COUNT(*) FROM (
         SELECT P2.PS_PRODUCT_GTIN
         FROM PACK_SSCC P2
         WHERE P2.PS_OUT_SSCC = NEW.PS_OUT_SSCC
         AND P2.PS_PRODUCT_GTIN <> NEW.PS_PRODUCT_GTIN
         GROUP BY P2.PS_PRODUCT_GTIN)
      INTO :WK_PS_PRODUCT_CNT;
      IF (WK_PS_PRODUCT_CNT IS NULL) THEN
      BEGIN
         WK_PS_PRODUCT_CNT = 0;
      END
      WK_PS_PRODUCT_CNT = WK_PS_PRODUCT_CNT + 1;
      NEW.PS_TOTAL_PRODUCTS_IN_SSCC = WK_PS_PRODUCT_CNT;
      UPDATE PACK_SSCC P2 SET P2.PS_TOTAL_PRODUCTS_IN_SSCC = :WK_PS_PRODUCT_CNT
         WHERE P2.PS_OUT_SSCC = NEW.PS_OUT_SSCC 
         AND P2.RECORD_ID <> NEW.RECORD_ID;

   END
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'end   update of PACK_SSCC');
END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
