
ALTER PROCEDURE UPDATE_SSN_TRIL_A (OBJECT VARCHAR(30),
WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
TRN_DATE TIMESTAMP,
QTY INTEGER)
AS 
                                                       
  DECLARE VARIABLE strORIGINAL_SSN VARCHAR(20);
  DECLARE VARIABLE WK_STATUS VARCHAR(2);
     
BEGIN
   /* Update SSN table */   
/*
   UPDATE SSN
   SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE,
       CURRENT_QTY = CURRENT_QTY + :QTY
   WHERE SSN_ID = :OBJECT;
*/
         
   SELECT ORIGINAL_SSN FROM ISSN 
      WHERE SSN_ID = :OBJECT
      INTO :strORIGINAL_SSN;
   WK_STATUS = 'ST';
   SELECT MOVE_STAT FROM LOCATION 
      WHERE WH_ID = :WH_ID AND LOCN_ID = :LOCN_ID
      INTO :WK_STATUS;
   UPDATE ISSN
   SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE,
       CURRENT_QTY = CURRENT_QTY + :QTY,
       ISSN_STATUS = :WK_STATUS
   WHERE SSN_ID = :OBJECT;
   IF (strORIGINAL_SSN = OBJECT) THEN
   BEGIN
      UPDATE SSN
         SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE,
             STATUS_SSN = :WK_STATUS
      WHERE SSN_ID = :OBJECT;
   END
      
END ^

