

DROP TRIGGER INSERT_TRAINING_SKILL ^
COMMIT^

CREATE TRIGGER INSERT_TRAINING_SKILL FOR TRAINING_SKILL
ACTIVE AFTER  INSERT POSITION 0 
AS
DECLARE VARIABLE WK_PERSON VARCHAR(10);
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_DATE_STR VARCHAR(30) ;
DECLARE VARIABLE WK_BY VARCHAR(10);
DECLARE VARIABLE WK_LOCN VARCHAR(10);
DECLARE VARIABLE WK_AUTH VARCHAR(50);
DECLARE VARIABLE WK_PASS CHAR(1);
DECLARE VARIABLE WK_TRESULT VARCHAR(20);
DECLARE VARIABLE WK_CERT TIMESTAMP;
DECLARE VARIABLE WK_CERT_STR VARCHAR(30) ;
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
BEGIN
   WK_PERSON = NEW.PERSON_ID;
   WK_CODE = NEW.TRAINING_CODE;
   WK_DATE = NEW.TRAINING_DATE;
   WK_DATE_STR = CAST(WK_DATE AS CHAR(22));
   WK_BY = NEW.TRAINING_BY;
   WK_LOCN = NEW.TRAINING_LOCATION;
   WK_AUTH = NEW.TRAINING_AUTHORITY;
   WK_PASS = NEW.TRAINING_PASS;
   WK_TRESULT = NEW.TRAINING_RESULT;
   WK_CERT = NEW.TRAINING_CERT_PRINTED;
   WK_CERT_STR = CAST(WK_CERT AS CHAR(22));
   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'newtskill.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_PERSON) || ',' ||
   SQUOTEDSTR(WK_CODE) || ',' ||
   SQUOTEDSTR(WK_DATE_STR) || ',' ||
   SQUOTEDSTR(WK_BY) || ',' ||
   SQUOTEDSTR(WK_LOCN) || ',' ||
   SQUOTEDSTR(WK_AUTH) || ',' ||
   SQUOTEDSTR(WK_PASS) || ',' ||
   SQUOTEDSTR(WK_TRESULT) || ',' ||
   SQUOTEDSTR(WK_CERT_STR) ;
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'newtskill.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

DROP TRIGGER UPDATE_TRAINING_SKILL ^
COMMIT^

CREATE TRIGGER UPDATE_TRAINING_SKILL FOR TRAINING_SKILL
ACTIVE AFTER  UPDATE POSITION 0 
AS
DECLARE VARIABLE WK_PERSON VARCHAR(10);
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_DATE_STR VARCHAR(30) ;
DECLARE VARIABLE WK_BY VARCHAR(10);
DECLARE VARIABLE WK_LOCN VARCHAR(10);
DECLARE VARIABLE WK_AUTH VARCHAR(50);
DECLARE VARIABLE WK_PASS CHAR(1);
DECLARE VARIABLE WK_TRESULT VARCHAR(20);
DECLARE VARIABLE WK_CERT TIMESTAMP;
DECLARE VARIABLE WK_CERT_STR VARCHAR(30) ;
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
BEGIN
   WK_PERSON = NEW.PERSON_ID;
   WK_CODE = NEW.TRAINING_CODE;
   WK_DATE = NEW.TRAINING_DATE;
   WK_DATE_STR = CAST(WK_DATE AS CHAR(22));
   WK_BY = NEW.TRAINING_BY;
   WK_LOCN = NEW.TRAINING_LOCATION;
   WK_AUTH = NEW.TRAINING_AUTHORITY;
   WK_PASS = NEW.TRAINING_PASS;
   WK_TRESULT = NEW.TRAINING_RESULT;
   WK_CERT = NEW.TRAINING_CERT_PRINTED;
   WK_CERT_STR = CAST(WK_CERT AS CHAR(22));
   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'updtskill.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_PERSON) || ',' ||
   SQUOTEDSTR(WK_CODE) || ',' ||
   SQUOTEDSTR(WK_DATE_STR) || ',' ||
   SQUOTEDSTR(WK_BY) || ',' ||
   SQUOTEDSTR(WK_LOCN) || ',' ||
   SQUOTEDSTR(WK_AUTH) || ',' ||
   SQUOTEDSTR(WK_PASS) || ',' ||
   SQUOTEDSTR(WK_TRESULT) || ',' ||
   SQUOTEDSTR(WK_CERT_STR) ;
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'updtskill.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

