-- where passed :WK_PROD_ID

CREATE PROCEDURE MOVEMENT_HIST (WK_PROD_ID VARCHAR(30) )
   RETURNS (WH_IDi CHAR(2), 
   LOCN_ID VARCHAR(10), 
   SSN_ID VARCHAR(30), 
   TRN_TYPE CHAR(4), 
   TRN_CODE CHAR(1), 
   SUB_LOCN_ID VARCHAR(10), 
   TRN_DATE TIMESTAMP, 
   QTY INTEGER, 
   PERSON_ID VARCHAR(10), 
   DEVICE_ID CHAR(2), 
   REFERENCE VARCHAR(40), 
   ERROR_TEXT VARCHAR(70))
AS

BEGIN
   FOR
      SELECT  SH.WH_ID, :LOCN_ID, :SSN_ID, :TRN_TYPE, :TRN_CODE, :SUB_LOCN_ID, :TRN_DATE, :QTY, :PERSON_ID, DEVICE_ID, :REFERENCE, :ERROR_TEXT
      FROM SSN_HIST SH
      LEFT OUTER JOIN ISSN ON ISSN.SSN_ID = SH.SSN_ID
      JOIN CONTROL ON CONTROL.RECORD_ID = 1
      WHERE 
         (SH.SSN_ID = :WK_PROD_ID
          OR ISSN.PROD_ID = :WK_PROD_ID)
         AND (POS(CONTROL.MOVEMENT_TRANS,SH.TRN_TYPE,0,1) > -1)
       ORDER BY TRN_DATE
       INTO :WH_ID, :LOCN_ID, :SSN_ID, :TRN_TYPE, :TRN_CODE, :SUB_LOCN_ID, :TRN_DATE, :QTY, :PERSON_ID, DEVICE_ID, :REFERENCE, :ERROR_TEXT
    DO
   BEGIN
      SUSPEND;
   END
END^
