ALTER TABLE PICK_LOCATIONS DROP DESCRIPTION;

CREATE TABLE PICK_QTYS (PICK_LABEL_NO PICK_LABEL_NO NOT NULL,
	DESCRIPTION DESCRIPTION,
	PICK_ORDER PICK_ORDER,
	PICK_ORDER_QTY QTY,
        PROD_ID PRODUCT ,
	SSN_ID SSN_ID ,
	UOM CODE_TWO ,
	PICK_LINE_STATUS STATUS,
	DESPATCH_LOCATION DESPATCH_LOCATION );

