SET TERM ^ ;


ALTER PROCEDURE ADD_TRAN (WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
OBJECT VARCHAR(30),
TRN_TYPE VARCHAR(4),
TRN_CODE CHAR(1),
TRN_DATE TIMESTAMP,
REFERENCE VARCHAR(40),
QTY INTEGER,
COMPLETE CHAR(1),
ERROR_TEXT VARCHAR(70),
INSTANCE_ID CHAR(10),
EXPORTED INTEGER,
SUB_LOCN_ID VARCHAR(10),
INPUT_SOURCE VARCHAR(10),
PERSON_ID VARCHAR(10),
DEVICE_ID CHAR(2))
AS 
 
 
        
  DECLARE VARIABLE REC_EXIST INTEGER; 
  DECLARE VARIABLE REC_ID INTEGER;   
BEGIN
  REC_EXIST = 0;   

  /* Check if record exists */
  SELECT COUNT(OBJECT)
  FROM TRANSACTIONS
  WHERE WH_ID = :WH_ID
  AND LOCN_ID = :LOCN_ID
  AND OBJECT = :OBJECT
  AND TRN_TYPE = :TRN_TYPE 
  AND TRN_CODE = :TRN_CODE 
  AND TRN_DATE = :TRN_DATE 
  AND PERSON_ID = :PERSON_ID
  AND DEVICE_ID = :DEVICE_ID
  AND COMPLETE = 'F' 
  INTO :REC_EXIST;  
  
  /* record is not exists, then insert new record */
  IF (REC_EXIST = 0) THEN
  BEGIN  
    REC_ID = GEN_ID(TRANSACTION_ID, 1);    
    INSERT INTO TRANSACTIONS   
           (RECORD_ID, WH_ID, LOCN_ID, OBJECT, TRN_TYPE, TRN_CODE, TRN_DATE, REFERENCE, QTY, COMPLETE, ERROR_TEXT, INSTANCE_ID, EXPORTED, SUB_LOCN_ID, INPUT_SOURCE, PERSON_ID, DEVICE_ID)
    VALUES (:REC_ID, :WH_ID, :LOCN_ID, :OBJECT, :TRN_TYPE, :TRN_CODE, :TRN_DATE, :REFERENCE, :QTY, :COMPLETE, :ERROR_TEXT, :INSTANCE_ID, :EXPORTED, :SUB_LOCN_ID, :INPUT_SOURCE, :PERSON_ID, :DEVICE_ID);
  END
  ELSE
  BEGIN
    UPDATE TRANSACTIONS
      SET	
          	REFERENCE = :REFERENCE, 
		QTY = :QTY, 
          	ERROR_TEXT = :ERROR_TEXT, 
		INSTANCE_ID = :INSTANCE_ID, 
          	EXPORTED = :EXPORTED, 
		SUB_LOCN_ID = :SUB_LOCN_ID, 
          	INPUT_SOURCE = :INPUT_SOURCE  
  WHERE WH_ID = :WH_ID
  AND LOCN_ID = :LOCN_ID
  AND OBJECT = :OBJECT
  AND TRN_TYPE = :TRN_TYPE 
  AND TRN_CODE = :TRN_CODE 
  AND TRN_DATE = :TRN_DATE 
  AND PERSON_ID = :PERSON_ID
  AND DEVICE_ID = :DEVICE_ID
  AND COMPLETE = 'F';
  END
END ^

