SET TERM ^ ;

ALTER PROCEDURE ADD_TRAN_ERROR (WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
OBJECT VARCHAR(30),
TRN_TYPE VARCHAR(4),
TRN_CODE CHAR(1),
TRN_DATE TIMESTAMP,
REFERENCE VARCHAR(40),
QTY INTEGER,
COMPLETE CHAR(1),
ERROR_TEXT VARCHAR(70),
INSTANCE_ID CHAR(10),
EXPORTED INTEGER,
SUB_LOCN_ID VARCHAR(10),
INPUT_SOURCE VARCHAR(10),
PERSON_ID VARCHAR(10),
DEVICE_ID CHAR(2))
AS 
 
 
      
  DECLARE VARIABLE REC_ID INTEGER; 
BEGIN
  REC_ID = GEN_ID(TRANSACTION_ID, 1); 
    
  INSERT INTO TRAN_ERROR   
         (RECORD_ID, WH_ID, LOCN_ID, OBJECT, TRN_TYPE, TRN_CODE, TRN_DATE, REFERENCE, QTY, COMPLETE, ERROR_TEXT, INSTANCE_ID, EXPORTED, SUB_LOCN_ID, INPUT_SOURCE, PERSON_ID, DEVICE_ID)
  VALUES (:REC_ID, :WH_ID, :LOCN_ID, :OBJECT, :TRN_TYPE, :TRN_CODE, :TRN_DATE, :REFERENCE, :QTY, :COMPLETE, :ERROR_TEXT, :INSTANCE_ID, :EXPORTED, :SUB_LOCN_ID, :INPUT_SOURCE, :PERSON_ID, :DEVICE_ID);
  
END ^

