SET TERM ^ ;

ALTER PROCEDURE ADD_SSN_HIST (WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
SSN_ID VARCHAR(20),
TRN_TYPE VARCHAR(4),
TRN_CODE CHAR(1),
TRN_DATE TIMESTAMP,
ERROR_TEXT VARCHAR(70),
REFERENCE VARCHAR(40),
QTY INTEGER,
PERSON_ID VARCHAR(10),
DEVICE_ID CHAR(2))
AS 
 
DECLARE VARIABLE REC_NO INTEGER;
BEGIN
   REC_NO = GEN_ID(SSN_HIST_RECORD_ID, 1);  
   INSERT INTO SSN_HIST   
        (RECORD_ID, WH_ID, LOCN_ID, SSN_ID, TRN_TYPE, TRN_CODE, TRN_DATE, 
         REFERENCE, QTY, ERROR_TEXT, PERSON_ID, DEVICE_ID)
   VALUES (:REC_NO, :WH_ID, :LOCN_ID,:SSN_ID, :TRN_TYPE, :TRN_CODE, :TRN_DATE, 
         :REFERENCE, :QTY, :ERROR_TEXT, :PERSON_ID, :DEVICE_ID);

   SUSPEND;
END ^

