ALTER TABLE PERSON ADD SAVE_FAX VARCHAR(30);
ALTER TABLE PERSON ADD SAVE_PHONE VARCHAR(30);

COMMIT;

UPDATE PERSON SET SAVE_FAX = SECOND_FAX_NO,SAVE_PHONE=SECOND_PHONE_NO;

COMMIT;

ALTER TABLE PERSON  DROP SECOND_FAX_NO ;
ALTER TABLE PERSON  DROP SECOND_PHONE_NO ;

COMMIT;
DROP DOMAIN SECOND_FAX_NO;
DROP DOMAIN SECOND_PHONE_NO;

COMMIT;

CREATE DOMAIN SECOND_FAX_NO AS VARCHAR(30);
CREATE DOMAIN SECOND_PHONE_NO AS VARCHAR(30);

COMMIT;

ALTER TABLE PERSON  ADD SECOND_FAX_NO SECOND_FAX_NO;
ALTER TABLE PERSON  ADD SECOND_PHONE_NO SECOND_PHONE_NO;

COMMIT;
UPDATE PERSON  SET SECOND_FAX_NO = SAVE_FAX,SECOND_PHONE_NO = SAVE_PHONE;

COMMIT;
ALTER TABLE PERSON  DROP SAVE_FAX ;
ALTER TABLE PERSON  DROP SAVE_PHONE ;

COMMIT;

