ALTER TABLE COMPANY ADD SAVE_FAX VARCHAR(30);
ALTER TABLE COMPANY ADD SAVE_PHONE VARCHAR(30);
ALTER TABLE PERSON ADD SAVE_FAX VARCHAR(30);
ALTER TABLE PERSON ADD SAVE_PHONE VARCHAR(30);
ALTER TABLE LOCN_ADDRESS ADD SAVE_PHONE VARCHAR(30);

COMMIT;

UPDATE COMPANY SET SAVE_FAX = FAX_NO,SAVE_PHONE=PHONE_NO;
UPDATE PERSON SET SAVE_FAX = FAX_NO,SAVE_PHONE=PHONE_NO;
UPDATE LOCN_ADDRESS SET SAVE_PHONE=PHONE_NO;

COMMIT;

ALTER TABLE COMPANY DROP FAX_NO ;
ALTER TABLE COMPANY DROP PHONE_NO ;
ALTER TABLE PERSON  DROP FAX_NO ;
ALTER TABLE PERSON  DROP PHONE_NO ;
ALTER TABLE LOCN_ADDRESS  DROP PHONE_NO ;

COMMIT;
DROP DOMAIN FAX_NO;
DROP DOMAIN PHONE_NO;

COMMIT;

CREATE DOMAIN FAX_NO AS VARCHAR(30);
CREATE DOMAIN PHONE_NO AS VARCHAR(30);

COMMIT;
ALTER TABLE COMPANY ADD FAX_NO FAX_NO;
ALTER TABLE COMPANY ADD PHONE_NO PHONE_NO;

ALTER TABLE PERSON  ADD FAX_NO FAX_NO;
ALTER TABLE PERSON  ADD PHONE_NO PHONE_NO;

ALTER TABLE LOCN_ADDRESS  ADD PHONE_NO PHONE_NO;

COMMIT;
UPDATE COMPANY SET FAX_NO = SAVE_FAX,PHONE_NO = SAVE_PHONE;
UPDATE PERSON  SET FAX_NO = SAVE_FAX,PHONE_NO = SAVE_PHONE;
UPDATE LOCN_ADDRESS SET PHONE_NO = SAVE_PHONE;

COMMIT;
ALTER TABLE COMPANY DROP SAVE_FAX ;
ALTER TABLE COMPANY DROP SAVE_PHONE ;
ALTER TABLE PERSON  DROP SAVE_FAX ;
ALTER TABLE PERSON  DROP SAVE_PHONE ;
ALTER TABLE LOCN_ADDRESS  DROP SAVE_PHONE ;

COMMIT;

