 
CREATE TRIGGER RUN_TRANSACTION_NIDP FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 45 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NIDP') THEN
  BEGIN
   EXECUTE PROCEDURE PC_ADD_PROD_COND_STATUS 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID;
   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
 
CREATE TRIGGER RUN_TRANSACTION_NXDP FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 46 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NXDP') THEN
  BEGIN
   EXECUTE PROCEDURE PC_DELETE_ONE_PROD_COND_STATUS 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID;
   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
 
CREATE TRIGGER RUN_TRANSACTION_NIEP FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 47 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NIEP') THEN
  BEGIN
   EXECUTE PROCEDURE PC_ADD_PROD_COND_STATUS 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID;
   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
 
CREATE TRIGGER RUN_TRANSACTION_NXEP FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 48 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NXEP') THEN
  BEGIN
   EXECUTE PROCEDURE PC_DELETE_ONE_PROD_COND_STATUS 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID;
   EXECUTE PROCEDURE TRAN_ARCHIVE;
  END
 END
END ^
 
