CREATE PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (PROD_ID VARCHAR(30) CHARACTER SET NONE,
SSN_ID VARCHAR(20) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
THISCOMPANY_ID VARCHAR(20) CHARACTER SET NONE,
TRN_TYPE VARCHAR(4) CHARACTER SET NONE,
TRN_CODE VARCHAR(1) CHARACTER SET NONE,
CURRENT_QTY INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (WH_ID1 VARCHAR(30) CHARACTER SET NONE,
LOCN_ID1 VARCHAR(30) CHARACTER SET NONE,
WH_ID2 VARCHAR(30) CHARACTER SET NONE,
LOCN_ID2 VARCHAR(30) CHARACTER SET NONE,
PROD_ID VARCHAR(30) CHARACTER SET NONE,
DESCRIPTION VARCHAR(50) CHARACTER SET NONE,
QTY INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (PICK_ORDER VARCHAR(30) CHARACTER SET NONE,
THISPICKORDER VARCHAR(30) CHARACTER SET NONE,
PROD_ID VARCHAR(30) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
QTY VARCHAR(30) CHARACTER SET NONE,
COMPANY_ID VARCHAR(30) CHARACTER SET NONE,
TRN_DATE TIMESTAMP)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_CANCELLED_DATA (THISPICK_ORDER VARCHAR(50) CHARACTER SET NONE)
RETURNS (PICK_ORDER VARCHAR(50) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
PROD_ID VARCHAR(50) CHARACTER SET NONE,
PICK_LABEL_NO VARCHAR(50) CHARACTER SET NONE)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_2_A_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_2_B_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_3_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_4_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_5_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_DAILY_6_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_PRODUCT_LEVELS_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^
CREATE PROCEDURE RPT_PRODUCT_RECEIPT_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 
BEGIN EXIT; END ^

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (PROD_ID VARCHAR(30) CHARACTER SET NONE,
SSN_ID VARCHAR(20) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
THISCOMPANY_ID VARCHAR(20) CHARACTER SET NONE,
TRN_TYPE VARCHAR(4) CHARACTER SET NONE,
TRN_CODE VARCHAR(1) CHARACTER SET NONE,
CURRENT_QTY INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR
SELECT ISSN.PROD_ID, SSN_ID,PROD_PROFILE.SHORT_DESC,PROD_PROFILE.COMPANY_ID AS THISCOMPANY_ID, TRN_TYPE,TRN_CODE,ISSN.CURRENT_QTY
FROM ISSN
INNER JOIN  TRANSACTIONS_ARCHIVE ON ISSN.SSN_ID = TRANSACTIONS_ARCHIVE.OBJECT
INNER JOIN  PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
WHERE TRN_TYPE = 'TRIL' AND TRN_CODE = 'W' AND PROD_PROFILE.COMPANY_ID = :THISCOMPANY
ORDER BY PROD_PROFILE.COMPANY_ID, PROD_PROFILE.PROD_ID

  INTO
          :PROD_ID,
          :SSN_ID,
          :SHORT_DESC,
          :THISCOMPANY_ID,
          :TRN_TYPE,
          :TRN_CODE,
          :CURRENT_QTY
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (WH_ID1 VARCHAR(30) CHARACTER SET NONE,
LOCN_ID1 VARCHAR(30) CHARACTER SET NONE,
WH_ID2 VARCHAR(30) CHARACTER SET NONE,
LOCN_ID2 VARCHAR(30) CHARACTER SET NONE,
PROD_ID VARCHAR(30) CHARACTER SET NONE,
DESCRIPTION VARCHAR(50) CHARACTER SET NONE,
QTY INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR
    SELECT SSN_HIST.WH_ID AS WH_ID1,SSN_HIST.LOCN_ID AS LOCN_ID1,
       SSN_HIST.WH_ID AS WH_ID2,SSN_HIST.LOCN_ID AS LOCN_ID2,ISSN.PROD_ID,
       SSN_HIST.SSN_ID AS DESCRIPTION, ISSN.CURRENT_QTY AS QTY
    FROM SSN_HIST
    LEFT OUTER JOIN  SSN ON SSN_HIST.SSN_ID = SSN.SSN_ID
    LEFT OUTER JOIN  ISSN ON SSN_HIST.SSN_ID = ISSN.SSN_ID
    WHERE TRN_TYPE = 'TRLI' AND SSN.COMPANY_ID = :THISCOMPANY
    AND  (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND )

  INTO
:WH_ID1,
:LOCN_ID1,
:WH_ID2,
:LOCN_ID2,
:PROD_ID,
:DESCRIPTION,
:QTY
 
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA (THISCOMPANY VARCHAR(20) CHARACTER SET NONE,
THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (PICK_ORDER VARCHAR(30) CHARACTER SET NONE,
THISPICKORDER VARCHAR(30) CHARACTER SET NONE,
PROD_ID VARCHAR(30) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
QTY VARCHAR(30) CHARACTER SET NONE,
COMPANY_ID VARCHAR(30) CHARACTER SET NONE,
TRN_DATE TIMESTAMP)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR
 SELECT DISTINCT(PICK_ITEM.PICK_ORDER) AS THISPICKORDER ,PROD_PROFILE.PROD_ID, PROD_PROFILE.SHORT_DESC, COUNT(PICK_ITEM.PICK_ORDER) , ISSN.COMPANY_ID,TRANSACTIONS_ARCHIVE.TRN_DATE
FROM ISSN
   INNER JOIN PICK_ITEM_DETAIL ON ISSN.SSN_ID = PICK_ITEM_DETAIL.SSN_ID
   INNER JOIN PICK_ITEM ON PICK_ITEM_DETAIL.PICK_LABEL_NO = PICK_ITEM.PICK_LABEL_NO
   INNER JOIN PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
   LEFT OUTER JOIN TRANSACTIONS_ARCHIVE ON PICK_ITEM_DETAIL.SSN_ID = TRANSACTIONS_ARCHIVE.OBJECT
   WHERE ISSN.COMPANY_ID = :THISCOMPANY
    AND  (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND )
   GROUP BY ISSN.COMPANY_ID,TRANSACTIONS_ARCHIVE.TRN_DATE, PICK_ITEM.PICK_ORDER , PROD_PROFILE.PROD_ID,PROD_PROFILE.SHORT_DESC
  INTO
:THISPICKORDER,
:PROD_ID,
:SHORT_DESC,
:QTY,
:COMPANY_ID,
:TRN_DATE
  DO
  BEGIN
  PICK_ORDER = THISPICKORDER;
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_CANCELLED_DATA (THISPICK_ORDER VARCHAR(50) CHARACTER SET NONE)
RETURNS (PICK_ORDER VARCHAR(50) CHARACTER SET NONE,
SHORT_DESC VARCHAR(50) CHARACTER SET NONE,
PROD_ID VARCHAR(50) CHARACTER SET NONE,
PICK_LABEL_NO VARCHAR(50) CHARACTER SET NONE)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR
 SELECT PICK_ITEM.PICK_ORDER, PROD_PROFILE.SHORT_DESC, PICK_ITEM.PROD_ID, PICK_ITEM.PICK_LABEL_NO
FROM PICK_ITEM
 INNER JOIN PICK_ITEM_DETAIL ON PICK_ITEM.PICK_LABEL_NO = PICK_ITEM_DETAIL.PICK_LABEL_NO
 LEFT OUTER JOIN PROD_PROFILE ON PROD_PROFILE.PROD_ID = PICK_ITEM.PROD_ID
 WHERE PICK_DETAIL_STATUS = 'XX' AND PICK_ITEM.PICK_ORDER = :THISPICK_ORDER
ORDER BY PICK_ITEM.PROD_ID

  INTO
:PICK_ORDER,
:SHORT_DESC ,
:PROD_ID,
:PICK_LABEL_NO 

  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_2_A_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_2_B_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_3_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_4_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_5_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_DAILY_6_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_PRODUCT_LEVELS_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

ALTER PROCEDURE RPT_PRODUCT_RECEIPT_DATA (THISSTART TIMESTAMP,
THISEND TIMESTAMP)
RETURNS (THISCOUNT INTEGER)
AS 


BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END ^

