COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */

/*
CREATE PROCEDURE RPT_ARCHIVE_DATA 
(
  THISWHID VARCHAR(2)
)
RETURNS
(
  WH_ID VARCHAR(2),
  LOCN_ID VARCHAR(10),
  PROD_ID VARCHAR(30),
  CURRENT_QTY VARCHAR(10),
  SHORT_DESC VARCHAR(50),
  MOVE_STAT VARCHAR(2),
  NAME VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_ARCHIVE_DATA 
(
  THISWHID VARCHAR(2)
)
RETURNS
(
  WH_ID VARCHAR(2),
  LOCN_ID VARCHAR(10),
  PROD_ID VARCHAR(30),
  CURRENT_QTY VARCHAR(10),
  SHORT_DESC VARCHAR(50),
  MOVE_STAT VARCHAR(2),
  NAME VARCHAR(50)
)
AS
BEGIN

      FOR SELECT ISSN.WH_ID, ISSN.LOCN_ID,ISSN.PROD_ID,ISSN.CURRENT_QTY,PROD_PROFILE.SHORT_DESC, LOCATION.MOVE_STAT , COMPANY.NAME
          FROM ISSN
          LEFT OUTER JOIN PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
          LEFT OUTER JOIN LOCATION ON ISSN.LOCN_ID = LOCATION.LOCN_ID
          LEFT OUTER JOIN COMPANY ON ISSN.COMPANY_ID = COMPANY.COMPANY_ID
          WHERE ((LOCATION.MOVE_STAT <> 'ST') AND (LOCATION.MOVE_STAT <> 'RC') AND (LOCATION.MOVE_STAT IS NOT NULL) AND (ISSN.WH_ID = :THISWHID ))

      INTO
      :WH_ID,
    :LOCN_ID,
    :PROD_ID,
    :CURRENT_QTY,
    :SHORT_DESC,
    :MOVE_STAT,
    :NAME

      DO
      BEGIN
         SUSPEND;
      END
   -- END

END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SSN_ID VARCHAR(20),
  SHORT_DESC VARCHAR(50),
  THISCOMPANY_ID VARCHAR(20),
  TRN_TYPE VARCHAR(4),
  TRN_CODE VARCHAR(1),
  CURRENT_QTY INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SSN_ID VARCHAR(20),
  SHORT_DESC VARCHAR(50),
  THISCOMPANY_ID VARCHAR(20),
  TRN_TYPE VARCHAR(4),
  TRN_CODE VARCHAR(1),
  CURRENT_QTY INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
SELECT ISSN.PROD_ID, SSN_ID,PROD_PROFILE.SHORT_DESC,PROD_PROFILE.COMPANY_ID AS THISCOMPANY_ID, TRN_TYPE,TRN_CODE,ISSN.CURRENT_QTY
FROM ISSN
INNER JOIN  TRANSACTIONS_ARCHIVE ON ISSN.SSN_ID = TRANSACTIONS_ARCHIVE.OBJECT
INNER JOIN  PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
WHERE TRN_TYPE = 'TRIL' AND TRN_CODE = 'W' AND PROD_PROFILE.COMPANY_ID = :THISCOMPANY
ORDER BY PROD_PROFILE.COMPANY_ID, PROD_PROFILE.PROD_ID

  INTO
          :PROD_ID,
          :SSN_ID,
          :SHORT_DESC,
          :THISCOMPANY_ID,
          :TRN_TYPE,
          :TRN_CODE,
          :CURRENT_QTY
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  WH_ID1 VARCHAR(30),
  LOCN_ID1 VARCHAR(30),
  WH_ID2 VARCHAR(30),
  LOCN_ID2 VARCHAR(30),
  PROD_ID VARCHAR(30),
  DESCRIPTION VARCHAR(50),
  QTY INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  WH_ID1 VARCHAR(30),
  LOCN_ID1 VARCHAR(30),
  WH_ID2 VARCHAR(30),
  LOCN_ID2 VARCHAR(30),
  PROD_ID VARCHAR(30),
  DESCRIPTION VARCHAR(50),
  QTY INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
    SELECT SSN_HIST.WH_ID AS WH_ID1,SSN_HIST.LOCN_ID AS LOCN_ID1,
       SSN_HIST.WH_ID AS WH_ID2,SSN_HIST.LOCN_ID AS LOCN_ID2,ISSN.PROD_ID,
       SSN_HIST.SSN_ID AS DESCRIPTION, ISSN.CURRENT_QTY AS QTY
    FROM SSN_HIST
    LEFT OUTER JOIN  SSN ON SSN_HIST.SSN_ID = SSN.SSN_ID
    LEFT OUTER JOIN  ISSN ON SSN_HIST.SSN_ID = ISSN.SSN_ID
    WHERE TRN_TYPE = 'TRLI' AND SSN.COMPANY_ID = :THISCOMPANY
    AND  (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND )

  INTO
:WH_ID1,
:LOCN_ID1,
:WH_ID2,
:LOCN_ID2,
:PROD_ID,
:DESCRIPTION,
:QTY
 
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PICK_ORDER VARCHAR(30),
  THISPICKORDER VARCHAR(30),
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  QTY VARCHAR(30),
  COMPANY_ID VARCHAR(30),
  TRN_DATE TIMESTAMP
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PICK_ORDER VARCHAR(30),
  THISPICKORDER VARCHAR(30),
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  QTY VARCHAR(30),
  COMPANY_ID VARCHAR(30),
  TRN_DATE TIMESTAMP
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
 SELECT DISTINCT(PICK_ITEM.PICK_ORDER) AS THISPICKORDER ,PROD_PROFILE.PROD_ID, PROD_PROFILE.SHORT_DESC, COUNT(PICK_ITEM.PICK_ORDER) , ISSN.COMPANY_ID,TRANSACTIONS_ARCHIVE.TRN_DATE
FROM ISSN
   INNER JOIN PICK_ITEM_DETAIL ON ISSN.SSN_ID = PICK_ITEM_DETAIL.SSN_ID
   INNER JOIN PICK_ITEM ON PICK_ITEM_DETAIL.PICK_LABEL_NO = PICK_ITEM.PICK_LABEL_NO
   INNER JOIN PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
   LEFT OUTER JOIN TRANSACTIONS_ARCHIVE ON PICK_ITEM_DETAIL.SSN_ID = TRANSACTIONS_ARCHIVE.OBJECT
   WHERE ISSN.COMPANY_ID = :THISCOMPANY
    AND  (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND )
   GROUP BY ISSN.COMPANY_ID,TRANSACTIONS_ARCHIVE.TRN_DATE, PICK_ITEM.PICK_ORDER , PROD_PROFILE.PROD_ID,PROD_PROFILE.SHORT_DESC
  INTO
:THISPICKORDER,
:PROD_ID,
:SHORT_DESC,
:QTY,
:COMPANY_ID,
:TRN_DATE
  DO
  BEGIN
  PICK_ORDER = THISPICKORDER;
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_CANCELLED_DATA 
(
  THISPICK_ORDER VARCHAR(50)
)
RETURNS
(
  PICK_ORDER VARCHAR(50),
  SHORT_DESC VARCHAR(50),
  PROD_ID VARCHAR(50),
  PICK_LABEL_NO VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_CANCELLED_DATA 
(
  THISPICK_ORDER VARCHAR(50)
)
RETURNS
(
  PICK_ORDER VARCHAR(50),
  SHORT_DESC VARCHAR(50),
  PROD_ID VARCHAR(50),
  PICK_LABEL_NO VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
 SELECT PICK_ITEM.PICK_ORDER, PROD_PROFILE.SHORT_DESC, PICK_ITEM.PROD_ID, PICK_ITEM.PICK_LABEL_NO
FROM PICK_ITEM
 INNER JOIN PICK_ITEM_DETAIL ON PICK_ITEM.PICK_LABEL_NO = PICK_ITEM_DETAIL.PICK_LABEL_NO
 LEFT OUTER JOIN PROD_PROFILE ON PROD_PROFILE.PROD_ID = PICK_ITEM.PROD_ID
 WHERE PICK_DETAIL_STATUS = 'XX' AND PICK_ITEM.PICK_ORDER = :THISPICK_ORDER
ORDER BY PICK_ITEM.PROD_ID

  INTO
:PICK_ORDER,
:SHORT_DESC ,
:PROD_ID,
:PICK_LABEL_NO 

  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_1_A_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_1_A_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL'
  -- AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_1_B_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_1_B_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKCA'
  --AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_2_A_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  QTYTOTAL INTEGER,
  PROD_ID VARCHAR(50),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_2_A_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  QTYTOTAL INTEGER,
  PROD_ID VARCHAR(50),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR

 SELECT COUNT(*) AS QTYTOTAL,PICK_ITEM.PROD_ID,PROD_PROFILE.SHORT_DESC  FROM TRANSACTIONS_ARCHIVE
LEFT OUTER  JOIN PICK_ITEM ON TRANSACTIONS_ARCHIVE.OBJECT = PICK_ITEM.PICK_ORDER
LEFT OUTER  JOIN PROD_PROFILE ON PICK_ITEM.PROD_ID = PROD_PROFILE.PROD_ID
WHERE TRN_TYPE = 'PKAL'
--AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
GROUP BY PICK_ITEM.PROD_ID,PROD_PROFILE.SHORT_DESC

  INTO
  :QTYTOTAL,
  :PROD_ID,
  :SHORT_DESC
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_2_B_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  QTYTOTAL INTEGER,
  PROD_ID VARCHAR(50),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_2_B_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  QTYTOTAL INTEGER,
  PROD_ID VARCHAR(50),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR

 SELECT COUNT(*) AS QTYTOTAL,PICK_ITEM.PROD_ID,PROD_PROFILE.SHORT_DESC  FROM TRANSACTIONS_ARCHIVE
LEFT OUTER  JOIN PICK_ITEM ON TRANSACTIONS_ARCHIVE.OBJECT = PICK_ITEM.PICK_ORDER
LEFT OUTER  JOIN PROD_PROFILE ON PICK_ITEM.PROD_ID = PROD_PROFILE.PROD_ID
WHERE TRN_TYPE = 'PKAL'
--AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
GROUP BY PICK_ITEM.PROD_ID,PROD_PROFILE.SHORT_DESC

  INTO
  :QTYTOTAL,
  :PROD_ID,
  :SHORT_DESC
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_3_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_3_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL'
  -- AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_4_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_4_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_5_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_5_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR SELECT COUNT(*) AS THISCOUNT  FROM TRANSACTIONS_ARCHIVE
  WHERE   TRN_TYPE = 'PKAL'
  --- AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND)
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_DAILY_6_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_DAILY_6_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  /* PROCEDURE BODY */
  FOR
SELECT  COUNT(DISTINCT(PICK_ITEM.PICK_ORDER))
FROM PICK_ORDER
INNER JOIN PICK_ITEM ON PICK_ORDER.PICK_ORDER = PICK_ITEM.PICK_ORDER
INNER JOIN SYS_USER ON PICK_ITEM.USER_ID = SYS_USER.USER_ID
WHERE ASSEMBLY_STARTED > 'TODAY'
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_PRODUCT_LEVELS_DATA 
(
  THISWHID VARCHAR(4)
)
RETURNS
(
  LOCN_ID VARCHAR(50),
  PROD_ID VARCHAR(50),
  CURRENT_QTY INTEGER,
  SHORT_DES VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_PRODUCT_LEVELS_DATA 
(
  THISWHID VARCHAR(4)
)
RETURNS
(
  LOCN_ID VARCHAR(50),
  PROD_ID VARCHAR(50),
  CURRENT_QTY INTEGER,
  SHORT_DES VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
   SELECT LOCN_ID,ISSN.PROD_ID,CURRENT_QTY,PROD_PROFILE.SHORT_DESC
   FROM ISSN
   LEFT OUTER JOIN PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
   WHERE ISSN.WH_ID = :THISWHID

  INTO
  :LOCN_ID,
  :PROD_ID,
  :CURRENT_QTY,
  :SHORT_DES
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_PRODUCT_RECEIPT_DATA 
(
  THISPROD_ID VARCHAR(30),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD VARCHAR(30),
  QTY INTEGER,
  TRN_DATE TIMESTAMP,
  THISGRN VARCHAR(30),
  LOCN_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_PRODUCT_RECEIPT_DATA 
(
  THISPROD_ID VARCHAR(30),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD VARCHAR(30),
  QTY INTEGER,
  TRN_DATE TIMESTAMP,
  THISGRN VARCHAR(30),
  LOCN_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
  SELECT OBJECT AS PROD, QTY, TRN_DATE, TRANSACTIONS_ARCHIVE.SUB_LOCN_ID AS THISGRN, LOCN_ID,PROD_PROFILE.SHORT_DESC
  FROM TRANSACTIONS_ARCHIVE
  LEFT OUTER JOIN PROD_PROFILE ON TRANSACTIONS_ARCHIVE.OBJECT = PROD_PROFILE.PROD_ID
  WHERE TRN_TYPE = 'GRNV' AND TRN_CODE = 'P' AND (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND) AND PROD_PROFILE.PROD_ID = :THISPROD_ID
  INTO
:PROD,
:QTY,
:TRN_DATE,
:THISGRN,
:LOCN_ID,
:SHORT_DESC
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
