/*
CREATE TABLE PURCHASE_ORDER (PURCHASE_ORDER PURCHASE_ORDER NOT NULL,
5898:PRIMARY KEY (PURCHASE_ORDER));
CREATE TABLE PURCHASE_ORDER_LINE (PURCHASE_ORDER PURCHASE_ORDER NOT NULL,
5933:PRIMARY KEY (PURCHASE_ORDER, PO_LINE));
*/

alter table purchase_order_line drop constraint INTEG_131;
alter table purchase_order drop constraint INTEG_128;
commit;
