/*
re-create indexes
>>>PURCHASEORDER_IX UNIQUE INDEX ON PURCHASE_ORDER(PURCHASE_ORDER) 
7991:CREATE UNIQUE INDEX PURCHASELINES_IX ON PURCHASE_ORDER_LINE (PURCHASE_ORDER, PO_LINE);

7985:CREATE INDEX PO_ITEM_DETAIL_PO_IDX ON PURCHASE_LINE_DETAIL (PURCHASE_ORDER, PO_LINE);
7989:CREATE INDEX POL_REVISED_IDX ON PURCHASE_LINE_REVISED (PURCHASE_ORDER, PO_LINE);
7990:CREATE UNIQUE INDEX PURCHASEORDER_IX ON PURCHASE_ORDER (PURCHASE_ORDER);
7991:CREATE UNIQUE INDEX PURCHASELINES_IX ON PURCHASE_ORDER_LINE (PURCHASE_ORDER, PO_LINE);
7995:CREATE INDEX PO_ITEM_SUB_PO_IDX ON PURCHASE_SUB_LINE (PURCHASE_ORDER, PO_LINE);
*/
CREATE INDEX PO_ITEM_DETAIL_PO_IDX ON PURCHASE_LINE_DETAIL (PURCHASE_ORDER, PO_LINE);
CREATE INDEX POL_REVISED_IDX ON PURCHASE_LINE_REVISED (PURCHASE_ORDER, PO_LINE);
CREATE INDEX PO_ITEM_SUB_PO_IDX ON PURCHASE_SUB_LINE (PURCHASE_ORDER, PO_LINE);
commit;

