
CREATE TABLE EMPLOYEE (
	PERSON_ID PERSON NOT NULL ,
	COMPANY_ID COMPANY,
	TITLE TITLE,
	OCCUPATION OCCUPATION,
	POSITION_TITLE CODE,
	DOB CREATE_DATE,
	GENDER GENDER,
	PREFERRED_LANGUAGE LANGUAGE,
	UNION_MEMBERSHIP CODE,
	UNION_MEMBERSHIP_NO UNION_MEMBERSHIP_NO,
	SUPERANNUATION_FUND CODE,
	SUPERANNUATION_NO SUPERANNUATION_NO,
	NOTES DISPOSAL_NOTES,
	DRIVER_LICENSE_NO DRIVER_LICENSE_NO,
	DRIVER_LICENSE_STATE DRIVER_LICENSE_STATE,
	DRIVER_LICENSE_CLASS DRIVER_LICENSE_CLASS,
	DRIVER_LICENSE_EXPIRY DRIVER_LICENSE_EXPIRY ,
	EMPLOYEE_UDF1 CODE,
	EMPLOYEE_UDF2 CODE,
	EMPLOYEE_UDF3 CODE,
	EMPLOYEE_UDF4 CODE,
	EMPLOYEE_UDF5 CODE,
	EMPLOYEE_UDF6 CODE,
	EMPLOYEE_UDF7 CODE,
	EMPLOYEE_UDF8 OTHER_DATE,
	EMPLOYEE_UDF9 CODE,
	EMPLOYEE_UDF10 OTHER_DATE,
	NEXT_OF_KIN_TITLE TITLE,
	NEXT_OF_KIN_FIRST_NAME FIRST_NAME,
	NEXT_OF_KIN_LAST_NAME LAST_NAME,
	NEXT_OF_KIN_GENDER GENDER,
	NEXT_OF_KIN_ADDRESS1 ADDRESS_LINE,
	NEXT_OF_KIN_ADDRESS2 ADDRESS_LINE,
	NEXT_OF_KIN_CITY CITY,
	NEXT_OF_KIN_STATE STATE,
	NEXT_OF_KIN_POST_CODE POST_CODE,
	NEXT_OF_KIN_COUNTRY COUNTRY,
	NEXT_OF_KIN_PHONE_NO PHONE_NO,
	NEXT_OF_KIN_MOBILE_NO MOBILE_NO,
	NEXT_OF_KIN_EMAIL EMAIL,
	NEXT_OF_KIN_RELATIONSHIP RELATIONSHIP,
PRIMARY KEY (PERSON_ID));


CREATE TABLE TRAINING_SKILL (
	PERSON_ID PERSON NOT NULL ,
	TRAINING_CODE CODE NOT NULL,
	TRAINING_DATE TRAINING_DATE NOT NULL,
	TRAINING_BY PERSON,
	TRAINING_LOCATION LOCN_ID,
	TRAINING_AUTHORITY MDR_DESCRIPTION,
	TRAINING_PASS TRAINING_PASS,
	TRAINING_RESULT TRAINING_RESULT,
	TRAINING_CERT_PRINTED LABEL_DATE,
PRIMARY KEY (PERSON_ID, TRAINING_CODE, TRAINING_DATE));

CREATE TABLE TRAINING_SKILL_CODES (
	CODE CODE NOT NULL ,
	SKILL_TYPE CODE_TWO,
	DESCRIPTION MDR_DESCRIPTION,
PRIMARY KEY (CODE));

ALTER TABLE IMAGES 
ADD	IMAGE_ID PERSON NOT NULL ;
ALTER TABLE IMAGES 
ADD	IMAGE_BLOB IMAGE;
ALTER TABLE IMAGES 
ADD	IMAGE_TYPE CODE_TWO;
ALTER TABLE IMAGES 
ADD	IMAGE_FORMAT IMAGE_FORMAT;
ALTER TABLE IMAGES 
ADD	IMAGE_SOURCE IMAGE_SOURCE;
ALTER TABLE IMAGES 
ADD	IMAGE_DATE IMAGE_DATE;
ALTER TABLE IMAGES 
ADD	CREATED_BY MDR_USER_ID;

