ALTER PROCEDURE ADD_PROD_COND_STATUS (
    SSN_ID VARCHAR (20),
    CODE VARCHAR (1),
    DESCRIPTION VARCHAR (50),
    ORIGINAL VARCHAR (1))
RETURNS (
    ADD_PROD CHAR (1))
AS




  DECLARE VARIABLE REC_EXIST INTEGER;
  DECLARE VARIABLE MASTER_REC_EXIST INTEGER;
BEGIN
  REC_EXIST = 0;
  MASTER_REC_EXIST = 0;
  ADD_PROD = 'F';

  /* Check if master record exists */
  SELECT 1
  FROM PRODUCT_CONDITION
  WHERE CODE = :CODE
  AND DESCRIPTION = :DESCRIPTION
  INTO :MASTER_REC_EXIST;

  /* if master record not exists then insert */
  IF (MASTER_REC_EXIST = 0) THEN
  BEGIN
    INSERT INTO PRODUCT_CONDITION
         ( CODE, DESCRIPTION)
    VALUES (:CODE, :DESCRIPTION);
  END
  /* Check if record exists */
  SELECT 1
  FROM PRODUCT_COND_STATUS
  WHERE SSN_ID = :SSN_ID
  AND CODE = :CODE
  AND DESCRIPTION = :DESCRIPTION
  AND ORIGINAL_TEST = :ORIGINAL
  INTO :REC_EXIST;

  /* if record not exists then insert */
  IF (REC_EXIST = 0) THEN
  BEGIN
    ADD_PROD = 'T';

    INSERT INTO PRODUCT_COND_STATUS
         (SSN_ID, CODE, DESCRIPTION, ORIGINAL_TEST)
    VALUES (:SSN_ID, :CODE, :DESCRIPTION, :ORIGINAL);
  END
END
^

