ALTER PROCEDURE DELETE_PROD_COND_STATUS (
    SSN_ID VARCHAR (20),
    CODE VARCHAR (1),
    ORIGINAL VARCHAR (1))
AS


BEGIN
  DELETE FROM PRODUCT_COND_STATUS
  WHERE SSN_ID = :SSN_ID
  AND   CODE = :CODE
  AND   ORIGINAL_TEST = :ORIGINAL;
END
^

