COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER PROCEDURE PC_LABEL_PRODUCT (REFERENCE REFERENCE)
RETURNS (RES INTEGER)
AS 

    
  DECLARE VARIABLE SFILEPATH VARCHAR(70);
  DECLARE VARIABLE SFILEPATH2 VARCHAR(70);
  DECLARE VARIABLE SPRINTERNAME DEVICE_ID;
  DECLARE VARIABLE SREF REFERENCE;  
  DECLARE VARIABLE SLABEL VARCHAR(256);
  
  DECLARE VARIABLE ICURQTY INTEGER;
  DECLARE VARIABLE SPRODUCTID PRODUCT;    
  DECLARE VARIABLE SDESC SHORT_DESC;  
  DECLARE VARIABLE TLABELDATE TIMESTAMP;  
  DECLARE VARIABLE WK_DATE VARCHAR(20);  
  DECLARE VARIABLE WK_TIME VARCHAR(10);  
     
BEGIN 
  
  /* Get the printer dir */
/*SPRINTERNAME = SUBSTR(:REFERENCE,1,2);
  SREF = SUBSTR(:REFERENCE,3,STRLEN(:REFERENCE)); */
  SPRINTERNAME = SUBSTRING(:REFERENCE FROM 1 FOR 2);
  SREF = SUBSTRING(:REFERENCE FROM 3);
  
  /* Need the directory for this label set */
  SELECT WORKING_DIRECTORY FROM SYS_EQUIP 
  WHERE DEVICE_ID = :SPRINTERNAME
  INTO :SFILEPATH;
  
  SFILEPATH2 = SFILEPATH || 'Product.txt';
       
  /* Get Product data */
  SELECT 
         ISSN.CURRENT_QTY,
         ISSN.PROD_ID,
         PROD_PROFILE.SHORT_DESC,
         SSN.LABEL_DATE
  FROM (ISSN
         LEFT OUTER JOIN PROD_PROFILE
                      ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID)
         INNER JOIN SSN
                 ON ISSN.ORIGINAL_SSN = SSN.SSN_ID
  WHERE ISSN.SSN_ID = :SREF  
  AND (ISSN.WH_ID < 'X ' OR ISSN.WH_ID > 'X~')
  INTO  :ICURQTY, :SPRODUCTID, :SDESC, :TLABELDATE;        
  
  
/*WK_DATE = EXTRACT(DAY FROM TLABELDATE) || '/' || EXTRACT(MONTH FROM TLABELDATE) || '/' || SUBSTR(CAST(EXTRACT(YEAR FROM TLABELDATE) AS CHAR(4)) , 3,4); */
  WK_DATE = EXTRACT(DAY FROM TLABELDATE) || '/' || EXTRACT(MONTH FROM TLABELDATE) || '/' || SUBSTRING(CAST(EXTRACT(YEAR FROM TLABELDATE) AS CHAR(4)) FROM 3 FOR 2);
  WK_TIME = EXTRACT(HOUR FROM TLABELDATE) || ':' || EXTRACT(MINUTE FROM TLABELDATE) ;
  WK_DATE = WK_DATE || ' ' || WK_TIME;
/*  SLABEL = DQUOTEDSTR(:SREF) || ',' || 
      DQUOTEDSTR(:ICURQTY) || ',' || 
      DQUOTEDSTR(:SPRODUCTID) || ',' || 
      DQUOTEDSTR(:SDESC) || ',' || 
      DQUOTEDSTR( WK_DATE) || ',' ||                 
      DQUOTEDSTR(:SPRINTERNAME); */
  SLABEL = '"' || :SREF || '","' || 
      :ICURQTY || '","' || 
      :SPRODUCTID || '","' || 
      :SDESC || '","' || 
      :WK_DATE || '","' ||                 
      :SPRINTERNAME || '"';
  
  RES = FILE_WRITELN(:SFILEPATH2, :SLABEL);
  IF (RES <> 0) THEN
  BEGIN
     SFILEPATH2 = SFILEPATH || 'Product.2xt';
     RES = FILE_WRITELN(:SFILEPATH2, :SLABEL);
  END   
  
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
