COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
/*
CREATE PROCEDURE ADD_PRODUCT_LABEL ( WK_LABEL_PRINTER CHAR(2),
 WK_PROD_ID VARCHAR(30),
 WK_PICK_LABEL_NO VARCHAR(10),
 WK_ISSN VARCHAR(20),
 WK_COPIES INTEGER)
RETURNS ( WK_LABEL_DATA VARCHAR(32000))
AS 
BEGIN EXIT; END ^
*/

CREATE OR ALTER  PROCEDURE ADD_PRODUCT_LABEL ( WK_LABEL_PRINTER CHAR(2),
 WK_PROD_ID VARCHAR(30),
 WK_PICK_LABEL_NO VARCHAR(10),
 WK_ISSN VARCHAR(20),
 WK_COPIES INTEGER)
RETURNS (WK_LABEL_DATA VARCHAR(32000))
AS 
DECLARE VARIABLE WK_DEFAULT_SSN_STATUS CHAR(2);
DECLARE VARIABLE WK_DEFAULT_PROD_STATUS CHAR(2);
DECLARE VARIABLE WK_LABEL_TYPE CHAR(1);
DECLARE VARIABLE WK_LABEL_USE_EXTERNAL CHAR(1);
DECLARE VARIABLE WK_LABEL_FIELD_WRAPPER CHAR(1);
DECLARE VARIABLE WK_BUFFER VARCHAR(40);
DECLARE VARIABLE WK_LABEL_PART VARCHAR(32000);
DECLARE VARIABLE WK_LABEL_PREFIX VARCHAR(32000);
DECLARE VARIABLE WK_WHERE VARCHAR(100);

DECLARE VARIABLE WK_PROD_PROD VARCHAR(30);
DECLARE VARIABLE WK_PROD_PICK_LABEL VARCHAR(10);
DECLARE VARIABLE WK_RESULT INTEGER; 
DECLARE VARIABLE WK_ERROR_TEXT VARCHAR(1024);
BEGIN 

   IF (WK_PROD_ID IS NULL) THEN
   BEGIN
      WK_PROD_PROD = '';
   END
   ELSE
   BEGIN
      WK_PROD_PROD = WK_PROD_ID;
   END
   IF (WK_PICK_LABEL_NO IS NULL) THEN
   BEGIN
      WK_PROD_PICK_LABEL = '';
   END
   ELSE
   BEGIN
      WK_PROD_PICK_LABEL = WK_PICK_LABEL_NO ;
   END
   
   SELECT NEW_SSN_STATUS, 
          NEW_PROD_STATUS, 
          GENERATE_LABEL_TEXT, 
          EXTERNAL_SCRIPT_4_LABEL,
          LABEL_FIELD_WRAPPER 
   FROM CONTROL
   INTO :WK_DEFAULT_SSN_STATUS, 
        :WK_DEFAULT_PROD_STATUS, 
        :WK_LABEL_TYPE, 
        :WK_LABEL_USE_EXTERNAL,
        :WK_LABEL_FIELD_WRAPPER;
   IF (WK_LABEL_TYPE IS NULL) THEN
   BEGIN
      WK_LABEL_TYPE = 'F';
   END
   IF (WK_LABEL_TYPE = '') THEN
   BEGIN
      WK_LABEL_TYPE = 'F';
   END
   IF (WK_LABEL_USE_EXTERNAL IS NULL) THEN
   BEGIN
      WK_LABEL_USE_EXTERNAL = 'F';
   END
   IF (WK_LABEL_USE_EXTERNAL = '') THEN
   BEGIN
      WK_LABEL_USE_EXTERNAL = 'F';
   END
   IF (WK_LABEL_FIELD_WRAPPER IS NULL) THEN
   BEGIN
      WK_LABEL_FIELD_WRAPPER = '%';
   END
   IF (WK_LABEL_PRINTER IS NULL) THEN
   BEGIN
      WK_LABEL_PRINTER = 'PA';
   END
   IF (WK_LABEL_PREFIX IS NULL) THEN
   BEGIN
      WK_LABEL_PREFIX  = '';
   END
   /* now must print a label */
   WK_RESULT = 0;
   IF (WK_LABEL_USE_EXTERNAL = 'F') THEN
   BEGIN
      IF (WK_LABEL_TYPE = 'F') THEN
      BEGIN
         /* use pc_label for label creation */
         WK_RESULT = 0;
         WK_LABEL_DATA = '';
         WK_LABEL_PART = '';
         WK_LABEL_DATA = WK_LABEL_DATA || :WK_LABEL_PREFIX;
         WK_WHERE = " WHERE PROD_ID='" || WK_PROD_PROD  || "'";
         EXECUTE PROCEDURE GET_TABLE_DATA ('PROD_PROFILE', WK_LABEL_FIELD_WRAPPER, '|', :WK_WHERE)
         RETURNING_VALUES :WK_LABEL_PART;
         IF (WK_LABEL_PART IS NULL) THEN
         BEGIN
            WK_LABEL_PART = '';
         END
         WK_LABEL_DATA = WK_LABEL_DATA || :WK_LABEL_PART;
         WK_WHERE = " WHERE PICK_LABEL_NO='" || WK_PROD_PICK_LABEL   || "'";
         EXECUTE PROCEDURE GET_TABLE_DATA ('PICK_ITEM', WK_LABEL_FIELD_WRAPPER, '|', :WK_WHERE)
         RETURNING_VALUES :WK_LABEL_PART;
         IF (WK_LABEL_PART IS NULL) THEN
         BEGIN
            WK_LABEL_PART = '';
         END
         WK_LABEL_DATA = WK_LABEL_DATA || :WK_LABEL_PART;
         WK_WHERE = " WHERE PROD_ID='" || WK_PROD_PROD   || "'";
         EXECUTE PROCEDURE GET_TABLE_DATA ('PROD_EAN', WK_LABEL_FIELD_WRAPPER, '|', :WK_WHERE)
         RETURNING_VALUES :WK_LABEL_PART;
         IF (WK_LABEL_PART IS NULL) THEN
         BEGIN
            WK_LABEL_PART = '';
         END
         WK_LABEL_DATA = WK_LABEL_DATA || :WK_LABEL_PART;
/*
         EXECUTE  PROCEDURE PC_LABEL (:WK_LABEL_PRINTER ,
                  'PRODUCT' , 
                  :WK_COPIES ,
                  NULL ,
                  :WK_LABEL_DATA ,
                  :WK_USER )
         RETURNING_VALUES :WK_RESULT ,
                           :WK_ERROR_TEXT ;
*/
      END
      ELSE
      BEGIN
         /* use bartender for printing */
         IF (WK_ISSN IS NOT NULL) THEN
         BEGIN
            /* use pc_label_product for label creation */
            WK_BUFFER = WK_LABEL_PRINTER  || WK_ISSN;
            /* EXECUTE PROCEDURE PC_LABEL_PRODUCT WK_BUFFER RETURNING_VALUES :WK_RESULT; */
            WK_LABEL_DATA = WK_BUFFER;
         END
         ELSE
         BEGIN
            /* use pc_label_product for label creation */
            WK_BUFFER = WK_LABEL_PRINTER  || WK_PROD_PROD;
            /* EXECUTE PROCEDURE PC_LABEL_ISSN WK_BUFFER RETURNING_VALUES :WK_RESULT; */
            WK_LABEL_DATA = WK_BUFFER;
         END
      END
   END
   ELSE
   BEGIN
      IF (WK_LABEL_TYPE = 'F') THEN
      BEGIN
         /* use error text to pass back data for label creation */
      END
      ELSE
      BEGIN
         WK_BUFFER = WK_LABEL_PRINTER  || WK_PROD_ID;
         /* use bartender for printing */
         WK_LABEL_DATA = WK_BUFFER;
      END
   END
   SUSPEND;
END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
