SET TERM ^;

DROP TRIGGER ADD_SSN_FROM_LEGACY^
COMMIT^

CREATE TRIGGER ADD_SSN_FROM_LEGACY FOR LEGACY
ACTIVE BEFORE INSERT POSITION 0 
AS
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_LEGACY_ID VARCHAR(20); 
DECLARE VARIABLE WK_LEGACY_DESC VARCHAR(200);
DECLARE VARIABLE WK_TYPE VARCHAR(40); 
DECLARE VARIABLE WK_GENERIC VARCHAR(40); 
DECLARE VARIABLE WK_BRAND VARCHAR(40); 
DECLARE VARIABLE WK_MODEL VARCHAR(40); 
DECLARE VARIABLE WK_SERIAL VARCHAR(30); 
DECLARE VARIABLE WK_OTHER1 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER2 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER3 VARCHAR(40); 
DECLARE VARIABLE WK_OTHER4 VARCHAR(40); 
DECLARE VARIABLE WK_OTHER_1_COND INTEGER; 
DECLARE VARIABLE WK_OTHER_2_COND INTEGER; 
DECLARE VARIABLE WK_OTHER_3_COND INTEGER; 
DECLARE VARIABLE WK_OTHER_4_COND INTEGER; 
DECLARE VARIABLE WK_OTHER6 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER7 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER8 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER9 VARCHAR(50); 
DECLARE VARIABLE WK_OTHER10 VARCHAR(50); 
DECLARE VARIABLE WK_STATUS CHAR(2); 
DECLARE VARIABLE WK_P_DATE TIMESTAMP; 
DECLARE VARIABLE WK_P_PRICE FLOAT; 
DECLARE VARIABLE WK_C_DATE TIMESTAMP;
DECLARE VARIABLE WK_A_COST  FLOAT;
DECLARE VARIABLE WK_CC  VARCHAR(40);
DECLARE VARIABLE WK_WH_ID  CHAR(2);
DECLARE VARIABLE WK_GRN  INTEGER;
DECLARE VARIABLE WK_LOAD  VARCHAR(10);
BEGIN
   WK_LEGACY_ID  = NEW.LEGACY_ID;
   WK_LEGACY_DESC = NEW.LEGACY_DESCRIPTION || ',';
   WK_TYPE = NEW.SSN_TYPE;
   WK_GENERIC = NEW.GENERIC;
   WK_BRAND = NEW.BRAND;
   WK_MODEL = NEW.MODEL;
   WK_SERIAL = NEW.SERIAL_NUMBER;
   WK_OTHER1 = NEW.OTHER1;
   WK_OTHER2 = NEW.OTHER2;
   WK_OTHER6 = NEW.OTHER6;
   WK_OTHER7 = NEW.OTHER7;
   WK_OTHER8 = NEW.OTHER8;
   WK_OTHER9 = NEW.OTHER9;
   WK_OTHER10 = NEW.OTHER10;
   WK_STATUS = NEW.STATUS;
   WK_P_DATE = NEW.PURCHASE_DATE;
   WK_P_PRICE = NEW.PURCHASE_PRICE;
   WK_C_DATE = NEW.COMMISSIONED_DATE;
   WK_A_COST = NEW.ACQUISITION_COST;
   WK_CC = NEW.COST_CENTER;
   WK_WH_ID = NEW.WH_ID;
   WK_GRN = NEW.GRN;
   WK_LOAD = NEW.LOAD_NO;


   /* Check SSN */
   WK_FOUND = 0;
   SELECT 1 FROM SSN 
      WHERE SSN_ID = :WK_LEGACY_ID
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no ssn so insert it */

      /* calculate other 1 to 4 */
    
      WK_OTHER_1_COND = POS(WK_LEGACY_DESC,',AS NEW CONDITION,',0,1);
      WK_OTHER_2_COND = POS(WK_LEGACY_DESC,',TESTED - OK,',0,1);
      WK_OTHER_3_COND = POS(WK_LEGACY_DESC,',COMPLETE,',0,1);
      WK_OTHER_4_COND = POS(WK_LEGACY_DESC,',NO SERVICE,',0,1);
      IF (WK_OTHER_1_COND = -1) THEN
      BEGIN
         WK_OTHER1 = 'NOT NEW CONDITION';
      END
      ELSE
      BEGIN
         WK_OTHER1 = 'AS NEW CONDITION';
      END
      IF (WK_OTHER_2_COND = -1) THEN
      BEGIN
         WK_OTHER2 = 'TESTED - FAULTY';
      END
      ELSE
      BEGIN
         WK_OTHER2 = 'TESTED - OK';
      END
      IF (WK_OTHER_3_COND = -1) THEN
      BEGIN
         WK_OTHER3 = 'INCOMPLETE';
      END
      ELSE
      BEGIN
         WK_OTHER3 = 'COMPLETE';
      END
      IF (WK_OTHER_4_COND = -1) THEN
      BEGIN
         WK_OTHER4 = 'NO SERVICE';
      END
      ELSE
      BEGIN
         WK_OTHER4 = 'SERVICE PROVIDED';
      END

      
      INSERT INTO SSN (SSN_ID, WH_ID, LOCN_ID, GRN, STATUS_SSN, 
             ORIGINAL_QTY, CURRENT_QTY, PO_ORDER, 
             PO_RECEIVE_DATE, SSN_TYPE, GENERIC, BRAND, MODEL, 
             SERIAL_NUMBER, OTHER6, OTHER7, OTHER8, OTHER9, OTHER10,
             STORAGE_UOM, OTHER1, OTHER2, OTHER3, OTHER4 )
      VALUES (:WK_LEGACY_ID, :WK_WH_ID, 'INTRANST', :WK_GRN, 'TS', 1, 1,
              :WK_LOAD, 'NOW', :WK_TYPE, :WK_GENERIC, :WK_BRAND, 
              :WK_MODEL, :WK_SERIAL, :WK_OTHER6, :WK_OTHER7, :WK_OTHER8,
              :WK_OTHER9, :WK_OTHER10, 'EA' , :WK_OTHER1, :WK_OTHER2, :WK_OTHER3, :WK_OTHER4);
      NEW.STATUS = 'T'; 
   END
   /* Check issn */
   WK_FOUND = 0;
   SELECT 1 FROM ISSN
      WHERE SSN_ID = :WK_LEGACY_ID
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no issn so insert it */
      INSERT INTO ISSN (SSN_ID, ORIGINAL_SSN, WH_ID, LOCN_ID, CURRENT_QTY,ISSN_STATUS)
      VALUES (:WK_LEGACY_ID, :WK_LEGACY_ID, :WK_WH_ID, 'INTRANST', 1, 'TS'); 
   END
   ELSE
   BEGIN
      UPDATE ISSN SET 
        ORIGINAL_SSN = :WK_LEGACY_ID 
      WHERE SSN_ID = :WK_LEGACY_ID;
   END
END ^
 
