COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE OR ALTER TRIGGER TRANSACTION_ARCHIVE_RECORD_ID FOR TRANSACTIONS_ARCHIVE 
ACTIVE BEFORE INSERT POSITION 0 
AS
BEGIN
  IF (NEW.RECORD_ID IS NULL) THEN
      NEW.RECORD_ID = GEN_ID(TRANSACTION_ID, 1);    
  IF (NEW.RECORD_ID = 0) THEN
      NEW.RECORD_ID = GEN_ID(TRANSACTION_ID, 1);    
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
