SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */

CREATE PROCEDURE RPT_CANCEL_ORDER_DATA 
(
  THISPICK_LABEL_NO VARCHAR(50)
)
RETURNS
(
  FROM_LOCN_ID VARCHAR(50),
  QTYSUM INTEGER,
  FROM_WH_ID VARCHAR(50)
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE RPT_CANCEL_ORDER_DATA 
(
  THISPICK_LABEL_NO VARCHAR(50)
)
RETURNS
(
  FROM_LOCN_ID VARCHAR(50),
  QTYSUM INTEGER,
  FROM_WH_ID VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
  SELECT  DISTINCT(FROM_LOCN_ID), SUM(QTY_PICKED) ,FROM_WH_ID 
  FROM PICK_ITEM_DETAIL
  WHERE  PICK_ITEM_DETAIL.PICK_LABEL_NO = :THISPICK_LABEL_NO AND  
         QTY_PICKED > 0
  GROUP BY FROM_WH_ID, FROM_LOCN_ID

  INTO
:FROM_LOCN_ID,
:QTYSUM,
:FROM_WH_ID
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

