COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */
/*
CREATE PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  THISCOMPANY_ID VARCHAR(20),
  CURRENT_QTY INTEGER
)
AS
BEGIN EXIT; END ^

CREATE PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  WH_ID1 VARCHAR(30),
  LOCN_ID1 VARCHAR(30),
  LOC_QTY_1 INTEGER,
  WH_ID2 VARCHAR(30),
  LOCN_ID2 VARCHAR(30),
  LOC_QTY_2 INTEGER,
  PROD_ID VARCHAR(30),
  DESCRIPTION VARCHAR(50)
)
AS
BEGIN EXIT; END ^

CREATE PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  QTY INTEGER,
  COMPANY_ID VARCHAR(30)
)
AS
BEGIN EXIT; END ^
*/

ALTER PROCEDURE RPT_BUSINESS_MONTHLY_1_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  THISCOMPANY_ID VARCHAR(20),
  CURRENT_QTY INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
SELECT ISSN.PROD_ID, PROD_PROFILE.SHORT_DESC,PROD_PROFILE.COMPANY_ID , SUM(ISSN.ORIGINAL_QTY)
FROM GRN
JOIN SSN ON SSN.GRN = GRN.GRN
JOIN ISSN ON ISSN.SSN_ID = SSN.SSN_ID
JOIN PROD_PROFILE ON PROD_PROFILE.PROD_ID = ISSN.PROD_ID
WHERE (GRN.GRN_DATE BETWEEN ZEROTIME(:THISSTART) AND MAXTIME(:THISEND)) AND
   PROD_PROFILE.COMPANY_ID = :THISCOMPANY 
GROUP BY PROD_PROFILE.COMPANY_ID, ISSN.PROD_ID, PROD_PROFILE.SHORT_DESC

  INTO
          :PROD_ID,
          :SHORT_DESC,
          :THISCOMPANY_ID,
          :CURRENT_QTY
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */



ALTER PROCEDURE RPT_BUSINESS_MONTHLY_2_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  WH_ID1 VARCHAR(30),
  LOCN_ID1 VARCHAR(30),
  LOC_QTY_1 INTEGER,
  WH_ID2 VARCHAR(30),
  LOCN_ID2 VARCHAR(30),
  LOC_QTY_2 INTEGER,
  PROD_ID VARCHAR(30),
  DESCRIPTION VARCHAR(50)
)
AS
BEGIN
  /* PROCEDURE BODY */
  WH_ID1 = '';
/*
  FOR
    SELECT SSN_HIST.WH_ID AS WH_ID1,SSN_HIST.LOCN_ID AS LOCN_ID1,
       SSN_HIST.WH_ID AS WH_ID2,SSN_HIST.LOCN_ID AS LOCN_ID2,ISSN.PROD_ID,
       SSN_HIST.SSN_ID AS DESCRIPTION, ISSN.CURRENT_QTY AS QTY
    FROM SSN_HIST
    LEFT OUTER JOIN  SSN ON SSN_HIST.SSN_ID = SSN.SSN_ID
    LEFT OUTER JOIN  ISSN ON SSN_HIST.SSN_ID = ISSN.SSN_ID
    WHERE TRN_TYPE = 'TRLI' AND SSN.COMPANY_ID = :THISCOMPANY
    AND  (TRN_DATE >= :THISSTART AND TRN_DATE <= :THISEND )

  INTO
:WH_ID1,
:LOCN_ID1,
:WH_ID2,
:LOCN_ID2,
:PROD_ID,
:DESCRIPTION,
:QTY
 
  DO
  BEGIN
  SUSPEND;
  END
*/
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */



ALTER PROCEDURE RPT_BUSINESS_MONTHLY_3_DATA 
(
  THISCOMPANY VARCHAR(20),
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  PROD_ID VARCHAR(30),
  SHORT_DESC VARCHAR(50),
  QTY INTEGER,
  COMPANY_ID VARCHAR(30)
)
AS
BEGIN
  /* PROCEDURE BODY */
  FOR
 SELECT PROD_PROFILE.PROD_ID, PROD_PROFILE.SHORT_DESC, SUM(ISSN.PREV_QTY), PROD_PROFILE.COMPANY_ID 
FROM ISSN
   INNER JOIN PROD_PROFILE ON ISSN.PROD_ID = PROD_PROFILE.PROD_ID
   WHERE PROD_PROFILE.COMPANY_ID = :THISCOMPANY
   AND (ISSN.DESPATCHED_DATE BETWEEN ZEROTIME(:THISSTART) AND MAXTIME(:THISEND))
   GROUP BY PROD_PROFILE.COMPANY_ID, PROD_PROFILE.PROD_ID,PROD_PROFILE.SHORT_DESC
  INTO
:PROD_ID,
:SHORT_DESC,
:QTY,
:COMPANY_ID
  DO
  BEGIN
  SUSPEND;
  END
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
