/*    
DECLARE EXTERNAL FUNCTION BLOB_BYTECOUNT
	BLOB
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'fn_blob_bytecount' MODULE_NAME 'udflib';

DECLARE EXTERNAL FUNCTION BLOB_LINECOUNT
	BLOB
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'fn_blob_linecount' MODULE_NAME 'udflib';
  
DROP TRIGGER RUN_TRANSACTION_NINB;

DROP EXTERNAL FUNCTION BLOB_SUBSTR;

DECLARE EXTERNAL FUNCTION BLOB_SUBSTR 
	BLOB, INTEGER, INTEGER 
	RETURNS CSTRING(32767) FREE_IT
	ENTRY_POINT 'fn_blob_substr' MODULE_NAME 'udflib';

*/
DROP EXTERNAL FUNCTION CHECK_LOGIN;

DECLARE EXTERNAL FUNCTION CHECK_LOGIN
	INTEGER, CSTRING(40)
	RETURNS INTEGER BY VALUE
	ENTRY_POINT 'fn_checkcnt' MODULE_NAME 'udflib';

