

CREATE TRIGGER INSERT_TRAINING_SKILL_CODES FOR TRAINING_SKILL_CODES
ACTIVE AFTER  INSERT POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
BEGIN
   WK_CODE = NEW.CODE;
   SELECT FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'newskillcode.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_CODE) ;
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'newskillcode.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

CREATE TRIGGER UPDATE_TRAINING_SKILL_CODES FOR TRAINING_SKILL_CODES
ACTIVE AFTER  UPDATE POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
BEGIN
   WK_CODE = NEW.CODE;
   SELECT FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'updskillcode.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_CODE) ;
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'updskillcode.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

CREATE TRIGGER DELETE_TRAINING_SKILL_CODES FOR TRAINING_SKILL_CODES
ACTIVE AFTER  DELETE POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
BEGIN
   WK_CODE = OLD.CODE;
   SELECT FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'delskillcode.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_CODE) ;
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'delskillcode.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

