DROP   TRIGGER UPDATE_ISSN_LOCATION^
COMMIT^

CREATE TRIGGER UPDATE_ISSN_LOCATION FOR ISSN 
ACTIVE BEFORE UPDATE POSITION 0 
AS
                                                       
  DECLARE VARIABLE WK_FROM_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_TO_STATUS VARCHAR(2);
  DECLARE VARIABLE WK_NEW_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_NEW_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_OLD_WH_ID VARCHAR(2);
  DECLARE VARIABLE WK_OLD_LOCN_ID VARCHAR(10);
  DECLARE VARIABLE WK_IS_OK CHAR(1);
  DECLARE VARIABLE WK_SSN VARCHAR(20);
  DECLARE VARIABLE WK_SSN_QTY INTEGER;
     
BEGIN
   /* Update ISSN table */   
         
   WK_NEW_WH_ID = NEW.WH_ID;
   WK_NEW_LOCN_ID = NEW.LOCN_ID;
   WK_OLD_WH_ID = OLD.WH_ID;
   WK_OLD_LOCN_ID = OLD.LOCN_ID;
   IF ( (WK_NEW_WH_ID <> WK_OLD_WH_ID) OR
        (WK_NEW_LOCN_ID <> WK_OLD_LOCN_ID)) THEN
   BEGIN
      /* location changed */
      WK_FROM_STATUS = NEW.ISSN_STATUS;
      WK_SSN = NEW.SSN_ID;
      WK_SSN_QTY = NEW.CURRENT_QTY;
      WK_TO_STATUS = 'ST';
      SELECT MOVE_STAT FROM LOCATION 
         WHERE WH_ID = :WK_NEW_WH_ID AND LOCN_ID = :WK_NEW_LOCN_ID
         INTO :WK_TO_STATUS;
      IF (WK_FROM_STATUS <> WK_TO_STATUS) THEN
      BEGIN
         /* a change in status possible - so check sys_moves */
         WK_IS_OK = 'N';
         SELECT UPDATE_FLAG FROM SYS_MOVES
            WHERE FROM_STATUS = :WK_FROM_STATUS AND INTO_STATUS = :WK_TO_STATUS
            INTO :WK_IS_OK;
         IF (WK_IS_OK = 'T') THEN
         BEGIN
            NEW.ISSN_STATUS = WK_TO_STATUS;
            IF (WK_TO_STATUS = 'DS') THEN
            BEGIN
               IF (WK_FROM_STATUS = 'ST') THEN
               BEGIN
                 UPDATE PICK_ITEM 
			SET PICK_LINE_STATUS = 'DS',
			PICKED_QTY = :WK_SSN_QTY,
			DESPATCH_LOCATION = :WK_NEW_LOCN_ID 
                 	WHERE SSN_ID = :WK_SSN
                 	AND PICK_LINE_STATUS IN ('OP','HD');
               END
               IF (WK_FROM_STATUS = 'RS') THEN
               BEGIN
                 UPDATE PICK_ITEM 
			SET PICK_LINE_STATUS = 'DS',
			PICKED_QTY = :WK_SSN_QTY,
			DESPATCH_LOCATION = :WK_NEW_LOCN_ID 
                 	WHERE SSN_ID = :WK_SSN
                 	AND PICK_LINE_STATUS IN ('OP','HD');
               END
            END
         END
      END
   END
END ^
 
