SET TERM ^;
CREATE TRIGGER RUN_TRANSACTION_NITP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 1 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NITP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
 
CREATE TRIGGER RUN_TRANSACTION_NIOB FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 2 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIOB') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIBC FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 3 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIBC') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIMO FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 4 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIMO') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NICC FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 5 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NICC') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NILG FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 6 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NILG') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_PSRF FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 7 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'PSRF') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NISN FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 8 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NISN') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO1 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 9 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO1') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO2 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 10 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO2') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO3 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 11 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO3') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO4 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 12 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO4') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO5 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 13 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO5') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO6 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 14 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO6') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO7 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 15 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO7') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO8 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 16 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO8') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIO9 FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 17 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIO9') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIOA FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 18 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIOA') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIOK FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 19 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIOK') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIPC FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 20 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIPC') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIOL FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 21 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIOL') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIST FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 22
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIST') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NILX FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 23
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NILX') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIGC FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 24
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIGC') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NIXX 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIAP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 25
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIAP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_ADD_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIOP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 26
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIOP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_ADD_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NICP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 27
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NICP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_ADD_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_AULO FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 28
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'AULO') THEN
		BEGIN
			EXECUTE PROCEDURE PC_AULO 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.TRN_DATE;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_AUOB FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 29
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'AUOB') THEN
		BEGIN
			EXECUTE PROCEDURE PC_AUOB 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NIID FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 30
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NIID') THEN
		BEGIN
			EXECUTE PROCEDURE PC_AUOB 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.INSTANCE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NXAP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 31
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NXAP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_DELETE_ONE_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NXOP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 32
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NXOP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_DELETE_ONE_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NXCP FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 33
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NXCP') THEN
		BEGIN
			EXECUTE PROCEDURE PC_DELETE_ONE_PROD_COND_STATUS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NILT FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 34
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NILT') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NILT_NILS
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_NILS FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 35
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'NILS') THEN
		BEGIN
			EXECUTE PROCEDURE PC_NILT_NILS
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_TRLO FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 36
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'TRLO') THEN
		BEGIN
			EXECUTE PROCEDURE PC_TRLO_TRLI
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_TRLI FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 37
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'TRLI') THEN
		BEGIN
			EXECUTE PROCEDURE PC_TRLO_TRLI
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_TROL FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 38
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'TROL') THEN
		BEGIN
			EXECUTE PROCEDURE PC_TROL_TRIL
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_TRIL FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 39
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'TRIL') THEN
		BEGIN
			EXECUTE PROCEDURE PC_TROL_TRIL
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_TRSS FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 40 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'TRSS') THEN
		BEGIN
			EXECUTE PROCEDURE PC_TRSS 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
CREATE TRIGGER RUN_TRANSACTION_WMAR FOR TRANSACTIONS  
ACTIVE AFTER  INSERT POSITION 41 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
	WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);	
	IF (WK_AUTORUN = 1) THEN
	BEGIN
		IF (NEW.TRN_TYPE = 'WMAR') THEN
		BEGIN
			EXECUTE PROCEDURE PC_WMAR 
				NEW.RECORD_ID ,
				NEW.WH_ID,
				NEW.LOCN_ID,
				NEW.OBJECT,
				NEW.TRN_TYPE,
				NEW.TRN_CODE,
				NEW.TRN_DATE,
				NEW.REFERENCE,
				NEW.QTY,
				NEW.PERSON_ID,
				NEW.DEVICE_ID,
				NEW.SUB_LOCN_ID;
			EXECUTE PROCEDURE TRAN_ARCHIVE;
		END
	END
END ^
