COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

 


CREATE OR ALTER TRIGGER RUN_TRANSACTION_NIRM FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 55 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_OBJECT OBJECT;
DECLARE VARIABLE WK_SSN_TYPE VARCHAR(40);
DECLARE VARIABLE WK_GENERIC VARCHAR(40);
DECLARE VARIABLE WK_BRAND VARCHAR(40);
DECLARE VARIABLE WK_MODEL VARCHAR(40);
DECLARE VARIABLE WK_PROD_ID PRODUCT;
DECLARE VARIABLE WK_SUPPLIER_ID VARCHAR(50);
DECLARE VARIABLE WK_OTHER6 VARCHAR(50);
DECLARE VARIABLE WK_OTHER7 VARCHAR(50);
DECLARE VARIABLE WK_OTHER8 VARCHAR(50);
DECLARE VARIABLE WK_OTHER9 VARCHAR(50);
DECLARE VARIABLE WK_OTHER10 VARCHAR(50);
DECLARE VARIABLE WK_DESCRIPTION VARCHAR(50);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_PRINTER DEVICE_ID;
DECLARE VARIABLE WK_DIRECTORY VARCHAR(75);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(250);
DECLARE VARIABLE WK_RECORD_ID INTEGER;
DECLARE VARIABLE WK_USER USER_ID;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NIRM') THEN
  BEGIN
   WK_RECORD_ID = NEW.RECORD_ID;
   WK_USER = NEW.PERSON_ID;
/* IF (SUBSTR(NEW.REFERENCE,1,5) = 'GROUP') THEN */
   IF (SUBSTRING(NEW.REFERENCE FROM 1 FOR 5) = 'GROUP') THEN
   BEGIN
    WK_FOUND = 0;
    WK_OBJECT = NEW.OBJECT;
    SELECT SSN.SSN_TYPE, 
       SSN.GENERIC, 
       SSN.BRAND, 
       SSN.MODEL, 
       SSN.PROD_ID, 
       SSN.SUPPLIER_ID, 
       SSN.OTHER6, 
       SSN.OTHER7, 
       SSN.OTHER8, 
       SSN.OTHER9, 
       SSN.OTHER10 
    FROM ISSN 
    JOIN SSN ON ISSN.ORIGINAL_SSN = SSN.SSN_ID 
    WHERE ISSN.SSN_ID = :WK_OBJECT
    INTO :WK_SSN_TYPE, 
         :WK_GENERIC, 
         :WK_BRAND, 
         :WK_MODEL, 
         :WK_PROD_ID, 
         :WK_SUPPLIER_ID, 
         :WK_OTHER6, 
         :WK_OTHER7, 
         :WK_OTHER8, 
         :WK_OTHER9, 
         :WK_OTHER10; 
    SELECT 1 FROM GROUP_COPY WHERE CODE = :WK_OBJECT INTO :WK_FOUND;
    IF (WK_FOUND = 0) THEN
    BEGIN
       INSERT INTO GROUP_COPY(CODE, 
          SSN_TYPE, 
          GENERIC, 
          BRAND, 
          MODEL, 
          PROD_ID, 
          SUPPLIER_ID, 
          OTHER6, 
          OTHER7, 
          OTHER8, 
          OTHER9, 
          OTHER10, 
          DESCRIPTION) VALUES (:WK_OBJECT,
         :WK_SSN_TYPE, 
         :WK_GENERIC, 
         :WK_BRAND, 
         :WK_MODEL, 
         :WK_PROD_ID, 
         :WK_SUPPLIER_ID, 
         :WK_OTHER6, 
         :WK_OTHER7, 
         :WK_OTHER8, 
         :WK_OTHER9, 
         :WK_OTHER10, 
         :WK_OBJECT); 
    END
    ELSE
    BEGIN
       UPDATE GROUP_COPY SET SSN_TYPE = :WK_SSN_TYPE, 
          GENERIC = :WK_GENERIC, 
          BRAND = :WK_BRAND, 
          MODEL = :WK_MODEL, 
          PROD_ID = :WK_PROD_ID, 
          SUPPLIER_ID = :WK_SUPPLIER_ID, 
          OTHER6 = :WK_OTHER6, 
          OTHER7 = :WK_OTHER7, 
          OTHER8 = :WK_OTHER8, 
          OTHER9 = :WK_OTHER9, 
          OTHER10 = :WK_OTHER10 
       WHERE CODE = :WK_OBJECT;
    END
/* WK_PRINTER = SUBSTR(NEW.REFERENCE,7,8); */
   WK_PRINTER = SUBSTRING(NEW.REFERENCE FROM 7 FOR 2);
    /* need the directory for this label set */
    SELECT WORKING_DIRECTORY FROM SYS_EQUIP 
        WHERE DEVICE_ID = :WK_PRINTER
        INTO :WK_DIRECTORY;
    /* append the file name to the directory*/
    BEGIN
       WK_FILENAME = WK_DIRECTORY || 'DESCRIPTION.txt';
/*     WK_LABEL_LINE = DQUOTEDSTR('/O' || WK_OBJECT) || ',' ||
          DQUOTEDSTR('GROUP CODE') ; */
       WK_LABEL_LINE = '"/O' || WK_OBJECT || '","GROUP CODE"' ;
       WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
       IF (WK_RESULT <> 0) THEN
       BEGIN
          WK_FILENAME = WK_DIRECTORY || 'DESCRIPTION.2xt';
          WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
       END
    END
    EXECUTE PROCEDURE UPDATE_TRAN (:WK_RECORD_ID, 'T', 'Processed successfully'); 
   END
/* EXECUTE PROCEDURE TRAN_ARCHIVE; */
  END
 END
END ^
 

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
