ALTER TABLE SSN_TEST_RESULTS
ADD INSPECT_CATEGORY VARCHAR(1);


ALTER TABLE TEST_QUESTIONS
ADD INSPECT_CATEGORY VARCHAR(1);
ALTER TABLE VALID_RESPONSES
ADD INSPECT_CATEGORY VARCHAR(1);
ALTER TABLE VALID_RESPONSES
ADD INSPECT_DESCRIPTION VARCHAR(25);
ALTER TABLE SSN_TEST_RESULTS
ADD INSPECT_PASS_CRITERIA VARCHAR(6);
ALTER TABLE VALID_RESPONSES
ADD INSPECT_PASS_CRITERIA VARCHAR(6);
ALTER TABLE SSN_TEST_RESULTS
ADD ORIGINAL_TEST FLAGS;
ALTER TABLE SSN_TEST_RESULTS
ADD PROCESSED FLAGS
DEFAULT 'O';
ALTER TABLE SSN_TEST_RESULTS
ADD USER_ID USER_ID;
/* Table: RESUME_TEST */

CREATE TABLE RESUME_TEST (
    SSN_ID SSN_ID,
    DESCRIPTION DESCR);

