
CREATE INDEX GRN_UPDATE_DATE_IDX ON GRN(LAST_UPDATE_DATE);
CREATE INDEX SSN_TEST_UPDATE_DATE_IDX ON SSN_TEST(LAST_UPDATE_DATE);

CREATE INDEX PROD_COND_TRN_DATE_IDX ON PRODUCT_CONDITION(LAST_UPDATE_DATE);
CREATE INDEX PROD_COND_STATUS_UPD_DATE_IDX ON PRODUCT_COND_STATUS(LAST_UPDATE_DATE);
