
CREATE TABLE CARRIER_WAREHOUSE ( RECORD_ID INTEGER NOT NULL,
        CARRIER_ID DESPATCH_CARRIER NOT NULL,
        WH_ID WH_ID  NOT NULL,
        CARRIER_DEPOT_FIELD DESCR,
        CREATE_DATE CREATE_DATE,
        CREATED_BY USER_ID,
        LAST_UPDATE_DATE LAST_UPDATE_DATE,
        LAST_UPDATE_BY   USER_ID,
PRIMARY KEY (RECORD_ID));
  
  
CREATE GENERATOR CARRIER_WAREHOUSE_ID_GEN;
CREATE UNIQUE INDEX CARRIER_WAREHOUSE_IDX ON CARRIER_WAREHOUSE (CARRIER_ID, WH_ID);
ALTER TABLE PICK_ORDER ADD P_POST_CODE_DEPOT_ID CODE;
ALTER TABLE PICK_DESPATCH ADD PICKD_POST_CODE_DEPOT_ID CODE;

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
CREATE TRIGGER ADD_CARRIER_WAREHOUSE FOR CARRIER_WAREHOUSE
ACTIVE BEFORE INSERT POSITION 10 
AS
BEGIN
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(CARRIER_WAREHOUSE_ID_GEN,1);
   END
   NEW.LAST_UPDATE_DATE = 'NOW';
   NEW.CREATE_DATE = 'NOW';
END ^

CREATE TRIGGER UPD_CARRIER_WAREHOUSE FOR CARRIER_WAREHOUSE
ACTIVE BEFORE UPDATE POSITION 10 
AS
BEGIN
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(CARRIER_WAREHOUSE_ID_GEN,1);
   END
   NEW.LAST_UPDATE_DATE = 'NOW';
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
