/*
  use prod_type table for replacement status
  do not pass the status to use - only use the status in the prod_type table
  
*/
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 

CREATE OR ALTER PROCEDURE ADD_PICK_ITEMS_PM (WK_ORDER PICK_ORDER,
WK_PROD1 PRODUCT,
WK_EXTENSION1 VARCHAR(6) CHARACTER SET NONE,
WK_LINE_NO1 VARCHAR(4) CHARACTER SET NONE,
WK_QTY1 QTY,
WK_TRN_DATE TIMESTAMP,
WK_PERSON_ID PERSON,
WK_SALE_PRICE NUMERIC(15, 4))
AS 
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_PICK_LABEL VARCHAR(8);
DECLARE VARIABLE WK_L_PICK_LINE_NO VARCHAR(4);
DECLARE VARIABLE WK_PROD_ID PRODUCT;
DECLARE VARIABLE WK_PROD_TYPE CHAR(2);
DECLARE VARIABLE WK_LINE_STATUS CHAR(2);
DECLARE VARIABLE WK_PROD_SALE_PRICE DECIMAL(9,4);
DECLARE VARIABLE WK_PICK_RETURN_DATE TIMESTAMP;
DECLARE VARIABLE WK_PICK_DUE_DATE TIMESTAMP;
DECLARE VARIABLE WK_ORDER_TYPE CHAR(2);
DECLARE VARIABLE WK_PI_SALE_PRICE DECIMAL(9,4);
DECLARE VARIABLE WK_PI_RETURN_DATE TIMESTAMP;
DECLARE VARIABLE WK_PI_DUE_DATE TIMESTAMP;
DECLARE VARIABLE WK_PI_LINE_TOTAL DECIMAL(9,4);
DECLARE VARIABLE WK_LOG_FILENAME VARCHAR(80) ;
DECLARE VARIABLE WK_LOG_RESULT   INTEGER;
DECLARE VARIABLE WK_PI_LABEL   VARCHAR(10);
DECLARE VARIABLE WK_PI_STATUS  CHAR(2);
DECLARE VARIABLE WK_PI_LINENO  VARCHAR(10);
DECLARE VARIABLE WK_LINE_LEN   INTEGER;
DECLARE VARIABLE WK_DEFAULT_UOM  CHAR(2);
DECLARE VARIABLE WK_DEFAULT_STATUS  CHAR(2);
DECLARE VARIABLE WK_DEFAULT_PROD_STATUS CHAR(2);
DECLARE VARIABLE WK_PROD_EAN_LENGTH   INTEGER;
DECLARE VARIABLE WK_LINE_ADDED CHAR(1);
DECLARE VARIABLE WK_PO_STATUS  CHAR(2);
DECLARE VARIABLE WK_PO_WH_ID VARCHAR(2) ;
DECLARE VARIABLE WK_PO_COMPANY_ID COMPANY ;
BEGIN
   SELECT WH_ID, COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER = :WK_ORDER INTO :WK_PO_WH_ID, :WK_PO_COMPANY_ID;
   IF (WK_PO_COMPANY_ID IS NULL) THEN
   BEGIN
      WK_PO_COMPANY_ID = '';
   END
   IF (WK_PO_COMPANY_ID = '') THEN
   BEGIN
      WK_PO_COMPANY_ID = 'ALL';
   END
   /* do line stuff */
   WK_PROD_ID = WK_PROD1 || WK_EXTENSION1;
   WK_LOG_FILENAME = '/data/tmp/addpickprodpm.log';
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'start add pick prod items pm');
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'order: ' || :WK_ORDER );
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'prod1: ' || :WK_PROD1);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'prod: ' || :WK_PROD_ID);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'qty: ' || :WK_QTY1);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'line: ' || :WK_LINE_NO1);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'line: ' || :WK_LINE_NO1 || ':');
   WK_LINE_ADDED = 'F';
   IF (COALESCE(WK_LINE_NO1,'') <> '') THEN
   BEGIN
      WK_LINE_NO1 = ALLTRIM(WK_LINE_NO1);
      WK_LINE_LEN = STRLEN(WK_LINE_NO1);
      WHILE (WK_LINE_LEN < 4)
      DO
      BEGIN
         WK_LINE_NO1 = WK_LINE_NO1 || ' ';
         WK_LINE_LEN = WK_LINE_LEN + 1;
      END
   END
   /* does product exist */
   WK_FOUND = 0;
   SELECT 1  
   FROM PROD_PROFILE
   WHERE PROD_ID = :WK_PROD_ID
   AND COMPANY_ID = :WK_PO_COMPANY_ID
   INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* Not found so try company all */
      SELECT 1  
      FROM PROD_PROFILE
      WHERE PROD_ID = :WK_PROD_ID
      AND COMPANY_ID = 'ALL'
      INTO :WK_FOUND;
      IF (WK_FOUND = 0) THEN
      BEGIN
         /* no prod profile - so create a dummy */
         /*
         INSERT INTO PROD_PROFILE(PROD_ID, SHORT_DESC)
         VALUES (:WK_PROD_ID, :WK_PROD_ID);
         */
         WK_DEFAULT_UOM = '';
         SELECT STANDARD_UOM FROM UOM_TYPE
         WHERE CODE = 'UT'
         INTO :WK_DEFAULT_UOM;
         /*
         INSERT INTO PROD_PROFILE(PROD_ID, SHORT_DESC, UOM, ORDER_UOM, ISSUE_UOM, COMPANY_ID)
         VALUES (:WK_PROD_ID, :WK_PROD_ID, :WK_DEFAULT_UOM, :WK_DEFAULT_UOM, :WK_DEFAULT_UOM, :WK_PO_COMPANY_ID);
         */
      END
      ELSE
      BEGIN
         /* Product found in ALL */
         WK_PO_COMPANY_ID = 'ALL';
      END
   END
   WK_FOUND = 0;
   /* get length allowed for prods in prod_ean */
   SELECT MAX_LENGTH
   FROM PARAM
   WHERE DATA_ID = 'PROD_EAN'
   INTO :WK_PROD_EAN_LENGTH;
   IF (STRLEN(WK_PROD1) <= :WK_PROD_EAN_LENGTH) THEN
   BEGIN
      SELECT 1 FROM PROD_EAN
      WHERE PROD_EAN = :WK_PROD1 AND 
            PROD_EAN_EXTENSION = :WK_EXTENSION1
      INTO :WK_FOUND;
      IF (WK_FOUND = 0) THEN
      BEGIN
         /* no prod ean - so create one */
         INSERT INTO PROD_EAN(PROD_ID, PROD_EAN, PROD_EAN_EXTENSION)
         VALUES (:WK_PROD_ID, :WK_PROD1, :WK_EXTENSION1);
      END
   END
   WK_PROD_TYPE = '';
   WK_PROD_SALE_PRICE = 0;
   SELECT PROD_TYPE , SALE_PRICE 
   FROM PROD_PROFILE
   WHERE PROD_ID = :WK_PROD_ID
   AND COMPANY_ID = :WK_PO_COMPANY_ID
   INTO :WK_PROD_TYPE, :WK_PROD_SALE_PRICE;
   IF (WK_PROD_TYPE IS NULL) THEN
   BEGIN
      WK_PROD_TYPE = '';
   END
   IF (WK_SALE_PRICE IS NOT NULL) THEN
   BEGIN
      IF (WK_SALE_PRICE > 0) THEN
      BEGIN
         WK_PROD_SALE_PRICE = WK_SALE_PRICE;
      END
   END
   /* now check for default pick line status for this prod type */
   /* get controls status to use */
   WK_DEFAULT_PROD_STATUS = 'OP';
   WK_LINE_STATUS = 'OP';
   SELECT CONTROL.PICK_IMPORT_PROD_STATUS
   FROM CONTROL
   INTO :WK_DEFAULT_PROD_STATUS;
/*
   IF (WK_DEFAULT_PROD_STATUS IS NULL) THEN
   BEGIN
      WK_DEFAULT_PROD_STATUS = 'OP';
   END
   commented out because must allow a null status for apcd
*/
   /* WK_LINE_STATUS = 'OP'; */
   WK_LINE_STATUS = WK_DEFAULT_PROD_STATUS ;
/*
   SELECT DESCRIPTION  
   FROM OPTIONS
   WHERE GROUP_CODE = 'ProdTYPKST' AND CODE = :WK_PROD_TYPE
   INTO :WK_LINE_STATUS;
*/
   SELECT ADD_PICK_ITEM_STATUS
   FROM PROD_TYPE
   WHERE CODE = :WK_PROD_TYPE
   INTO :WK_LINE_STATUS;
    
   IF (WK_LINE_STATUS IS NULL) THEN
   BEGIN
      /* WK_LINE_STATUS = 'OP'; */
      WK_LINE_STATUS = WK_DEFAULT_PROD_STATUS ;
   END
   /* does line for product exist in order */
   BEGIN
      WK_FOUND = 0;
      SELECT 1, RETURN_DATE, PICK_DUE_DATE, PICK_ORDER_TYPE 
      FROM PICK_ORDER
      WHERE PICK_ORDER = :WK_ORDER
      INTO :WK_FOUND, :WK_PICK_RETURN_DATE, :WK_PICK_DUE_DATE, :WK_ORDER_TYPE;
      WK_FOUND = 0;
      IF (WK_LINE_NO1 IS NULL OR WK_LINE_NO1 = '') THEN
      BEGIN
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP') */
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP') */
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP', 'DX')
             OR (PICK_LINE_STATUS IS NULL) */
         /* SELECT 1, PICK_LABEL_NO FROM PICK_ITEM */
/* note only allow DX if prod type status is DX */
         SELECT FIRST 1 1, PICK_LABEL_NO FROM PICK_ITEM
         WHERE PICK_ORDER = :WK_ORDER
           AND PROD_ID = :WK_PROD_ID
           AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP' )
             OR (PICK_LINE_STATUS IS NULL)
             OR (PICK_LINE_STATUS = :WK_LINE_STATUS) )
         INTO :WK_FOUND, :WK_PICK_LABEL;
      END
      ELSE
      BEGIN
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP') */
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP') */
         /*  AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP', 'DX')
             OR (PICK_LINE_STATUS IS NULL) */
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'order: ' || :WK_ORDER );
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'prod: ' || :WK_PROD_ID);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'line: ' || :WK_LINE_NO1 || ':');
         /* SELECT 1, PICK_LABEL_NO FROM PICK_ITEM */
/* note only allow DX if prod type status is DX */
         SELECT FIRST 1 1, PICK_LABEL_NO FROM PICK_ITEM
         WHERE PICK_ORDER = :WK_ORDER
           AND PROD_ID = :WK_PROD_ID
           AND PICK_ORDER_LINE_NO = :WK_LINE_NO1
           AND (PICK_LINE_STATUS IN ('UC','CF','OP','UP','WP' )
             OR (PICK_LINE_STATUS IS NULL)
             OR (PICK_LINE_STATUS = :WK_LINE_STATUS) )
         INTO :WK_FOUND, :WK_PICK_LABEL;

/* this was to chew up some time for bhp soapminder to commit stuff
         FOR SELECT PICK_LABEL_NO,PICK_LINE_STATUS,PICK_ORDER_LINE_NO 
         FROM PICK_ITEM
         WHERE PICK_ORDER = :WK_ORDER
           AND PROD_ID = :WK_PROD_ID
           AND PICK_ORDER_LINE_NO = :WK_LINE_NO1
         INTO :WK_PI_LABEL, :WK_PI_STATUS, :WK_PI_LINENO
         DO
         BEGIN
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'got a line ');
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'label:' || :WK_PI_LABEL);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'status:' || :WK_PI_STATUS);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'line:' || :WK_PI_LINENO || ':');
         END
         FOR SELECT PICK_LABEL_NO,PICK_LINE_STATUS,PICK_ORDER_LINE_NO 
         FROM PICK_ITEM
         WHERE PICK_ORDER = :WK_ORDER
           AND PROD_ID = :WK_PROD_ID
         INTO :WK_PI_LABEL, :WK_PI_STATUS, :WK_PI_LINENO
         DO
         BEGIN
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'got a line ');
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'label:' || :WK_PI_LABEL);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'status:' || :WK_PI_STATUS);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'line:' || :WK_PI_LINENO || ':');
         END
*/
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'past reading lines ');
      END
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'found: ' || :WK_FOUND);
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'label: ' || :WK_PICK_LABEL);
      IF (WK_FOUND = 0) THEN
      BEGIN
         /* no line - so create one */
         /* calc the next label and line no */
         WK_PICK_LABEL = '';
         SELECT LABEL_NO FROM NEXT_PICK_LABEL
         INTO :WK_PICK_LABEL;
         IF ((WK_LINE_NO1 > '') AND (WK_LINE_NO1 <> '0')) THEN
         BEGIN
            WK_L_PICK_LINE_NO = WK_LINE_NO1;
         END
         ELSE
         BEGIN
            SELECT PICK_ORDER_LINE_NO 
            FROM GET_SALE_LINES_NO(:WK_ORDER) 
            INTO :WK_L_PICK_LINE_NO;
         END
         WK_PI_LINE_TOTAL = WK_PROD_SALE_PRICE * WK_QTY1; 
         WK_PI_SALE_PRICE = WK_PROD_SALE_PRICE ;
         WK_PI_DUE_DATE = NULL;
         WK_PI_RETURN_DATE = NULL ;
          
         INSERT INTO PICK_ITEM(
            PICK_ORDER, 
            PICK_LABEL_NO,
            PICK_ORDER_LINE_NO,
            PICK_LINE_STATUS, 
            PICK_ORDER_QTY, 
            PROD_ID,
            CREATE_DATE,
            USER_ID,
            SSN_CONFIRM,
            SALE_PRICE,
            PICK_LINE_DUE_DATE,
            RETURN_DATE,
            LINE_TOTAL)
         VALUES (
            :WK_ORDER, 
            :WK_PICK_LABEL,
            :WK_L_PICK_LINE_NO,
            :WK_LINE_STATUS, /* 'OP', */ 
            :WK_QTY1,
            :WK_PROD_ID,
            :WK_TRN_DATE,
            :WK_PERSON_ID,
            'I',
            :WK_PI_SALE_PRICE,
            :WK_PI_DUE_DATE,
            :WK_PI_RETURN_DATE,
            :WK_PI_LINE_TOTAL );
         WK_LINE_ADDED = 'T';
      END
      ELSE
      BEGIN
         UPDATE PICK_ITEM 
         SET PICK_ORDER_QTY = :WK_QTY1,
            CREATE_DATE = :WK_TRN_DATE,
            PICK_LINE_STATUS = :WK_LINE_STATUS, /* 'OP', */ 
            USER_ID = :WK_PERSON_ID
         WHERE PICK_LABEL_NO = :WK_PICK_LABEL;
      END
   END
   WK_LOG_RESULT = FILE_WRITELN(WK_LOG_FILENAME, 'end   add pick prod items pm');
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
