
ALTER PROCEDURE PC_GROUP_COPY (OBJECT VARCHAR(30) CHARACTER SET NONE,
SSN_TYPE VARCHAR(30) CHARACTER SET NONE,
GENERIC VARCHAR(30) CHARACTER SET NONE,
BRAND VARCHAR(30) CHARACTER SET NONE,
MODEL VARCHAR(30) CHARACTER SET NONE)
AS 
 
 
                                                                           
     
BEGIN
       
    UPDATE SSN
    SET SSN_TYPE = :SSN_TYPE, GENERIC = :GENERIC, BRAND = :BRAND, MODEL = :MODEL
    WHERE SSN_ID = :OBJECT; 
                      
END ^

