
CREATE PROCEDURE PC_GROUP_COPY (OBJECT VARCHAR(30) ,
SSN_TYPE VARCHAR(40) ,
GENERIC VARCHAR(40) ,
BRAND VARCHAR(40) ,
MODEL VARCHAR(40) ,
PROD_ID VARCHAR(30) ,
SUPPLIER_ID VARCHAR(40) ,
OTHER6 VARCHAR(50) ,
OTHER7 VARCHAR(50) ,
OTHER8 VARCHAR(50) ,
OTHER9 VARCHAR(50) ,
OTHER10 VARCHAR(50) ,
DESCRIPTION VARCHAR(50) )
AS 
 
     
BEGIN
       
    UPDATE SSN
    SET SSN_TYPE = :SSN_TYPE, 
        GENERIC = :GENERIC, 
        BRAND = :BRAND, 
        MODEL = :MODEL,
        PROD_ID = :PROD_ID,
        SUPPLIER_ID = :SUPPLIER_ID,
        OTHER6 = :OTHER6,
        OTHER7 = :OTHER7,
        OTHER8 = :OTHER8,
        OTHER9 = :OTHER9,
        OTHER10 = :OTHER10,
        SSN_DESCRIPTION = :DESCRIPTION
    WHERE SSN_ID = :OBJECT; 
                      
END ^

