

DROP TRIGGER INSERT_SKILLS ^
COMMIT^

CREATE TRIGGER INSERT_SKILLS FOR EMPLOYEE_SKILL
ACTIVE BEFORE INSERT POSITION 0 
AS
DECLARE VARIABLE WK_PERSON VARCHAR(10);
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_BY VARCHAR(10);
DECLARE VARIABLE WK_LOCN VARCHAR(40);
DECLARE VARIABLE WK_AUTH VARCHAR(50);
DECLARE VARIABLE WK_PASS CHAR(1);
DECLARE VARIABLE WK_TRESULT VARCHAR(20);
DECLARE VARIABLE WK_CERT TIMESTAMP;
DECLARE VARIABLE WK_COMPULSORY CHAR(1) ;
DECLARE VARIABLE WK_FOUND INTEGER;
BEGIN
   WK_PERSON = NEW.EMPLOYEE_ID;
   WK_CODE = NEW.SKILL_CODE;
   WK_DATE = NEW.TRAINING_DATE;
   WK_BY = NEW.TRAINING_BY;
   WK_LOCN = NEW.TRAINING_LOCATION;
   WK_AUTH = NEW.TRAINING_AUTHORITY;
   WK_PASS = NEW.TRAINING_PASS;
   WK_TRESULT = NEW.TRAINING_RESULT;
   WK_CERT = NEW.TRAINING_CERT_PRTD_DATE;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_FOUND = 0;
   SELECT 1 
   FROM TRAINING_SKILL
      WHERE PERSON_ID = :WK_PERSON
        AND TRAINING_CODE = :WK_CODE
        AND TRAINING_DATE = :WK_DATE
   INTO WK_FOUND;
   IF (WK_FOUND = 1) THEN
   BEGIN
      UPDATE TRAINING_SKILL SET
         TRAINING_BY =
                 :WK_BY,
         TRAINING_LOCATION =
                 :WK_LOCN,
         TRAINING_AUTHORITY =
                 :WK_AUTH,
         TRAINING_PASS =
                 :WK_PASS,
         TRAINING_RESULT =
                 :WK_TRESULT,
         TRAINING_CERT_PRINTED =
                 :WK_CERT,
         COMPULSORY_SKILL =
                 :WK_COMPULSORY
      WHERE PERSON_ID = :WK_PERSON
        AND TRAINING_CODE = :WK_CODE
        AND TRAINING_DATE = :WK_DATE;
   END
   ELSE
   BEGIN
      INSERT INTO TRAINING_SKILL(
         PERSON_ID ,
         TRAINING_CODE, 
         TRAINING_DATE, 
         TRAINING_BY ,
         TRAINING_LOCATION ,
         TRAINING_AUTHORITY ,
         TRAINING_PASS ,
         TRAINING_RESULT ,
         TRAINING_CERT_PRINTED ,
         COMPULSORY_SKILL)
         VALUES (:WK_PERSON,
                 :WK_CODE,
                 :WK_DATE,
                 :WK_BY,
                 :WK_LOCN,
                 :WK_AUTH,
                 :WK_PASS,
                 :WK_TRESULT,
                 :WK_CERT,
                 :WK_COMPULSORY);
            
   END

END^

DROP TRIGGER UPDATE_SKILLS ^
COMMIT^

CREATE TRIGGER UPDATE_SKILLS FOR EMPLOYEE_SKILL
ACTIVE BEFORE UPDATE POSITION 0 
AS
DECLARE VARIABLE WK_PERSON VARCHAR(10);
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_BY VARCHAR(10);
DECLARE VARIABLE WK_LOCN VARCHAR(40);
DECLARE VARIABLE WK_AUTH VARCHAR(50);
DECLARE VARIABLE WK_PASS CHAR(1);
DECLARE VARIABLE WK_TRESULT VARCHAR(20);
DECLARE VARIABLE WK_CERT TIMESTAMP;
DECLARE VARIABLE WK_COMPULSORY CHAR(1) ;
DECLARE VARIABLE WK_FOUND INTEGER;
BEGIN
   WK_PERSON = NEW.EMPLOYEE_ID;
   WK_CODE = NEW.SKILL_CODE;
   WK_DATE = NEW.TRAINING_DATE;
   WK_BY = NEW.TRAINING_BY;
   WK_LOCN = NEW.TRAINING_LOCATION;
   WK_AUTH = NEW.TRAINING_AUTHORITY;
   WK_PASS = NEW.TRAINING_PASS;
   WK_TRESULT = NEW.TRAINING_RESULT;
   WK_CERT = NEW.TRAINING_CERT_PRTD_DATE;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_FOUND = 0;
   SELECT 1 
   FROM TRAINING_SKILL
      WHERE PERSON_ID = :WK_PERSON
        AND TRAINING_CODE = :WK_CODE
        AND TRAINING_DATE = :WK_DATE
   INTO WK_FOUND;
   IF (WK_FOUND = 1) THEN
   BEGIN
      UPDATE TRAINING_SKILL SET
         TRAINING_BY =
                 :WK_BY,
         TRAINING_LOCATION =
                 :WK_LOCN,
         TRAINING_AUTHORITY =
                 :WK_AUTH,
         TRAINING_PASS =
                 :WK_PASS,
         TRAINING_RESULT =
                 :WK_TRESULT,
         TRAINING_CERT_PRINTED =
                 :WK_CERT,
         COMPULSORY_SKILL =
                 :WK_COMPULSORY
      WHERE PERSON_ID = :WK_PERSON
        AND TRAINING_CODE = :WK_CODE
        AND TRAINING_DATE = :WK_DATE;
   END
   ELSE
   BEGIN
      INSERT INTO TRAINING_SKILL(
         PERSON_ID ,
         TRAINING_CODE, 
         TRAINING_DATE, 
         TRAINING_BY ,
         TRAINING_LOCATION ,
         TRAINING_AUTHORITY ,
         TRAINING_PASS ,
         TRAINING_RESULT ,
         TRAINING_CERT_PRINTED ,
         COMPULSORY_SKILL)
         VALUES (:WK_PERSON,
                 :WK_CODE,
                 :WK_DATE,
                 :WK_BY,
                 :WK_LOCN,
                 :WK_AUTH,
                 :WK_PASS,
                 :WK_TRESULT,
                 :WK_CERT,
                 :WK_COMPULSORY);
            
   END

END^

