CREATE TABLE QTY_EAN (CODE CODE NOT NULL,
	DESCRIPTION DESCRIPTION,
        QTY QTY);

INSERT INTO QTY_EAN(CODE, DESCRIPTION, QTY) VALUES ('EA','ONE',1);
INSERT INTO QTY_EAN(CODE, DESCRIPTION, QTY) VALUES ('PR','PAIR',2);
INSERT INTO QTY_EAN(CODE, DESCRIPTION, QTY) VALUES ('FIVE','FIVE',5);


