

DROP TRIGGER INSERT_SKILL_CODES ^
COMMIT^

CREATE TRIGGER INSERT_SKILL_CODES FOR SKILL
ACTIVE BEFORE INSERT POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_SKILL CHAR(2);
DECLARE VARIABLE WK_DESC VARCHAR(50);
DECLARE VARIABLE WK_PUBLISH CHAR(1);
DECLARE VARIABLE WK_COMPULSORY CHAR(1);
DECLARE VARIABLE WK_CREATED_DATE TIMESTAMP;
DECLARE VARIABLE WK_CREATED_BY VARCHAR(10);
DECLARE VARIABLE WK_FOUND INTEGER;
BEGIN
   WK_CODE = NEW.CODE;
   WK_SKILL = NEW.SKILL_TYPE;
   WK_DESC = NEW.DESCRIPTION;
   WK_PUBLISH = NEW.PUBLISH;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_CREATED_DATE = NEW.CREATED_DATE;
   WK_CREATED_BY = NEW.CREATED_BY;
   WK_FOUND = 0;
   SELECT 1 
   FROM TRAINING_SKILL_CODES
   WHERE CODE = :WK_CODE
   INTO WK_FOUND;
   IF (WK_FOUND = 1) THEN
   BEGIN
      UPDATE TRAINING_SKILL_CODES SET
      DESCRIPTION = :WK_DESC,
      SKILL_TYPE = :WK_SKILL,
      PUBLISH = :WK_PUBLISH,
      COMPULSORY_SKILL = :WK_COMPULSORY,
      CREATED_DATE = :WK_CREATED_DATE,
      CREATED_BY = :WK_CREATED_BY
      WHERE CODE = :WK_CODE;
   END
   ELSE
   BEGIN
      INSERT INTO TRAINING_SKILL_CODES 
      (DESCRIPTION ,
      SKILL_TYPE ,
      PUBLISH ,
      COMPULSORY_SKILL ,
      CREATED_DATE ,
      CREATED_BY,
      CODE)
      VALUES( :WK_DESC,
      :WK_SKILL,
      :WK_PUBLISH,
      :WK_COMPULSORY,
      :WK_CREATED_DATE,
      :WK_CREATED_BY,
      :WK_CODE);
   END
END^

DROP TRIGGER UPDATE_SKILL_CODES ^
COMMIT^

CREATE TRIGGER UPDATE_SKILL_CODES FOR SKILL
ACTIVE BEFORE UPDATE POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_SKILL CHAR(2);
DECLARE VARIABLE WK_DESC VARCHAR(50);
DECLARE VARIABLE WK_PUBLISH CHAR(1);
DECLARE VARIABLE WK_COMPULSORY CHAR(1);
DECLARE VARIABLE WK_CREATED_DATE TIMESTAMP;
DECLARE VARIABLE WK_CREATED_BY VARCHAR(10);
DECLARE VARIABLE WK_FOUND INTEGER;
BEGIN
   WK_CODE = NEW.CODE;
   WK_SKILL = NEW.SKILL_TYPE;
   WK_DESC = NEW.DESCRIPTION;
   WK_PUBLISH = NEW.PUBLISH;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_CREATED_DATE = NEW.CREATED_DATE;
   WK_CREATED_BY = NEW.CREATED_BY;
   WK_FOUND = 0;
   SELECT 1 
   FROM TRAINING_SKILL_CODES
   WHERE CODE = :WK_CODE
   INTO WK_FOUND;
   IF (WK_FOUND = 1) THEN
   BEGIN
      UPDATE TRAINING_SKILL_CODES SET
      DESCRIPTION = :WK_DESC,
      SKILL_TYPE = :WK_SKILL,
      PUBLISH = :WK_PUBLISH,
      COMPULSORY_SKILL = :WK_COMPULSORY,
      CREATED_DATE = :WK_CREATED_DATE,
      CREATED_BY = :WK_CREATED_BY
      WHERE CODE = :WK_CODE;
   END
   ELSE
   BEGIN
      INSERT INTO TRAINING_SKILL_CODES 
      (DESCRIPTION ,
      SKILL_TYPE ,
      PUBLISH ,
      COMPULSORY_SKILL ,
      CREATED_DATE ,
      CREATED_BY,
      CODE)
      VALUES( :WK_DESC,
      :WK_SKILL,
      :WK_PUBLISH,
      :WK_COMPULSORY,
      :WK_CREATED_DATE,
      :WK_CREATED_BY,
      :WK_CODE);
   END
END^

