

DROP TRIGGER INSERT_TRAINING_SKILL_CODES ^
COMMIT^

CREATE TRIGGER INSERT_TRAINING_SKILL_CODES FOR TRAINING_SKILL_CODES
ACTIVE AFTER  INSERT POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_SKILL CHAR(2);
DECLARE VARIABLE WK_DESC VARCHAR(50);
DECLARE VARIABLE WK_PUBLISH CHAR(1);
DECLARE VARIABLE WK_COMPULSORY CHAR(1);
DECLARE VARIABLE WK_CREATED_DATE TIMESTAMP;
DECLARE VARIABLE WK_CREATED_STR VARCHAR(30) ;
DECLARE VARIABLE WK_CREATED_BY VARCHAR(10);
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_QUOTE CHAR(1);
BEGIN
   WK_QUOTE = chr(39);
   WK_CODE = NEW.CODE;
   WK_SKILL = NEW.SKILL_TYPE;
   WK_DESC = NEW.DESCRIPTION;
   WK_PUBLISH = NEW.PUBLISH;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_CREATED_DATE = NEW.CREATED_DATE;
   WK_CREATED_STR = CAST(WK_CREATED_DATE AS CHAR(22));
   WK_CREATED_BY = NEW.CREATED_BY;
   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'newskillcode.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_CODE) || ',' ||
   WK_QUOTE || NONULL(WK_SKILL) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_DESC) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_PUBLISH) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_COMPULSORY) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_CREATED_STR) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_CREATED_BY) || WK_QUOTE ; 
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'newskillcode.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

DROP TRIGGER UPDATE_TRAINING_SKILL_CODES ^
COMMIT^

CREATE TRIGGER UPDATE_TRAINING_SKILL_CODES FOR TRAINING_SKILL_CODES
ACTIVE AFTER  UPDATE POSITION 0 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_SKILL CHAR(2);
DECLARE VARIABLE WK_DESC VARCHAR(50);
DECLARE VARIABLE WK_PUBLISH CHAR(1);
DECLARE VARIABLE WK_COMPULSORY CHAR(1);
DECLARE VARIABLE WK_CREATED_DATE TIMESTAMP;
DECLARE VARIABLE WK_CREATED_STR VARCHAR(30) ;
DECLARE VARIABLE WK_CREATED_BY VARCHAR(10);
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(255);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_QUOTE CHAR(1);
BEGIN
   WK_QUOTE = chr(39);
   WK_CODE = NEW.CODE;
   WK_SKILL = NEW.SKILL_TYPE;
   WK_DESC = NEW.DESCRIPTION;
   WK_PUBLISH = NEW.PUBLISH;
   WK_COMPULSORY = NEW.COMPULSORY_SKILL;
   WK_CREATED_DATE = NEW.CREATED_DATE;
   WK_CREATED_STR = CAST(WK_CREATED_DATE AS CHAR(22));
   WK_CREATED_BY = NEW.CREATED_BY;
   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'updskillcode.trn';
   WK_LABEL_LINE = SQUOTEDSTR(WK_CODE) || ',' ||
   WK_QUOTE || NONULL(WK_SKILL) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_DESC) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_PUBLISH) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_COMPULSORY) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_CREATED_STR) || WK_QUOTE || ',' ||
   WK_QUOTE || NONULL(WK_CREATED_BY) || WK_QUOTE ; 
   WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'updskillcode.2rn';
      WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
   END

END^

