CREATE TABLE SKILL_PASS (CODE CODE NOT NULL,
	DESCRIPTION DESCRIPTION);

INSERT INTO SKILL_PASS(CODE, DESCRIPTION) VALUES ('PASS','COMPETENT');
INSERT INTO SKILL_PASS(CODE, DESCRIPTION) VALUES ('FAIL','INCOMPETENT');


