DROP TRIGGER DELETE_TRAINING_SKILL;
DROP TRIGGER INSERT_TRAINING_SKILL;
DROP TRIGGER UPDATE_TRAINING_SKILL;

COMMIT;

ALTER TABLE TRAINING_SKILL DROP TRAINING_LOCATION;
COMMIT;
ALTER TABLE TRAINING_SKILL ADD  TRAINING_LOCATION CODE;
ALTER TABLE TRAINING_SKILL ADD  COMPULSORY_SKILL CHAR(1);

