ALTER TABLE TRAINING_SKILL_CODES ADD PUBLISH CHAR(1);
ALTER TABLE TRAINING_SKILL_CODES ADD COMPULSORY_SKILL CHAR(1);
ALTER TABLE TRAINING_SKILL_CODES ADD CREATED_DATE TIMESTAMP;
ALTER TABLE TRAINING_SKILL_CODES ADD CREATED_BY PERSON;
