CREATE TABLE PRODUCT_KIT (
KIT_ID	PRODUCT NOT NULL,
PROD_ID PRODUCT NOT NULL,
PROD_QTY INTEGER,
CREATED_BY USER_ID,
CREATE_DATE CREATE_DATE,
PRIMARY KEY (KIT_ID, PROD_ID));

CREATE TABLE EMPLOYEE_ISSUE (
EMPLOYEE_TYPE CODE_TWO NOT NULL,
KIT_ID	PRODUCT  NOT NULL,
PRIMARY KEY (EMPLOYEE_TYPE, KIT_ID));

