
/* CREATE INDEX PACK_SSCC_IDX ON PACK_SSCC (PS_SSCC); */
CREATE INDEX PACK_SSCC_ORDER_LINE_IDX ON PACK_SSCC (PS_PICK_ORDER,PS_PICK_ORDER_LINE_NO);

/* use company from the order not from the vendor field */

COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER TRIGGER ADD_PACK_SSCC FOR PACK_SSCC 
ACTIVE BEFORE INSERT POSITION 10 
AS
DECLARE VARIABLE WK_SO_COMPANY_ID VARCHAR(20);
BEGIN
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(PACK_SSCC_ID_GEN,1);
   END
   NEW.PS_LAST_UPDATE_DATE = 'NOW';
   IF ((NEW.PS_SSCC IS NULL) OR (NEW.PS_SSCC = '')) THEN
   BEGIN
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      /* SELECT SSCC_ID FROM NEXT_SSCC_ID(NEW.PS_VENDOR_IN_HOUSE_NO) INTO NEW.PS_SSCC; */
      SELECT SSCC_ID FROM NEXT_SSCC_ID(:WK_SO_COMPANY_ID) INTO NEW.PS_SSCC;
   END
END ^

CREATE OR ALTER TRIGGER UPD_PACK_SSCC FOR PACK_SSCC 
ACTIVE BEFORE UPDATE POSITION 10 
AS
DECLARE VARIABLE WK_SO_COMPANY_ID VARCHAR(20);
BEGIN
   IF ((NEW.RECORD_ID IS NULL) OR (NEW.RECORD_ID = 0)) THEN
   BEGIN
      NEW.RECORD_ID  = GEN_ID(PACK_SSCC_ID_GEN,1);
   END
   NEW.PS_LAST_UPDATE_DATE = 'NOW';
   IF ((NEW.PS_SSCC IS NULL) OR (NEW.PS_SSCC = '')) THEN
   BEGIN
      SELECT COMPANY_ID FROM PICK_ORDER WHERE PICK_ORDER.PICK_ORDER = NEW.PS_PICK_ORDER INTO :WK_SO_COMPANY_ID;
      /* SELECT SSCC_ID FROM NEXT_SSCC_ID(NEW.PS_VENDOR_IN_HOUSE_NO) INTO NEW.PS_SSCC; */
      SELECT SSCC_ID FROM NEXT_SSCC_ID(:WK_SO_COMPANY_ID) INTO NEW.PS_SSCC;
   END
END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
