COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 

DROP TRIGGER RUN_TRANSACTION_UIXX ^
COMMIT^

CREATE TRIGGER RUN_TRANSACTION_UIXX FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 2 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0);
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (SUBSTR(NEW.TRN_TYPE,1,2) = 'UI') THEN
  BEGIN
   EXECUTE PROCEDURE PC_UIXX
   (NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID,
    NEW.INSTANCE_ID);
   /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
  END
 END
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
