COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER TRIGGER ADD_PICK_ITEM_DETAIL_TIME FOR PICK_ITEM_DETAIL
ACTIVE BEFORE INSERT POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   IF (NEW.PICK_ORDER IS NULL) THEN
   BEGIN
      SELECT PICK_ITEM.PICK_ORDER 
      FROM PICK_ITEM
      WHERE PICK_ITEM.PICK_LABEL_NO = NEW.PICK_LABEL_NO
      INTO NEW.PICK_ORDER;
      SELECT PICK_ORDER.COMPANY_ID, PICK_ORDER.ZONE_C, PICK_ORDER.PICK_ORDER_SUB_TYPE ,PICK_ORDER.ALTERNATE_COMPANYS
      FROM PICK_ORDER 
      WHERE PICK_ORDER.PICK_ORDER = NEW.PICK_ORDER
      INTO NEW.COMPANY_ID, NEW.ZONE_C, NEW.PICK_ORDER_SUB_TYPE, NEW.ALTERNATE_COMPANYS;
   END
   IF (NEW.PROD_ID IS NULL ) THEN
   BEGIN
      SELECT ISSN.PROD_ID 
      FROM ISSN
      WHERE ISSN.SSN_ID = NEW.SSN_ID
      INTO NEW.PROD_ID;
   END
   IF (NEW.PS_CUSTOMER_EDI_NO IS NULL ) THEN
   BEGIN
      SELECT FIRST 1 PACK_SSCC.PS_CUSTOMER_EDI_NO ,PACK_SSCC.PS_DEL_TO_STORE_IN_HOUSE_NO ,PACK_SSCC.PS_DEL_TO_DC_IN_HOUSE_NO 
      FROM PACK_SSCC
      WHERE PACK_SSCC.PS_PICK_LABEL_NO = NEW.PICK_LABEL_NO
      INTO NEW.PS_CUSTOMER_EDI_NO, NEW.PS_DEL_TO_STORE_IN_HOUSE_NO, NEW.PS_DEL_TO_DC_IN_HOUSE_NO ;
   END
   
END^


CREATE OR ALTER TRIGGER UPDATE_PICK_ITEM_DETAIL_TIME FOR PICK_ITEM_DETAIL 
ACTIVE BEFORE UPDATE POSITION 20 
AS
DECLARE VARIABLE WK_LEGACY_TRYS INTEGER;
DECLARE VARIABLE WK_PICK_ORDER VARCHAR(15);
DECLARE VARIABLE WK_LEGACY_ID VARCHAR(50);
DECLARE VARIABLE WK_GOTO_DX CHAR(1);
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   IF (NEW.PICK_ORDER IS NULL) THEN
   BEGIN
      SELECT PICK_ITEM.PICK_ORDER 
      FROM PICK_ITEM
      WHERE PICK_ITEM.PICK_LABEL_NO = NEW.PICK_LABEL_NO
      INTO NEW.PICK_ORDER;
      SELECT PICK_ORDER.COMPANY_ID, PICK_ORDER.ZONE_C, PICK_ORDER.PICK_ORDER_SUB_TYPE, PICK_ORDER.ALTERNATE_COMPANYS 
      FROM PICK_ORDER 
      WHERE PICK_ORDER.PICK_ORDER = NEW.PICK_ORDER
      INTO NEW.COMPANY_ID, NEW.ZONE_C, NEW.PICK_ORDER_SUB_TYPE, NEW.ALTERNATE_COMPANYS;
   END
   IF (NEW.PID_LEGACY_TRY IS NULL) THEN
   BEGIN
      NEW.PID_LEGACY_TRY = 0;
   END
   IF (NEW.PICK_DETAIL_STATUS = 'Dl') THEN
   BEGIN
      SELECT LEGACY_TRYS FROM CONTROL INTO :WK_LEGACY_TRYS;
      IF (WK_LEGACY_TRYS IS NULL) THEN
      BEGIN
         WK_LEGACY_TRYS = 0;
      END
      NEW.PID_LEGACY_TRY = NEW.PID_LEGACY_TRY + 1;
      IF (NEW.PID_LEGACY_TRY < :WK_LEGACY_TRYS) THEN
      BEGIN
         NEW.PICK_DETAIL_STATUS = 'DL';
      END
   END
   IF (NEW.PICK_DETAIL_STATUS = 'DL') THEN
   BEGIN
      WK_GOTO_DX = 'F';
      SELECT PICK_ORDER FROM PICK_ITEM
      WHERE  PICK_LABEL_NO = NEW.PICK_LABEL_NO
      INTO :WK_PICK_ORDER;
      SELECT SO_LEGACY_INTERNAL_ID FROM PICK_ORDER
      WHERE PICK_ORDER  = :WK_PICK_ORDER
      INTO :WK_LEGACY_ID;
      IF (WK_LEGACY_ID IS NULL ) THEN
      BEGIN
         WK_GOTO_DX = 'T';
      END
      IF (WK_LEGACY_ID = '') THEN
      BEGIN
         WK_GOTO_DX = 'T';
      END
      IF (WK_GOTO_DX = 'T') THEN
      BEGIN
         NEW.PICK_DETAIL_STATUS = 'DX';
      END
   END
END ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

