SET TERM ^ ;

ALTER PROCEDURE UPDATE_SSN_QTY_TROL (OBJECT VARCHAR(30),
QTY INTEGER)
AS 
 
                                                      
     
BEGIN
   /* Update CURRENT_QTY in SSN table */   
/*
   UPDATE SSN
   SET CURRENT_QTY = CURRENT_QTY + (:QTY)
   WHERE SSN_ID = :OBJECT;
*/
   UPDATE ISSN
   SET CURRENT_QTY = CURRENT_QTY + (:QTY)
   WHERE SSN_ID = :OBJECT;
         
   SUSPEND;
END ^

ALTER PROCEDURE UPDATE_SSN_TRIL_A (OBJECT VARCHAR(30),
WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
TRN_DATE TIMESTAMP,
QTY INTEGER)
AS 
 
                                                       
  DECLARE VARIABLE strORIGINAL_SSN VARCHAR(20);
     
BEGIN
   /* Update SSN table */   
/*
   UPDATE SSN
   SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE,
       CURRENT_QTY = CURRENT_QTY + :QTY
   WHERE SSN_ID = :OBJECT;
*/
         
   SELECT ORIGINAL_SSN FROM ISSN 
	WHERE SSN_ID = :OBJECT
	INTO :strORIGINAL_SSN;
   UPDATE ISSN
   SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE
   WHERE SSN_ID = :OBJECT;
   IF (strORIGINAL_SSN = OBJECT) THEN
   BEGIN
      UPDATE SSN
         SET WH_ID = :WH_ID, LOCN_ID = :LOCN_ID, INTO_DATE = :TRN_DATE
      WHERE SSN_ID = :OBJECT;
   END
      
   SUSPEND;
END ^

ALTER PROCEDURE UPDATE_SSN_TROL_A (OBJECT VARCHAR(30),
WH_ID CHAR(2),
LOCN_ID VARCHAR(10),
TRN_DATE TIMESTAMP,
DEVICE_ID CHAR(2))
AS 
 
                                                      
  DECLARE VARIABLE strORIGINAL_SSN VARCHAR(20);
     
BEGIN
   /* Update SSN table */   
/*
   UPDATE SSN
   SET PREV_LOCN_ID = :LOCN_ID, LOCN_ID = :DEVICE_ID, WH_ID = :WH_ID,
       DT_PREV_INTO = :TRN_DATE
   WHERE SSN_ID = :OBJECT;
*/
   
   SELECT ORIGINAL_SSN FROM ISSN 
	WHERE SSN_ID = :OBJECT
	INTO :strORIGINAL_SSN;
   UPDATE ISSN
   SET PREV_LOCN_ID = :LOCN_ID, LOCN_ID = :DEVICE_ID, WH_ID = :WH_ID,
       PREV_DATE = :TRN_DATE
   WHERE SSN_ID = :OBJECT;
   IF (strORIGINAL_SSN = OBJECT) THEN
   BEGIN
      UPDATE SSN
      SET PREV_LOCN_ID = :LOCN_ID, LOCN_ID = :DEVICE_ID, WH_ID = :WH_ID,
          DT_PREV_INTO = :TRN_DATE
      WHERE SSN_ID = :OBJECT;
      
   END
         
   SUSPEND;
END ^

ALTER PROCEDURE UPDATE_TRAN (RECORD_ID INTEGER,
COMPLETE CHAR(1),
ERROR_TEXT VARCHAR(70))
AS 
 
 
BEGIN
    /* Update transactions table */
    UPDATE TRANSACTIONS
    SET COMPLETE = :COMPLETE, ERROR_TEXT = :ERROR_TEXT
    WHERE RECORD_ID = :RECORD_ID;
 
    SUSPEND;
END ^
SET TERM ; ^
COMMIT WORK ;
SET AUTODDL ON;

