ALTER TABLE LOCATION ADD ORIG_WH_ID WH_ID;
/* create a trigger to populate this field ie on insert */

UPDATE LOCATION SET ORIG_WH_ID = WH_ID;

SET TERM ^;
CREATE TRIGGER BI_LOCATION_INIT4 FOR LOCATION  
ACTIVE BEFORE INSERT POSITION 4
AS
BEGIN
  IF (NEW.ORIG_WH_ID IS NULL) THEN
    NEW.ORIG_WH_ID = NEW.WH_ID;
END ^

