COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* what is the company to use ? */

CREATE OR ALTER TRIGGER RUN_TRANSACTION_PPSP FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 109 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_PROD_ID VARCHAR(30);
DECLARE VARIABLE WK_WH_ID CHAR(2);
DECLARE VARIABLE WK_LOCN_ID VARCHAR(10);
DECLARE VARIABLE WK_SUBLOCN_ID VARCHAR(10);
DECLARE VARIABLE WK_REF_ID VARCHAR(40);
DECLARE VARIABLE WK_QTY INTEGER;
DECLARE VARIABLE WK_USER VARCHAR(10);
DECLARE VARIABLE WK_DEVICE CHAR(2);
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_LOCN_2 VARCHAR(12);
DECLARE VARIABLE WK_REF_2 VARCHAR(60);
DECLARE VARIABLE WK_PALLET_CFG VARCHAR(12);
DECLARE VARIABLE WK_PERM VARCHAR(12);
DECLARE VARIABLE WK_TURNOVER VARCHAR(12);
/* DECLARE VARIABLE WK_NET_WT INTEGER; */
DECLARE VARIABLE WK_NET_WT DECIMAL(4,3);
DECLARE VARIABLE WK_MAX_QTY INTEGER;
DECLARE VARIABLE WK_MIN_QTY INTEGER;
DECLARE VARIABLE WK_REORDER_QTY INTEGER;
DECLARE VARIABLE WK_MAX_ISSUE_QTY INTEGER;
DECLARE VARIABLE WK_DEF_ISSUE_QTY INTEGER;
DECLARE VARIABLE WK_NET_WT_X VARCHAR(50);
DECLARE VARIABLE WK_MAX_QTY_X VARCHAR(50);
DECLARE VARIABLE WK_MIN_QTY_X VARCHAR(50);
DECLARE VARIABLE WK_REORDER_QTY_X VARCHAR(50);
DECLARE VARIABLE WK_MAX_ISSUE_QTY_X VARCHAR(50);
DECLARE VARIABLE WK_DEF_ISSUE_QTY_X VARCHAR(50);
DECLARE VARIABLE WK_RECORD_ID INTEGER;
DECLARE VARIABLE WK_ERROR_TEXT  VARCHAR(70);
DECLARE VARIABLE WK_COMPANY VARCHAR(20);
DECLARE VARIABLE WK_COMPANY_ID VARCHAR(20);
DECLARE VARIABLE WK_PROD_ID2 VARCHAR(30);
BEGIN
   WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
   IF (WK_AUTORUN = 1) THEN
   BEGIN
      IF (NEW.TRN_TYPE = 'PPSP') THEN
      BEGIN
         /* check exists */
         WK_FOUND = 0;
         WK_PROD_ID = NEW.OBJECT;
         WK_WH_ID = NEW.WH_ID;
         WK_LOCN_ID = NEW.LOCN_ID;
         WK_SUBLOCN_ID = NEW.SUB_LOCN_ID;
         WK_REF_ID = NEW.REFERENCE;
         WK_QTY = NEW.QTY;
         WK_USER = NEW.PERSON_ID;
         WK_DEVICE = NEW.DEVICE_ID;
         WK_DATE = NEW.TRN_DATE;
         WK_RECORD_ID = NEW.RECORD_ID;
         WK_COMPANY_ID = NEW.COMPANY_ID;
         WK_PROD_ID2 = NEW.PROD_ID;

/*
         WK_LOCN_2 = WK_WH_ID || WK_LOCN_ID;
*/
/*
         WK_REF_2 = WK_SUBLOCN_ID || WK_REF_ID;
*/
         WK_REF_2 = WK_WH_ID || WK_LOCN_ID || WK_SUBLOCN_ID || WK_REF_ID;
/*
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 1  RETURNING_VALUES :WK_PALLET_CFG ; 
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 2  RETURNING_VALUES :WK_PERM ; 
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 3  RETURNING_VALUES :WK_TURNOVER ; 

         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 4  RETURNING_VALUES :WK_NET_WT_X ; 
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 5  RETURNING_VALUES :WK_MAX_QTY_X ; 
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 6  RETURNING_VALUES :WK_MIN_QTY_X;
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 7  RETURNING_VALUES :WK_REORDER_QTY_X;
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 8  RETURNING_VALUES :WK_MAX_ISSUE_QTY_X;
         EXECUTE PROCEDURE GET_REFERENCE_FIELD :WK_REF_2, 9  RETURNING_VALUES :WK_DEF_ISSUE_QTY_X;
*/

         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 1, '|') INTO :WK_PALLET_CFG ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 2, '|') INTO :WK_PERM ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 3, '|') INTO :WK_TURNOVER ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 4, '|') INTO :WK_NET_WT_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 5, '|') INTO :WK_MAX_QTY_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 6, '|') INTO :WK_MIN_QTY_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 7, '|') INTO :WK_REORDER_QTY_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 8, '|') INTO :WK_MAX_ISSUE_QTY_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 9, '|') INTO :WK_DEF_ISSUE_QTY_X ;
         SELECT WK_FIELD_TEXT FROM GET_REFERENCE_FIELD4 (:WK_REF_2, 10, '|') INTO :WK_COMPANY ;

         IF (WK_NET_WT_X = '') THEN
            WK_NET_WT_X  = '0';
         IF (WK_MAX_QTY_X = '') THEN
            WK_MAX_QTY_X  = '0';
         IF (WK_MIN_QTY_X = '') THEN
            WK_MIN_QTY_X  = '0';
         IF (WK_REORDER_QTY_X = '') THEN
            WK_REORDER_QTY_X  = '0';
         IF (WK_MAX_ISSUE_QTY_X = '') THEN
            WK_MAX_ISSUE_QTY_X  = '0';
         IF (WK_DEF_ISSUE_QTY_X = '') THEN
            WK_DEF_ISSUE_QTY_X  = '0';
         /* WK_NET_WT = CAST(WK_NET_WT_X AS INTEGER); */
         WK_NET_WT = CAST(WK_NET_WT_X AS DECIMAL(4, 3));
         WK_MAX_QTY = CAST(WK_MAX_QTY_X AS INTEGER);
         WK_MIN_QTY = CAST(WK_MIN_QTY_X AS INTEGER);
         WK_REORDER_QTY = CAST(WK_REORDER_QTY_X AS INTEGER);
         WK_MAX_ISSUE_QTY = CAST(WK_MAX_ISSUE_QTY_X AS INTEGER);
         WK_DEF_ISSUE_QTY = CAST(WK_DEF_ISSUE_QTY_X AS INTEGER);

         IF (WK_COMPANY = '') THEN
         BEGIN
            IF (WK_COMPANY_ID IS NOT NULL) THEN
               WK_COMPANY = WK_COMPANY_ID;
         END
         IF (WK_COMPANY = '') THEN
         BEGIN
            SELECT COMPANY_ID FROM CONTROL INTO :WK_COMPANY;
            IF (WK_COMPANY IS NULL) THEN
               WK_COMPANY = '';
         END
         IF (WK_COMPANY = '') THEN
            WK_COMPANY = 'ALL';

         SELECT 1 FROM PROD_PROFILE   
         WHERE PROD_ID = :WK_PROD_ID
         AND COMPANY_ID = :WK_COMPANY
         INTO :WK_FOUND;
         IF (WK_FOUND IS NULL) THEN
         BEGIN
            WK_FOUND = 0;
         END
         IF (WK_FOUND = 0) THEN
         BEGIN
            INSERT INTO PROD_PROFILE (PROD_ID, SHORT_DESC, PALLET_CFG_C, PERM_LEVEL, TOG_C, NET_WEIGHT, MAX_QTY, MIN_QTY, REORDER_QTY, MAX_ISSUE_QTY, DEFAULT_ISSUE_QTY, SALE_PRICE, LAST_UPDATE_DATE, LAST_UPDATE_BY, COMPANY_ID)
            VALUES (:WK_PROD_ID, :WK_PROD_ID, :WK_PALLET_CFG, :WK_PERM, :WK_TURNOVER, :WK_NET_WT, :WK_MAX_QTY, :WK_MIN_QTY, :WK_REORDER_QTY, :WK_MAX_ISSUE_QTY, :WK_DEF_ISSUE_QTY,  :WK_QTY/100, :WK_DATE, :WK_USER, :WK_COMPANY);
         END
         ELSE
         BEGIN
            UPDATE PROD_PROFILE SET  
            PALLET_CFG_C =  :WK_PALLET_CFG, 
            PERM_LEVEL =  :WK_PERM, 
            TOG_C =  :WK_TURNOVER, 
            NET_WEIGHT =  :WK_NET_WT, 
            MAX_QTY =  :WK_MAX_QTY, 
            MIN_QTY =  :WK_MIN_QTY, 
            REORDER_QTY =  :WK_REORDER_QTY, 
            MAX_ISSUE_QTY =  :WK_MAX_ISSUE_QTY, 
            DEFAULT_ISSUE_QTY =  :WK_DEF_ISSUE_QTY, 
            SALE_PRICE =  :WK_QTY / 100, 
            LAST_UPDATE_DATE =  :WK_DATE, 
            LAST_UPDATE_BY = :WK_USER
            WHERE PROD_ID = :WK_PROD_ID 
            AND COMPANY_ID = :WK_COMPANY;
         END
         /* EXECUTE PROCEDURE UPDATE_TRAN (:WK_RECORD_ID, 'T','Processed successfully'); */
         WK_ERROR_TEXT = 'Processed successfully';
         UPDATE TRANSACTIONS SET COMPLETE='T',ERROR_TEXT=:WK_ERROR_TEXT WHERE RECORD_ID = :WK_RECORD_ID;
         /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
      END
   END
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
