COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;


CREATE OR ALTER TRIGGER RUN_TRANSACTION_PKDL FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 53 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_DEVICE CHAR(2);
DECLARE VARIABLE WK_USER VARCHAR(10);
DECLARE VARIABLE WK_RECORD INTEGER;
DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(80);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_PI_LABEL VARCHAR(7);
DECLARE VARIABLE WK_PI_LOCATION VARCHAR(10);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(200);
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'PKDL') THEN
  BEGIN
     WK_DEVICE = NEW.WH_ID;
     WK_USER = NEW.PERSON_ID;
     WK_RECORD = NEW.RECORD_ID;

     WK_DIRECTORY = '';
     SELECT FTP_DIRECTORY
         FROM CONTROL
         INTO :WK_DIRECTORY;
      WK_FILENAME = WK_DIRECTORY || WK_DEVICE || '.pk';
     /* clear devices file */
      WK_RESULT = FILE_DELETE(WK_FILENAME);
     FOR 
        SELECT PICK_LABEL_NO, 
               DESPATCH_LOCATION
               FROM PICK_ITEM
               WHERE PICK_LINE_STATUS IN ('PL')
                 AND DEVICE_ID = :WK_DEVICE
               INTO :WK_PI_LABEL, :WK_PI_LOCATION 
     DO
     BEGIN
           /* add to devices file */
/*         WK_LABEL_LINE = 'UPDATE PICK_QTYS SET DESPATCH_LOCATION = ' ||
             SQUOTEDSTR(WK_PI_LOCATION ) ||
             ' WHERE PICK_LABEL_NO = ' ||
             SQUOTEDSTR(WK_PI_LABEL ) || ')'; */
           WK_LABEL_LINE = 'UPDATE PICK_QTYS SET DESPATCH_LOCATION = ' ||
             '''' || WK_PI_LOCATION || '''' ||
             ' WHERE PICK_LABEL_NO = ' ||
             '''' || WK_PI_LABEL || ''''  ;
           WK_RESULT = FILE_WRITELN(WK_FILENAME, WK_LABEL_LINE);
     END

   EXECUTE PROCEDURE UPDATE_TRAN (WK_RECORD, 'T','Processed successfully');
   /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
  END
 END
END ^
 

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
