{
	print "/*"
	print "CREATE PROCEDURE UPDATE_EMP_SETUP"
	print "*/"
	print "ALTER  PROCEDURE UPDATE_EMP_SETUP"
	print "AS"
	print "DECLARE VARIABLE WK_EMP_NO VARCHAR(10);"
	print "DECLARE VARIABLE WK_FIELD  VARCHAR(255);"
	print "BEGIN"
	item=$1
	print "FOR SELECT EMPLOYEE_ID FROM EMPLOYEE"
	printf "%s%s%s\n", "WHERE EMPLOYEE.",item," IS NULL"
	print "INTO :WK_EMP_NO"
	print "DO"
	print "BEGIN"
	printf "%s %s %s\n","   SELECT",item ,"FROM PERSON WHERE PERSON_ID = :WK_EMP_NO INTO :WK_FIELD;"
	printf "%s %s %s\n", "   UPDATE EMPLOYEE SET",item," =  :WK_FIELD"
	print "   WHERE EMPLOYEE_ID = :WK_EMP_NO;"
	print "END"
	print "END^"
	print "COMMIT^"
	print "EXECUTE PROCEDURE UPDATE_EMP_SETUP"
	print "COMMIT^"
}
