--Table: IMPORT_MAP

--DROP TABLE IMPORT_MAP;

CREATE TABLE IMPORT_MAP (
  RECORD_ID            RECORD_ID NOT NULL,
  IMPORT_RULES_NAME    VARCHAR(20) NOT NULL,
  MAP_IMPORT_COL       VARCHAR(30) NOT NULL,
  MAP_IMS_SEQUENCE     SEQUENCE_NO DEFAULT 0,
  MAP_IMS_TABLE        VARCHAR(40) NOT NULL,
  MAP_IMS_FIELDNAME    VARCHAR(40) NOT NULL,
  MAP_IMS_FIELDTYPE    INTEGER,
  MAP_IMS_FORMAT       VARCHAR(40) NOT NULL,
  MAP_IMS_SUFFIX       VARCHAR(40),
  MAP_IMS_PREFIX       VARCHAR(40),
  MAP_IMS_FIND         VARCHAR(40),
  MAP_IMS_REPLACE      VARCHAR(40),
  CREATED_BY           PERSON,
  CREATED_DATE         TIMESTAMP,
  MAP_IMS_DEFAULT      VARCHAR(40),
  MAP_IMS_DATA_ID      CODE_128,
  /* Keys */
  CONSTRAINT RECRD_ID
    PRIMARY KEY (RECORD_ID)
);


SET TERM ^ ;

CREATE TRIGGER ADD_IMPORT_MAP FOR IMPORT_MAP
ACTIVE BEFORE INSERT POSITION 20
AS
BEGIN
   IF (NEW.RECORD_ID IS NULL OR NEW.RECORD_ID = 0) THEN
   BEGIN
      NEW.RECORD_ID = GEN_ID(IMPORT_MAP_ID_GEN,1);
   END

END^

SET TERM ; ^

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON TABLE IMPORT_MAP
TO MINDER WITH GRANT OPTION;
