
SET SQL DIALECT 3; 

/* CREATE DATABASE 'despatch' PAGE_SIZE 4096 DEFAULT CHARACTER SET NONE */


/* Domain definitions */
CREATE DOMAIN FMS_ADDRESS_LINE AS VARCHAR(50);
CREATE DOMAIN FMS_CARRIER_ACCOUNT_NO AS VARCHAR(10);
CREATE DOMAIN FMS_CITY AS VARCHAR(25);
CREATE DOMAIN FMS_CODE_ONE AS CHAR(1);
CREATE DOMAIN FMS_CODE_TWO AS CHAR(2);
CREATE DOMAIN FMS_COUNTRY AS VARCHAR(25);
CREATE DOMAIN FMS_DESCRIPTION AS VARCHAR(50);
CREATE DOMAIN FMS_DESPATCHED_VOL AS NUMERIC(9, 4);
CREATE DOMAIN FMS_DESPATCHED_WEIGHT AS NUMERIC(9, 3);
CREATE DOMAIN FMS_DESPATCH_CARRIER AS VARCHAR(10);
CREATE DOMAIN FMS_DESPATCH_POST_CODE AS VARCHAR(10);
CREATE DOMAIN FMS_EDI_LOCN_NO AS VARCHAR(20);
CREATE DOMAIN FMS_EDI_NO AS VARCHAR(35);
CREATE DOMAIN FMS_EMAIL AS VARCHAR(50);
CREATE DOMAIN FMS_FAX_NO AS VARCHAR(30);
CREATE DOMAIN FMS_FIRST_NAME AS VARCHAR(50);
CREATE DOMAIN FMS_LAST_NAME AS VARCHAR(50);
CREATE DOMAIN FMS_LEGACY_COUNTRY AS VARCHAR(35);
CREATE DOMAIN FMS_MIRROR_DATE AS TIMESTAMP;
CREATE DOMAIN FMS_PHONE_NO AS VARCHAR(30);
CREATE DOMAIN FMS_PICK_ORDER_25 AS VARCHAR(25);
CREATE DOMAIN FMS_POST_CODE AS VARCHAR(10);
CREATE DOMAIN FMS_QTY AS INTEGER;
CREATE DOMAIN FMS_SERVICE_TYPE AS VARCHAR(4);
CREATE DOMAIN FMS_STATE AS VARCHAR(15);
CREATE DOMAIN FMS_STATUS AS CHAR(2);
CREATE DOMAIN FMS_UOM AS VARCHAR(10);
CREATE DOMAIN FMS_WEIGHT AS INTEGER;
CREATE DOMAIN FMS_WEIGHT_DECIMAL3 AS NUMERIC(4, 3);

/* Table: PACK_ID, Owner: SYSDBA */
CREATE TABLE PACK_ID (PACK_ID INTEGER NOT NULL,
        MIRROR_DATA FMS_MIRROR_DATE,
        DESPATCH_ID INTEGER NOT NULL,
        DESPATCH_LABEL_NO VARCHAR(40),
        DIMENSION_X NUMERIC(9, 3),
        DIMENSION_Y NUMERIC(9, 3),
        DIMENSION_Z NUMERIC(9, 3),
        PACK_WEIGHT FMS_WEIGHT_DECIMAL3,
        PACK_STATUS FMS_STATUS,
        DIMENSION_UOM FMS_CODE_TWO,
        VOLUME DOUBLE PRECISION,
        VOLUME_UOM FMS_UOM,
        PACK_WEIGHT_UOM FMS_CODE_TWO,
        PACK_TYPE FMS_CODE_ONE,
        CUBIC_WEIGHT DOUBLE PRECISION,
        CHARGE_WEIGHT NUMERIC(9, 3),
        LAST_UPDATE_DATE TIMESTAMP,
CONSTRAINT PACK_ID_PK PRIMARY KEY (PACK_ID));

/* Table: PICK_DESPATCH, Owner: SYSDBA */
CREATE TABLE PICK_DESPATCH (DESPATCH_ID INTEGER NOT NULL,
        MIRROR_DATA FMS_MIRROR_DATE,
        AWB_CONSIGNMENT_NO VARCHAR(20),
        PICKD_CARRIER_ID FMS_DESPATCH_CARRIER,
        PICKD_SERVICE_TYPE FMS_SERVICE_TYPE,
        PICKD_PICK_ORDER1 FMS_PICK_ORDER_25,
        DESPATCH_STATUS FMS_STATUS,
        PICKD_CHARGE_TO FMS_CODE_ONE,
        SENDER_ACCOUNT FMS_CARRIER_ACCOUNT_NO,
        RECEIVER_ACCOUNT FMS_CARRIER_ACCOUNT_NO,
        PICKD_POST_CODE FMS_DESPATCH_POST_CODE,
        PICKD_SUBURB FMS_DESCRIPTION,
        PICKD_STATE FMS_STATE,
        PICKD_COUNTRY FMS_COUNTRY,
        PICKD_PALLET_QTY FMS_QTY,
        PICKD_CARTON_QTY FMS_QTY,
        PICKD_SATCHEL_QTY FMS_QTY,
        PICKD_WT_CALC FMS_WEIGHT,
        PICKD_WT_ACTUAL FMS_DESPATCHED_WEIGHT,
        PICKD_VOL_ACTUAL FMS_DESPATCHED_VOL,
        SENT_FROM_FIRST_NAME FMS_FIRST_NAME,
        SENT_FROM_LAST_NAME FMS_LAST_NAME,
        SENT_FROM_ADDRESS_1 VARCHAR(100),
        SENT_FROM_ADDRESS_2 FMS_ADDRESS_LINE,
        SENT_FROM_CITY FMS_CITY,
        SENT_FROM_SUBURB FMS_CITY,
        SENT_FROM_STATE FMS_STATE,
        SENT_FROM_POST_CODE FMS_POST_CODE,
        SENT_FROM_COUNTRY FMS_COUNTRY,
        SENT_FROM_EMAIL FMS_EMAIL,
        SENT_FROM_PHONE_NO FMS_PHONE_NO,
        PS_DEL_TO_DC_IN_HOUSE_NO FMS_EDI_LOCN_NO,
        PS_CUSTOMER_EDI_NO FMS_EDI_NO,
        LAST_UPDATE_DATE TIMESTAMP,
CONSTRAINT PICK_DESPATCH_PK PRIMARY KEY (DESPATCH_ID));

/* Table: PICK_ORDER, Owner: SYSDBA */
CREATE TABLE PICK_ORDER (PICK_ORDER VARCHAR(25) NOT NULL,
        MIRROR_DATA FMS_MIRROR_DATE,
        SPECIAL_INSTRUCTIONS1 VARCHAR(8192),
        PICK_STATUS FMS_STATUS,
        CONTACT_NAME VARCHAR(50),
        CUSTOMER_PO_WO VARCHAR(20),
        SHIP_VIA VARCHAR(10),
        SHIP_SERVICE VARCHAR(10),
        D_TITLE VARCHAR(10),
        D_FIRST_NAME FMS_FIRST_NAME,
        D_LAST_NAME FMS_LAST_NAME,
        D_SUBURB FMS_CITY,
        D_CITY FMS_CITY,
        D_STATE FMS_STATE,
        D_POST_CODE FMS_POST_CODE,
        D_COUNTRY FMS_LEGACY_COUNTRY,
        D_PHONE FMS_PHONE_NO,
        D_FAX_NO FMS_FAX_NO,
        D_ADDRESS_LINE1 VARCHAR(100),
        D_ADDRESS_LINE2 FMS_ADDRESS_LINE,
        D_ADDRESS_LINE3 FMS_ADDRESS_LINE,
        D_ADDRESS_LINE4 FMS_ADDRESS_LINE,
        D_ADDRESS_LINE5 FMS_ADDRESS_LINE,
        D_EMAIL FMS_EMAIL,
        S_TITLE VARCHAR(10),
        S_FIRST_NAME FMS_FIRST_NAME,
        S_LAST_NAME FMS_LAST_NAME,
        S_SUBURB FMS_CITY,
        S_CITY FMS_CITY,
        S_STATE FMS_STATE,
        S_POST_CODE FMS_POST_CODE,
        S_COUNTRY FMS_COUNTRY,
        S_PHONE FMS_PHONE_NO,
        S_FAX_NO FMS_FAX_NO,
        S_ADDRESS_LINE1 VARCHAR(100),
        S_ADDRESS_LINE2 FMS_ADDRESS_LINE,
        S_ADDRESS_LINE3 FMS_ADDRESS_LINE,
        S_ADDRESS_LINE4 FMS_ADDRESS_LINE,
        S_ADDRESS_LINE5 FMS_ADDRESS_LINE,
        S_EMAIL FMS_EMAIL,
        LAST_UPDATE_DATE TIMESTAMP,
CONSTRAINT PICK_ORDER_PK PRIMARY KEY (PICK_ORDER));
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER ADD_PACK_ID_TIME FOR PACK_ID 
ACTIVE BEFORE INSERT POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PACK_ID_GO';
END ^

CREATE TRIGGER MOD_PACK_ID_MIRROR FOR PACK_ID 
ACTIVE BEFORE UPDATE POSITION 4 
AS
BEGIN
   IF ( OLD.MIRROR_DATA IS NOT NULL) THEN
   BEGIN
      /* currently mirror data is populated */
      NEW.MIRROR_DATA = NULL;
   END

END ^

CREATE TRIGGER UPDATE_PACK_ID_TIME FOR PACK_ID 
ACTIVE BEFORE UPDATE POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PACK_ID_UP';
END ^

CREATE TRIGGER ADD_PICK_DESPATCH_TIME FOR PICK_DESPATCH 
ACTIVE BEFORE INSERT POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PICK_DESPATCH_GO';
END ^

CREATE TRIGGER MOD_PICK_DESPATCH_MIRROR FOR PICK_DESPATCH 
ACTIVE BEFORE UPDATE POSITION 4 
AS
BEGIN
   IF ( OLD.MIRROR_DATA IS NOT NULL) THEN
   BEGIN
      /* currently mirror data is populated */
      NEW.MIRROR_DATA = NULL;
   END

END ^

CREATE TRIGGER UPDATE_PICK_DESPATCH_TIME FOR PICK_DESPATCH 
ACTIVE BEFORE UPDATE POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PICK_DESPATCH_UP';
END ^

CREATE TRIGGER ADD_PICK_ORDER_TIME FOR PICK_ORDER 
ACTIVE BEFORE INSERT POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PICK_ORDER_GO';
END ^

CREATE TRIGGER MOD_PICK_ORDER_MIRROR FOR PICK_ORDER 
ACTIVE BEFORE UPDATE POSITION 4 
AS
BEGIN
   IF ( OLD.MIRROR_DATA IS NOT NULL) THEN
   BEGIN
      /* currently mirror data is populated */
      NEW.MIRROR_DATA = NULL;
   END

END ^

CREATE TRIGGER UPDATE_PICK_ORDER_TIME FOR PICK_ORDER 
ACTIVE BEFORE UPDATE POSITION 20 
AS
BEGIN
   NEW.LAST_UPDATE_DATE = 'NOW';
   POST_EVENT 'PICK_ORDER_UP';
END ^

COMMIT WORK ^
SET TERM ; ^

/* Grant permissions for this database */
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PACK_ID TO USER DESPATCH;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PACK_ID TO USER MINDER;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PICK_DESPATCH TO USER DESPATCH;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PICK_DESPATCH TO USER MINDER;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PICK_ORDER TO USER DESPATCH;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PICK_ORDER TO USER MINDER;
