
CREATE INDEX ISSN_UPDATE_DATE_IDX ON ISSN(LAST_UPDATE_DATE);
CREATE INDEX SSN_UPDATE_DATE_IDX ON SSN(LAST_UPDATE_DATE);

CREATE INDEX SSN_HIST_TRN_DATE_IDX ON SSN_HIST(TRN_DATE);
CREATE INDEX TRANS_ARCHIVE_TRN_DATE_IDX ON TRANSACTIONS_ARCHIVE(TRN_DATE, DEVICE_ID, TRN_TYPE, TRN_CODE);
