
CREATE INDEX PICK_ORDER_UPDATE_IDX ON PICK_ORDER(LAST_UPDATE_DATE);
CREATE INDEX PICK_ITEM_UPDATE_IDX ON PICK_ITEM(LAST_UPDATE_DATE);

CREATE INDEX PICK_ITEM_LINE_NO_DATE_IDX ON PICK_ITEM_LINE_NO(LAST_UPDATE_DATE);
CREATE INDEX PICK_ITEM_DETAIL_UPDATE_IDX ON PICK_ITEM_DETAIL(LAST_UPDATE_DATE);
