
CREATE INDEX PICK_DESPATCH_UPDATE_IDX ON PICK_DESPATCH(LAST_UPDATE_DATE);
CREATE INDEX PACK_ID_UPDATE_IDX ON PACK_ID(LAST_UPDATE_DATE);

CREATE INDEX LOCATION_UPDATE_DATE_IDX ON LOCATION(LAST_UPDATE_DATE);

CREATE INDEX PICK_ITEM_CANCEL_UPDATE_IDX ON PICK_ITEM_CANCEL(LAST_UPDATE_DATE);


