CREATE TRIGGER UPDATE_ISSN_SSNSTATUS FOR ISSN
ACTIVE AFTER UPDATE POSITION 10 
AS                       

DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_SSN VARCHAR(20);
DECLARE VARIABLE WK_ORIG_SSN VARCHAR(20);
DECLARE VARIABLE WK_STATUS CHAR(2);
DECLARE VARIABLE WK_OLD_STATUS CHAR(2);
DECLARE VARIABLE WK_SSN_STATUS CHAR(2);

BEGIN    
    
    /* Get SSN to update */
   WK_SSN = NEW.SSN_ID;
   WK_ORIG_SSN = NEW.ORIGINAL_SSN;
   IF (WK_ORIG_SSN = WK_SSN) THEN
   BEGIN
      WK_STATUS = NEW.ISSN_STATUS;
      WK_OLD_STATUS = OLD.ISSN_STATUS;
      IF (WK_STATUS <> WK_OLD_STATUS) THEN
      BEGIN
         WK_FOUND = 0;
         SELECT 1, STATUS_SSN
            FROM SSN
            WHERE SSN_ID = :WK_SSN
            INTO :WK_FOUND, :WK_SSN_STATUS;
         IF (WK_FOUND = 1) THEN
         BEGIN
            IF (WK_SSN_STATUS <> WK_STATUS) THEN
            BEGIN
               UPDATE SSN 
                  SET STATUS_SSN = :WK_STATUS
                  WHERE SSN_ID = :WK_SSN;
            END
         END
      END
   END
END^

