COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

CREATE OR ALTER PROCEDURE PC_PI_NOLINE 
AS 
 
  DECLARE VARIABLE WK_PI_ORDER   PICK_ORDER;
  DECLARE VARIABLE WK_PI_LABEL   PICK_LABEL_NO;
  DECLARE VARIABLE WK_PI_LINE_NO PICK_ORDER_LINE_NO;
  DECLARE VARIABLE WK_IS_OK         VARCHAR(1);
  DECLARE VARIABLE WK_IS_PROD_ID    PRODUCT;
  DECLARE VARIABLE WK_ERROR_TEXT ERROR_TEXT;
  DECLARE VARIABLE WK_FILENAME  VARCHAR(80);
  DECLARE VARIABLE WK_RESULT INTEGER;
       
BEGIN
  
   WK_FILENAME = '/tmp/f.pi.noline.log';
   /* check temperature of product versus new location */
   WK_IS_OK = 'T';
   FOR SELECT PICK_LABEL_NO, PICK_ORDER
       FROM PICK_ITEM 
       WHERE PICK_ORDER_LINE_NO = ''
       AND PICK_LINE_STATUS IN ('OP','UP','AL','CN','HD','NF','Al','AS')
       INTO :WK_PI_LABEL, :WK_PI_ORDER
   DO
   BEGIN
           WK_RESULT = FILE_WRITELN(WK_FILENAME, :WK_PI_ORDER); 
           WK_RESULT = FILE_WRITELN(WK_FILENAME, :WK_PI_LABEL); 
      SELECT PICK_ORDER_LINE_NO
      FROM GET_SALE_LINES_NO(:WK_PI_ORDER)
      INTO :WK_PI_LINE_NO;
           WK_RESULT = FILE_WRITELN(WK_FILENAME, :WK_PI_LINE_NO); 
      UPDATE PICK_ITEM SET PICK_ORDER_LINE_NO = :WK_PI_LINE_NO WHERE PICK_LABEL_NO = :WK_PI_LABEL;
   END
END  ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
