DROP TRIGGER INSERT_COST_CENTRE ^
COMMIT^

CREATE TRIGGER INSERT_COST_CENTRE FOR COST_CENTRE
ACTIVE AFTER  INSERT POSITION 10 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DESC VARCHAR(50);

DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(250);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_QUOTE CHAR(1);
BEGIN
   WK_QUOTE = chr(39);
   WK_CODE = NEW.CODE;
   WK_DESC = NEW.DESCRIPTION;

   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'newcost.trn';
   WK_LABEL_LINE = WK_QUOTE || WK_CODE || WK_QUOTE || ',' ||
   WK_QUOTE || WK_DESC || WK_QUOTE  ;

   WK_RESULT = FILE_WRITE(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'newcost.2rn';
      WK_RESULT = FILE_WRITE(WK_FILENAME, WK_LABEL_LINE);
   END

END^

DROP TRIGGER UPDATE_COST_CENTRE ^
COMMIT^

CREATE TRIGGER UPDATE_COST_CENTRE FOR COST_CENTRE
ACTIVE AFTER  UPDATE POSITION 10 
AS
DECLARE VARIABLE WK_CODE VARCHAR(40);
DECLARE VARIABLE WK_DESC VARCHAR(50);

DECLARE VARIABLE WK_DIRECTORY VARCHAR(80);
DECLARE VARIABLE WK_FILENAME VARCHAR(255);
DECLARE VARIABLE WK_LABEL_LINE VARCHAR(250);
DECLARE VARIABLE WK_RESULT INTEGER;
DECLARE VARIABLE WK_QUOTE CHAR(1);

BEGIN
   WK_QUOTE = chr(39);
   WK_CODE = NEW.CODE;
   WK_DESC = NEW.DESCRIPTION;

   SELECT EMPLOYEE_FTP_DIRECTORY FROM CONTROL INTO :WK_DIRECTORY;
   WK_FILENAME = WK_DIRECTORY || 'updcost.trn';
   WK_LABEL_LINE = WK_QUOTE || WK_CODE || WK_QUOTE || ',' ||
   WK_QUOTE || WK_DESC || WK_QUOTE ;

   WK_RESULT = FILE_WRITE(WK_FILENAME, WK_LABEL_LINE);
   IF (WK_RESULT <> 0) THEN
   BEGIN
      WK_FILENAME = WK_DIRECTORY || 'updcost.2rn';
      WK_RESULT = FILE_WRITE(WK_FILENAME, WK_LABEL_LINE);
   END


END^

