ALTER TABLE PERSON ADD
MAIL_PHONE PHONE_NO;
ALTER TABLE PERSON ADD
CONTACT_ADDRESS1 ADDRESS_LINE;
ALTER TABLE PERSON ADD
CONTACT_ADDRESS2 ADDRESS_LINE;
ALTER TABLE PERSON ADD
CONTACT_CITY CITY;
ALTER TABLE PERSON ADD
CONTACT_STATE STATE;
ALTER TABLE PERSON ADD
CONTACT_POST_CODE POST_CODE;
ALTER TABLE PERSON ADD
CONTACT_PHONE PHONE_NO;
ALTER TABLE PERSON ADD
CREATE_BY PERSON;

ALTER TABLE PERSON ADD
CONTACT_COUNTRY COUNTRY;
