/* change first_name to be varchar 255 */
DROP   VIEW PERSON_SUBTYPE ;
DROP TRIGGER ADD_PICK_FROM_TEMP ;
DROP TRIGGER ADD_PURCHASE_FROM_TEMP ;
DROP TRIGGER RUN_TRANSACTION_EIND ;
DROP TRIGGER INSERT_PERSON ;
DROP TRIGGER UPDATE_PERSON ;
COMMIT WORK;
ALTER TABLE PERSON ADD SAVE_FIRST_NAME VARCHAR(255);
COMMIT;
UPDATE  PERSON SET SAVE_FIRST_NAME=FIRST_NAME;
COMMIT;
ALTER TABLE PERSON DROP FIRST_NAME;
COMMIT;
ALTER TABLE PERSON ADD FIRST_NAME VARCHAR(255);
COMMIT;
UPDATE PERSON SET FIRST_NAME = SAVE_FIRST_NAME;
COMMIT;

CREATE VIEW PERSON_SUBTYPE (PERSON_ID, PERSON_TYPE, FIRST_NAME) AS
SELECT person_id, person_type, first_name FROM person WHERE person_type in ('LE');
COMMIT WORK;
ALTER TABLE PERSON DROP SAVE_FIRST_NAME;

SET TERM ^;

 
CREATE TRIGGER ADD_PICK_FROM_TEMP FOR PICK_ORDER_ITEM_TEMP 
ACTIVE BEFORE INSERT POSITION 0 
AS
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_H_PERSON_ID VARCHAR(10); 
DECLARE VARIABLE WK_P_PERSON_TYPE CHAR(2);
DECLARE VARIABLE WK_P_FIRST_NAME VARCHAR(50); 
DECLARE VARIABLE WK_P_LAST_NAME VARCHAR(50); 
DECLARE VARIABLE WK_P_ADDRESS_LINE1 VARCHAR(50); 
DECLARE VARIABLE WK_P_ADDRESS_LINE2 VARCHAR(50); 
DECLARE VARIABLE WK_P_CITY VARCHAR(25); 
DECLARE VARIABLE WK_P_STATE VARCHAR(15); 
DECLARE VARIABLE WK_P_POST_CODE VARCHAR(10); 
DECLARE VARIABLE WK_P_COUNTRY VARCHAR(25);

DECLARE VARIABLE WK_H_PICK_ORDER  VARCHAR(15);
DECLARE VARIABLE WK_H_PICK_ORDER_TYPE  CHAR(2);
DECLARE VARIABLE WK_H_CONTACT_NAME  VARCHAR(50);
DECLARE VARIABLE WK_H_CUSTOMER_PO_WO  VARCHAR(20);
DECLARE VARIABLE WK_H_COST_CENTER  VARCHAR(40);
DECLARE VARIABLE WK_H_COMPANY_ID  VARCHAR(20);
DECLARE VARIABLE WK_H_DIVISION_ID  VARCHAR(20);
DECLARE VARIABLE WK_H_PICK_PRIORITY  SMALLINT;
DECLARE VARIABLE WK_H_DELIVERY_RUN_NO  VARCHAR(10);
DECLARE VARIABLE WK_H_PICK_DUE_DATE  TIMESTAMP;
DECLARE VARIABLE WK_H_SPECIAL_INSTRUCTIONS1  VARCHAR(255);
DECLARE VARIABLE WK_H_SPECIAL_INSTRUCTIONS2  VARCHAR(255);
DECLARE VARIABLE WK_H_INV_WITH_GOODS  CHAR(1);
DECLARE VARIABLE WK_H_SHIP_VIA  VARCHAR(10);
DECLARE VARIABLE WK_H_DESPATCH_LOCATION  VARCHAR(10);
DECLARE VARIABLE WK_H_CREATE_DATE  TIMESTAMP;
DECLARE VARIABLE WK_H_CREATED_BY  VARCHAR(10);
DECLARE VARIABLE WK_H_PICK_STARTED  TIMESTAMP;
DECLARE VARIABLE WK_H_PICK_STATUS  CHAR(2);
DECLARE VARIABLE WK_H_PARTIAL_PICK_ALLOWED  CHAR(1);

DECLARE VARIABLE WK_L_PICK_LABEL_NO  VARCHAR(7);
DECLARE VARIABLE WK_L_PICK_ORDER  VARCHAR(15);
DECLARE VARIABLE WK_L_PICK_ORDER_LINE_NO  CHAR(4);
DECLARE VARIABLE WK_L_CONTACT_NAME  VARCHAR(50);
DECLARE VARIABLE WK_L_PROD_ID  VARCHAR(30);
DECLARE VARIABLE WK_L_SSN_ID  VARCHAR(20);
DECLARE VARIABLE WK_L_WARRANTY_TERM  VARCHAR(50);
DECLARE VARIABLE WK_L_PICK_LABEL_DATE  TIMESTAMP;
DECLARE VARIABLE WK_L_SPECIAL_INSTRUCTIONS1  VARCHAR(255);
DECLARE VARIABLE WK_L_SPECIAL_INSTRUCTIONS2  VARCHAR(255);
DECLARE VARIABLE WK_L_SHIP_VIA  VARCHAR(10);
DECLARE VARIABLE WK_L_PICK_ORDER_QTY  INTEGER;
DECLARE VARIABLE WK_L_PICK_ALLOCATED_QTY  INTEGER;
DECLARE VARIABLE WK_L_PICKED_QTY  INTEGER;
DECLARE VARIABLE WK_L_PICK_LINE_DUE_DATE  TIMESTAMP;
DECLARE VARIABLE WK_L_PICK_STARTED  TIMESTAMP;
DECLARE VARIABLE WK_L_DESPATCH_TS  TIMESTAMP;
DECLARE VARIABLE WK_L_DESPATCH_LOCATION  VARCHAR(10);
DECLARE VARIABLE WK_L_CREATE_DATE  TIMESTAMP;
DECLARE VARIABLE WK_L_USER_ID  VARCHAR(10);
DECLARE VARIABLE WK_L_DEVICE_ID  CHAR(2);
DECLARE VARIABLE WK_L_CHECKIN_START  TIMESTAMP;
DECLARE VARIABLE WK_L_CHECKIN_FINISH  TIMESTAMP;
DECLARE VARIABLE WK_L_CHECKIN_USER_ID  VARCHAR(10);
DECLARE VARIABLE WK_L_PICK_LINE_STATUS  CHAR(2);
DECLARE VARIABLE WK_L_PARTIAL_PICK_ALLOWED  CHAR(1);
DECLARE VARIABLE WK_L_SALE_PRICE  NUMERIC(9,3);
DECLARE VARIABLE WK_PICK_LABEL_NO CHAR(8);
DECLARE VARIABLE WK_PICK_LABEL_START INTEGER;
DECLARE VARIABLE WK_PICK_LABEL_STOP INTEGER;
DECLARE VARIABLE WK_PICK_LABEL_PREFIX INTEGER;
DECLARE VARIABLE WK_LEN_LABEL_NO INTEGER;
DECLARE VARIABLE WK_LABEL_LENGTH INTEGER;
DECLARE VARIABLE WK_PICK_ADJUSTMENT INTEGER;
DECLARE VARIABLE WK_PROD_LENGTH INTEGER;
DECLARE VARIABLE WK_L_WH_ID CHAR(2);
DECLARE VARIABLE WK_L_LOCN_ID VARCHAR(10);
DECLARE VARIABLE WK_CURRENT_STATUS  CHAR(2);
DECLARE VARIABLE WK_CURRENT_LINE_DUE_DATE  TIMESTAMP;
DECLARE VARIABLE WK_PICK_STATUS  CHAR(2);
DECLARE VARIABLE WK_PI_STATUS  CHAR(2);
DECLARE VARIABLE WK_DOITEM  CHAR(1);
DECLARE VARIABLE WK_PICK_SSN_ALLOWED VARCHAR(40);
DECLARE VARIABLE WK_TEST_STATUS VARCHAR(4);
BEGIN
   WK_H_PERSON_ID  = NEW.H_PERSON_ID;
   WK_P_PERSON_TYPE = NEW.P_PERSON_TYPE;
   WK_P_FIRST_NAME = NEW.P_FIRST_NAME;
   WK_P_LAST_NAME = NEW.P_LAST_NAME;
   WK_P_ADDRESS_LINE1 = NEW.P_ADDRESS_LINE1;
   WK_P_ADDRESS_LINE2 = NEW.P_ADDRESS_LINE2;
   WK_P_CITY = NEW.P_CITY;
   WK_P_STATE = NEW.P_STATE;
   WK_P_POST_CODE = NEW.P_POST_CODE;
   WK_P_COUNTRY = NEW.P_COUNTRY;

   WK_H_PICK_ORDER = NEW.H_PICK_ORDER;
   WK_H_PICK_ORDER_TYPE = NEW.H_PICK_ORDER_TYPE;
   WK_H_CONTACT_NAME = NEW.H_CONTACT_NAME;
   WK_H_CUSTOMER_PO_WO = NEW.H_CUSTOMER_PO_WO;
   WK_H_COST_CENTER = NEW.H_COST_CENTER;
   WK_H_COMPANY_ID = NEW.H_COMPANY_ID;
   WK_H_DIVISION_ID = NEW.H_DIVISION_ID;
   WK_H_PICK_PRIORITY = NEW.H_PICK_PRIORITY;
   WK_H_DELIVERY_RUN_NO = NEW.H_DELIVERY_RUN_NO;
   WK_H_PICK_DUE_DATE = NEW.H_PICK_DUE_DATE;
   WK_H_SPECIAL_INSTRUCTIONS1 = NEW.H_SPECIAL_INSTRUCTIONS1;
   WK_H_SPECIAL_INSTRUCTIONS2 = NEW.H_SPECIAL_INSTRUCTIONS2;
   WK_H_INV_WITH_GOODS = NEW.H_INV_WITH_GOODS;
   WK_H_SHIP_VIA = NEW.H_SHIP_VIA;
   WK_H_DESPATCH_LOCATION = NEW.H_DESPATCH_LOCATION;
   WK_H_CREATE_DATE = NEW.H_CREATE_DATE;
   WK_H_CREATED_BY = NEW.H_CREATED_BY;
   WK_H_PICK_STARTED = NEW.H_PICK_STARTED;
   WK_H_PICK_STATUS = NEW.H_PICK_STATUS;
   WK_H_PARTIAL_PICK_ALLOWED = NEW.H_PARTIAL_PICK_ALLOWED;
   WK_L_PICK_LABEL_NO = 'NULL' ;
   WK_L_PICK_ORDER = NEW.H_PICK_ORDER ;
   WK_L_PICK_ORDER_LINE_NO = NEW.L_PICK_ORDER_LINE_NO ;
   WK_L_CONTACT_NAME = NEW.L_CONTACT_NAME ;
   WK_L_PROD_ID = NEW.L_PROD_ID ;
   WK_L_SSN_ID = NEW.L_SSN_ID ;
   WK_L_WARRANTY_TERM = NEW.L_WARRANTY_TERM ;
   WK_L_PICK_LABEL_DATE = NEW.L_PICK_LABEL_DATE ;
   WK_L_SPECIAL_INSTRUCTIONS1 = NEW.L_SPECIAL_INSTRUCTIONS1 ;
   WK_L_SPECIAL_INSTRUCTIONS2 = NEW.L_SPECIAL_INSTRUCTIONS2 ;
   WK_L_SHIP_VIA = NEW.L_SHIP_VIA ;
   WK_L_PICK_ORDER_QTY = NEW.L_PICK_ORDER_QTY ;
   WK_L_PICK_ALLOCATED_QTY = NEW.L_PICK_ALLOCATED_QTY ;
   WK_L_PICKED_QTY = NEW.L_PICKED_QTY ;
   WK_L_PICK_LINE_DUE_DATE = NEW.L_PICK_LINE_DUE_DATE ;
   WK_L_PICK_STARTED = NEW.L_PICK_STARTED ;
   WK_L_DESPATCH_TS = NEW.L_DESPATCH_TS ;
   WK_L_DESPATCH_LOCATION = NEW.L_DESPATCH_LOCATION ;
   WK_L_CREATE_DATE = NEW.L_CREATE_DATE ;
   WK_L_USER_ID = NEW.L_USER_ID ;
   WK_L_DEVICE_ID = NEW.L_DEVICE_ID ;
   WK_L_CHECKIN_START = NEW.L_CHECKIN_START ;
   WK_L_CHECKIN_FINISH = NEW.L_CHECKIN_FINISH ;
   WK_L_CHECKIN_USER_ID = NEW.L_CHECKIN_USER_ID ;
   IF (NEW.L_PICK_LINE_STATUS IS NULL) THEN
   BEGIN
      WK_L_PICK_LINE_STATUS = 'OP' ;
   END
   ELSE
   BEGIN
      WK_L_PICK_LINE_STATUS = NEW.L_PICK_LINE_STATUS ; 
   END
   WK_L_PARTIAL_PICK_ALLOWED = NEW.L_PARTIAL_PICK_ALLOWED ;
   WK_L_SALE_PRICE = NEW.L_SALE_PRICE ;
   WK_DOITEM = '0'   ;
   /* Check person */
   WK_FOUND = 0;
   SELECT 1 FROM PERSON 
      WHERE PERSON_ID = :WK_H_PERSON_ID
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no person so insert it */
      INSERT INTO PERSON (PERSON_ID, PERSON_TYPE, FIRST_NAME, LAST_NAME, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, POST_CODE, COUNTRY)
      VALUES (:WK_H_PERSON_ID, :WK_P_PERSON_TYPE, :WK_P_FIRST_NAME, :WK_P_LAST_NAME, :WK_P_ADDRESS_LINE1, :WK_P_ADDRESS_LINE2, :WK_P_CITY, :WK_P_STATE, :WK_P_POST_CODE, :WK_P_COUNTRY);
   END
   ELSE
   BEGIN
      UPDATE PERSON  SET PERSON_TYPE = :WK_P_PERSON_TYPE, 
         FIRST_NAME = :WK_P_FIRST_NAME, 
         LAST_NAME = :WK_P_LAST_NAME, 
         ADDRESS_LINE1 = :WK_P_ADDRESS_LINE1, 
         ADDRESS_LINE2 = :WK_P_ADDRESS_LINE2, 
         CITY = :WK_P_CITY, 
         STATE = :WK_P_STATE, 
         POST_CODE = :WK_P_POST_CODE, 
         COUNTRY = :WK_P_COUNTRY 
       WHERE PERSON_ID = :WK_H_PERSON_ID;
   END
   /* Check pick_order */
   WK_FOUND = 0;
   SELECT 1 FROM PICK_ORDER
      WHERE PICK_ORDER = :WK_H_PICK_ORDER
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no order so insert it */
      INSERT INTO PICK_ORDER (
 PICK_ORDER ,
        PICK_ORDER_TYPE ,
        PERSON_ID ,
        CONTACT_NAME ,
        CUSTOMER_PO_WO ,
        COST_CENTER ,
        COMPANY_ID ,
        DIVISION_ID ,
        PICK_PRIORITY ,
        DELIVERY_RUN_NO ,
        PICK_DUE_DATE ,
        SPECIAL_INSTRUCTIONS1 ,
        SPECIAL_INSTRUCTIONS2 ,
        INV_WITH_GOODS ,
        SHIP_VIA ,
        DESPATCH_LOCATION ,
        CREATE_DATE ,
        CREATED_BY ,
        PICK_STARTED ,
        PICK_STATUS ,
        PARTIAL_PICK_ALLOWED )
      VALUES (
 :WK_H_PICK_ORDER ,
        :WK_H_PICK_ORDER_TYPE ,
        :WK_H_PERSON_ID ,
        :WK_H_CONTACT_NAME ,
        :WK_H_CUSTOMER_PO_WO ,
        :WK_H_COST_CENTER ,
        :WK_H_COMPANY_ID ,
        :WK_H_DIVISION_ID ,
        :WK_H_PICK_PRIORITY ,
        :WK_H_DELIVERY_RUN_NO ,
        :WK_H_PICK_DUE_DATE ,
        :WK_H_SPECIAL_INSTRUCTIONS1 ,
        :WK_H_SPECIAL_INSTRUCTIONS2 ,
        :WK_H_INV_WITH_GOODS ,
        :WK_H_SHIP_VIA ,
        :WK_H_DESPATCH_LOCATION ,
        :WK_H_CREATE_DATE ,
        :WK_H_CREATED_BY ,
        :WK_H_PICK_STARTED ,
        :WK_H_PICK_STATUS ,
        :WK_H_PARTIAL_PICK_ALLOWED );
   END
   ELSE
   BEGIN
      UPDATE PICK_ORDER SET 
        PICK_ORDER_TYPE = :WK_H_PICK_ORDER_TYPE ,
        PERSON_ID = :WK_H_PERSON_ID ,
        CONTACT_NAME = :WK_H_CONTACT_NAME ,
        CUSTOMER_PO_WO = :WK_H_CUSTOMER_PO_WO ,
        COST_CENTER = :WK_H_COST_CENTER ,
        COMPANY_ID = :WK_H_COMPANY_ID ,
        DIVISION_ID = :WK_H_DIVISION_ID ,
        PICK_PRIORITY = :WK_H_PICK_PRIORITY ,
        DELIVERY_RUN_NO = :WK_H_DELIVERY_RUN_NO ,
        PICK_DUE_DATE = :WK_H_PICK_DUE_DATE ,
        SPECIAL_INSTRUCTIONS1 = :WK_H_SPECIAL_INSTRUCTIONS1 ,
        SPECIAL_INSTRUCTIONS2 = :WK_H_SPECIAL_INSTRUCTIONS2 ,
        INV_WITH_GOODS = :WK_H_INV_WITH_GOODS ,
        SHIP_VIA = :WK_H_SHIP_VIA ,
        DESPATCH_LOCATION = :WK_H_DESPATCH_LOCATION ,
        CREATE_DATE = :WK_H_CREATE_DATE ,
        CREATED_BY = :WK_H_CREATED_BY ,
        PICK_STARTED = :WK_H_PICK_STARTED ,
        PICK_STATUS = :WK_H_PICK_STATUS ,
        PARTIAL_PICK_ALLOWED = :WK_H_PARTIAL_PICK_ALLOWED 
 WHERE PICK_ORDER = :WK_H_PICK_ORDER;
   END
   /* Check pick_item */
  WK_FOUND = 0;
  SELECT 1, PICK_LABEL_NO, PICK_LINE_STATUS
      FROM PICK_ITEM
      WHERE PICK_ORDER = :WK_H_PICK_ORDER 
        AND PICK_ORDER_LINE_NO = :WK_L_PICK_ORDER_LINE_NO
      INTO :WK_FOUND, :WK_L_PICK_LABEL_NO, :WK_PICK_STATUS;
  IF (WK_FOUND = 0) THEN
  BEGIN
     WK_L_PICK_LABEL_NO = 'NULL';
     WK_PICK_STATUS = 'OP';
  END
  IF (WK_L_PICK_LABEL_NO = 'NULL') THEN
  BEGIN
     /* Get length for label */   
     SELECT MAX_LENGTH
     FROM PARAM
     WHERE DATA_ID = 'PICK'
     INTO :WK_LABEL_LENGTH;
     WK_PICK_LABEL_NO = GEN_ID(PICK_LABEL_GEN, 1);
     WK_PICK_LABEL_START = GEN_ID(PICK_LABEL_START, 0);
     WK_PICK_LABEL_STOP = GEN_ID(PICK_LABEL_STOP, 0);
     WK_PICK_LABEL_PREFIX = GEN_ID(PICK_LABEL_PREFIX , 0);
     IF (WK_PICK_LABEL_NO > WK_PICK_LABEL_STOP) THEN
     BEGIN
  WK_PICK_ADJUSTMENT = WK_PICK_LABEL_START - WK_PICK_LABEL_STOP;
        WK_PICK_LABEL_NO = GEN_ID(PICK_LABEL_GEN, WK_PICK_ADJUSTMENT);
        WK_PICK_LABEL_PREFIX = GEN_ID(PICK_LABEL_PREFIX , 1);
        WK_PICK_LABEL_NO = WK_PICK_LABEL_START;
     END
     WK_LEN_LABEL_NO = STRLEN(ALLTRIM(WK_PICK_LABEL_NO)) + 1;     
     /* Get Label prefix */      
     WK_L_PICK_LABEL_NO = chr(WK_PICK_LABEL_PREFIX);
     /* Padding leading with 0 */
     WHILE (WK_LEN_LABEL_NO < WK_LABEL_LENGTH) DO
     BEGIN
        WK_L_PICK_LABEL_NO = WK_L_PICK_LABEL_NO || '0';      
        WK_LEN_LABEL_NO = WK_LEN_LABEL_NO + 1;
     END
     WK_L_PICK_LABEL_NO = WK_L_PICK_LABEL_NO || ALLTRIM(WK_PICK_LABEL_NO);
     SELECT PICK_IMPORT_SSN_STATUS FROM CONTROL INTO :WK_PICK_SSN_ALLOWED ; 
     IF (NEW.L_SSN_ID IS NULL) THEN
     BEGIN
        /* a null */
        WK_FOUND = 2;
     END
     ELSE
     BEGIN
        IF (WK_L_SSN_ID > '') THEN
        BEGIN
           SELECT ISSN_STATUS FROM ISSN
              WHERE SSN_ID = :WK_L_SSN_ID
              INTO :WK_PI_STATUS;
           WK_TEST_STATUS = ',' || WK_PI_STATUS || ',';
           IF (POS(WK_PICK_SSN_ALLOWED , WK_TEST_STATUS,0,1) = -1) THEN
           BEGIN
              WK_L_PICK_LINE_STATUS = 'NP';
           END
        END
     END
  END
  IF (WK_PICK_STATUS = 'OP') THEN
  BEGIN
      WK_DOITEM = '1';
  END
  IF (WK_PICK_STATUS = 'CN') THEN
  BEGIN
      WK_DOITEM = '1';
  END
  IF (WK_PICK_STATUS = 'HD') THEN
  BEGIN
      WK_DOITEM = '1';
  END

  IF (WK_DOITEM = '1') THEN
  BEGIN
      WK_L_WH_ID = '';
      WK_L_LOCN_ID = '';
       /* Check ssn */
       IF (NEW.L_SSN_ID IS NULL) THEN
       BEGIN
          /* a null */
          WK_FOUND = 2;
       END
       ELSE
       BEGIN
          IF (WK_L_SSN_ID > '') THEN
          BEGIN
             IF (WK_L_PICK_LINE_STATUS <> 'NP') THEN
             BEGIN
                SELECT WH_ID, LOCN_ID FROM ISSN
                   WHERE SSN_ID = :WK_L_SSN_ID
                   INTO :WK_L_WH_ID, :WK_L_LOCN_ID;
                UPDATE ISSN SET ISSN_STATUS = 'RS'
                   WHERE SSN_ID = :WK_L_SSN_ID;
             END
          END
       END
    
       /* Get length for product */   
       IF (NEW.L_PROD_ID IS NULL) THEN
       BEGIN
          /* a null */
          WK_FOUND = 2;
       END
       ELSE
       BEGIN
          IF (WK_L_PROD_ID > '') THEN
          BEGIN
             SELECT MAX_LENGTH
             FROM PARAM
             WHERE DATA_ID = 'PROD_INTERNAL'
             INTO :WK_PROD_LENGTH;
             WK_L_PROD_ID = ALLTRIM(WK_L_PROD_ID) ;     
             WK_LEN_LABEL_NO = STRLEN(WK_L_PROD_ID) ;     
             /* Padding leading with 0 */
             WHILE (WK_LEN_LABEL_NO < :WK_PROD_LENGTH) DO
             BEGIN
                WK_L_PROD_ID = '0' || WK_L_PROD_ID ;      
                WK_LEN_LABEL_NO = WK_LEN_LABEL_NO + 1;
             END
             IF (WK_L_WH_ID = '') THEN
             BEGIN
                SELECT FIRST 1 WH_ID, LOCN_ID FROM ISSN
                   WHERE PROD_ID = :WK_L_PROD_ID
                     AND WH_ID <> 'XX'
                   INTO :WK_L_WH_ID, :WK_L_LOCN_ID;
             END
          END
       END
    
       WK_FOUND = 0;
       WK_CURRENT_STATUS = '';
       SELECT 1, PICK_LINE_STATUS, PICK_LINE_DUE_DATE 
          FROM PICK_ITEM
          WHERE PICK_LABEL_NO = :WK_L_PICK_LABEL_NO 
          INTO :WK_FOUND, :WK_CURRENT_STATUS, :WK_CURRENT_LINE_DUE_DATE;
       IF (WK_FOUND = 0) THEN
       BEGIN
          IF (NEW.L_PICK_LINE_STATUS IS NULL) THEN
          BEGIN
             WK_L_PICK_LINE_STATUS = 'OP' ;
          END
          IF (NEW.L_PICK_LINE_DUE_DATE IS NULL) THEN
          BEGIN
             WK_L_PICK_LINE_DUE_DATE = WK_H_PICK_DUE_DATE ;
          END
          /* no line so insert it */
          INSERT INTO PICK_ITEM (
            PICK_LABEL_NO ,
            PICK_ORDER ,
            PICK_ORDER_LINE_NO ,
            CONTACT_NAME ,
            PROD_ID ,
            SSN_ID ,
            WARRANTY_TERM ,
            PICK_LABEL_DATE ,
            SPECIAL_INSTRUCTIONS1 ,
            SPECIAL_INSTRUCTIONS2 ,
            SHIP_VIA ,
            PICK_ORDER_QTY ,
            PICK_ALLOCATED_QTY ,
            PICKED_QTY ,
            PICK_LINE_DUE_DATE ,
            PICK_STARTED ,
            DESPATCH_TS ,
            DESPATCH_LOCATION ,
            CREATE_DATE ,
            USER_ID ,
            DEVICE_ID ,
            CHECKIN_START ,
            CHECKIN_FINISH ,
            CHECKIN_USER_ID ,
            PICK_LINE_STATUS ,
            PARTIAL_PICK_ALLOWED,
            WH_ID,
            PICK_LOCATION,
            SALE_PRICE )
          VALUES (
            :WK_L_PICK_LABEL_NO ,
            :WK_L_PICK_ORDER ,
            :WK_L_PICK_ORDER_LINE_NO ,
            :WK_L_CONTACT_NAME ,
            :WK_L_PROD_ID ,
            :WK_L_SSN_ID ,
            :WK_L_WARRANTY_TERM ,
            :WK_L_PICK_LABEL_DATE ,
            :WK_L_SPECIAL_INSTRUCTIONS1 ,
            :WK_L_SPECIAL_INSTRUCTIONS2 ,
            :WK_L_SHIP_VIA ,
            :WK_L_PICK_ORDER_QTY ,
            :WK_L_PICK_ALLOCATED_QTY ,
            :WK_L_PICKED_QTY ,
            :WK_L_PICK_LINE_DUE_DATE ,
            :WK_L_PICK_STARTED ,
            :WK_L_DESPATCH_TS ,
            :WK_L_DESPATCH_LOCATION ,
            :WK_L_CREATE_DATE ,
            :WK_L_USER_ID ,
            :WK_L_DEVICE_ID ,
            :WK_L_CHECKIN_START ,
            :WK_L_CHECKIN_FINISH ,
            :WK_L_CHECKIN_USER_ID ,
            :WK_L_PICK_LINE_STATUS ,
            :WK_L_PARTIAL_PICK_ALLOWED,
            :WK_L_WH_ID,
            :WK_L_LOCN_ID ,
            :WK_L_SALE_PRICE );
       END
       ELSE
          BEGIN
             IF (NEW.L_PICK_LINE_STATUS IS NULL) THEN
             BEGIN
                WK_L_PICK_LINE_STATUS = WK_CURRENT_STATUS ;
             END
             IF (NEW.L_PICK_LINE_DUE_DATE IS NULL) THEN
             BEGIN
                WK_L_PICK_LINE_DUE_DATE = WK_CURRENT_LINE_DUE_DATE ;
             END
             UPDATE PICK_ITEM SET 
               PICK_ORDER = :WK_L_PICK_ORDER ,
               PICK_ORDER_LINE_NO = :WK_L_PICK_ORDER_LINE_NO ,
               CONTACT_NAME = :WK_L_CONTACT_NAME ,
               PROD_ID = :WK_L_PROD_ID ,
               SSN_ID = :WK_L_SSN_ID ,
               WARRANTY_TERM = :WK_L_WARRANTY_TERM ,
               PICK_LABEL_DATE = :WK_L_PICK_LABEL_DATE ,
               SPECIAL_INSTRUCTIONS1 = :WK_L_SPECIAL_INSTRUCTIONS1 ,
               SPECIAL_INSTRUCTIONS2 = :WK_L_SPECIAL_INSTRUCTIONS2 ,
               SHIP_VIA = :WK_L_SHIP_VIA ,
               PICK_ORDER_QTY = :WK_L_PICK_ORDER_QTY ,
               PICK_ALLOCATED_QTY = :WK_L_PICK_ALLOCATED_QTY ,
               PICKED_QTY = :WK_L_PICKED_QTY ,
               PICK_LINE_DUE_DATE = :WK_L_PICK_LINE_DUE_DATE ,
               PICK_STARTED = :WK_L_PICK_STARTED ,
               DESPATCH_TS = :WK_L_DESPATCH_TS ,
               DESPATCH_LOCATION = :WK_L_DESPATCH_LOCATION ,
               CREATE_DATE = :WK_L_CREATE_DATE ,
               USER_ID = :WK_L_USER_ID ,
               DEVICE_ID = :WK_L_DEVICE_ID ,
               CHECKIN_START = :WK_L_CHECKIN_START ,
               CHECKIN_FINISH = :WK_L_CHECKIN_FINISH ,
               CHECKIN_USER_ID = :WK_L_CHECKIN_USER_ID ,
               PICK_LINE_STATUS = :WK_L_PICK_LINE_STATUS ,
               PARTIAL_PICK_ALLOWED = :WK_L_PARTIAL_PICK_ALLOWED ,
               WH_ID = :WK_L_WH_ID,
               PICK_LOCATION = :WK_L_LOCN_ID,
               SALE_PRICE = :WK_L_SALE_PRICE
               WHERE PICK_LABEL_NO = :WK_L_PICK_LABEL_NO ;
          END
   END
END ^
 
CREATE TRIGGER ADD_PURCHASE_FROM_TEMP FOR PURCHASE_ORDER_LINE_TEMP 
ACTIVE BEFORE INSERT POSITION 0 
AS
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_H_PERSON_ID VARCHAR(10); 
DECLARE VARIABLE WK_P_PERSON_TYPE CHAR(2);
DECLARE VARIABLE WK_P_FIRST_NAME VARCHAR(50); 
DECLARE VARIABLE WK_P_LAST_NAME VARCHAR(50); 
DECLARE VARIABLE WK_P_ADDRESS_LINE1 VARCHAR(50); 
DECLARE VARIABLE WK_P_ADDRESS_LINE2 VARCHAR(50); 
DECLARE VARIABLE WK_P_CITY VARCHAR(25); 
DECLARE VARIABLE WK_P_STATE VARCHAR(15); 
DECLARE VARIABLE WK_P_POST_CODE VARCHAR(10); 
DECLARE VARIABLE WK_P_COUNTRY VARCHAR(25);

DECLARE VARIABLE WK_H_PURCHASE_ORDER VARCHAR(10);
DECLARE VARIABLE WK_H_REQUISITION_NO VARCHAR(10) ; 
DECLARE VARIABLE WK_H_PO_DATE        TIMESTAMP ; 
DECLARE VARIABLE WK_H_PO_REVISION_NO CHAR(2) ; 
DECLARE VARIABLE WK_H_PO_STATUS      CHAR(2) ; 
DECLARE VARIABLE WK_H_COMMENTS       VARCHAR(255) ; 
DECLARE VARIABLE WK_H_PO_PRINTED     TIMESTAMP ; 
DECLARE VARIABLE WK_H_USER_ID        VARCHAR(10) ; 
DECLARE VARIABLE WK_H_COMPANY_ID  VARCHAR(20);
DECLARE VARIABLE WK_H_DIVISION_ID  VARCHAR(20);

DECLARE VARIABLE WK_L_PURCHASE_ORDER  VARCHAR(10);
DECLARE VARIABLE WK_L_PO_LINE         CHAR(4);
DECLARE VARIABLE WK_L_REQUISITION_NO  VARCHAR(10) ; 
DECLARE VARIABLE WK_L_PROD_ID         VARCHAR(30) ; 
DECLARE VARIABLE WK_L_PO_LINE_QTY     INTEGER ; 
DECLARE VARIABLE WK_L_UNIT_PRICE      NUMERIC(9, 3) ; 
DECLARE VARIABLE WK_L_UOM_ORDER       CHAR(2) ; 
DECLARE VARIABLE WK_L_PO_LINE_DUE_DATE TIMESTAMP ; 
DECLARE VARIABLE WK_L_PO_LINE_STATUS  CHAR(2) ; 
DECLARE VARIABLE WK_L_COMMENTS        VARCHAR(255) ; 
DECLARE VARIABLE WK_L_GST_VALUE       INTEGER ; 
DECLARE VARIABLE WK_L_GST_RATE        INTEGER ; 
DECLARE VARIABLE WK_L_GST_CODE        VARCHAR(3) ; 
DECLARE VARIABLE WK_LEN_LABEL_NO      INTEGER; 
DECLARE VARIABLE WK_PROD_LENGTH       INTEGER;
DECLARE VARIABLE WK_PURCHASE_LENGTH   INTEGER;
DECLARE VARIABLE WK_PURCHASE_ORDER    VARCHAR(10); 
BEGIN
   WK_H_PERSON_ID  = NEW.H_PERSON_ID;
   WK_P_PERSON_TYPE = NEW.P_PERSON_TYPE;
   WK_P_FIRST_NAME = NEW.P_FIRST_NAME;
   WK_P_LAST_NAME = NEW.P_LAST_NAME;
   WK_P_ADDRESS_LINE1 = NEW.P_ADDRESS_LINE1;
   WK_P_ADDRESS_LINE2 = NEW.P_ADDRESS_LINE2;
   WK_P_CITY = NEW.P_CITY;
   WK_P_STATE = NEW.P_STATE;
   WK_P_POST_CODE = NEW.P_POST_CODE;
   WK_P_COUNTRY = NEW.P_COUNTRY;

   WK_H_PURCHASE_ORDER = NEW.H_PURCHASE_ORDER ;
   WK_H_REQUISITION_NO = NEW.H_REQUISITION_NO ;
   WK_H_PO_DATE        = NEW.H_PO_DATE        ;
   WK_H_PO_REVISION_NO = NEW.H_PO_REVISION_NO ;
   WK_H_PO_STATUS      = NEW.H_PO_STATUS      ;
   WK_H_COMMENTS       = NEW.H_COMMENTS       ;
   WK_H_PO_PRINTED     = NEW.H_PO_PRINTED     ;
   WK_H_USER_ID        = NEW.H_USER_ID        ;
   WK_H_COMPANY_ID = NEW.H_COMPANY_ID;
   WK_H_DIVISION_ID = NEW.H_DIVISION_ID;

   WK_L_PURCHASE_ORDER  = NEW.L_PURCHASE_ORDER  ;
   WK_L_PO_LINE         = NEW.L_PO_LINE         ;
   WK_L_REQUISITION_NO  = NEW.L_REQUISITION_NO  ;
   WK_L_PROD_ID         = NEW.L_PROD_ID         ;
   WK_L_PO_LINE_QTY     = NEW.L_PO_LINE_QTY     ;
   WK_L_UNIT_PRICE      = NEW.L_UNIT_PRICE      ;
   WK_L_UOM_ORDER       = NEW.L_UOM_ORDER       ;
   WK_L_PO_LINE_DUE_DATE = NEW.L_PO_LINE_DUE_DATE ;
   WK_L_PO_LINE_STATUS  = NEW.L_PO_LINE_STATUS  ;
   WK_L_COMMENTS        = NEW.L_COMMENTS        ;
   WK_L_GST_VALUE       = NEW.L_GST_VALUE       ;
   WK_L_GST_RATE        = NEW.L_GST_RATE        ;
   WK_L_GST_CODE        = NEW.L_GST_CODE        ;
   /* Check person */
   WK_FOUND = 0;
   SELECT 1 FROM PERSON 
      WHERE PERSON_ID = :WK_H_PERSON_ID
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no person so insert it */
      INSERT INTO PERSON (PERSON_ID, PERSON_TYPE, FIRST_NAME, LAST_NAME, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, POST_CODE, COUNTRY)
      VALUES (:WK_H_PERSON_ID, :WK_P_PERSON_TYPE, :WK_P_FIRST_NAME, :WK_P_LAST_NAME, :WK_P_ADDRESS_LINE1, :WK_P_ADDRESS_LINE2, :WK_P_CITY, :WK_P_STATE, :WK_P_POST_CODE, :WK_P_COUNTRY);
   END
   ELSE
   BEGIN
      UPDATE PERSON  SET PERSON_TYPE = :WK_P_PERSON_TYPE, 
         FIRST_NAME = :WK_P_FIRST_NAME, 
         LAST_NAME = :WK_P_LAST_NAME, 
         ADDRESS_LINE1 = :WK_P_ADDRESS_LINE1, 
         ADDRESS_LINE2 = :WK_P_ADDRESS_LINE2, 
         CITY = :WK_P_CITY, 
         STATE = :WK_P_STATE, 
         POST_CODE = :WK_P_POST_CODE, 
         COUNTRY = :WK_P_COUNTRY 
       WHERE PERSON_ID = :WK_H_PERSON_ID;
   END
   WK_FOUND = 0;
   /* Get length for purchase */   
   SELECT MAX_LENGTH
   FROM PARAM
   WHERE DATA_ID = 'PURCHASE'
   INTO :WK_PURCHASE_LENGTH;
   IF (SUBSTR(WK_H_PURCHASE_ORDER,1,1) <> 'P') THEN
   BEGIN
      WK_PURCHASE_ORDER = WK_H_PURCHASE_ORDER;
      WK_H_PURCHASE_ORDER = 'P' ; 
      WK_LEN_LABEL_NO = STRLEN(WK_PURCHASE_ORDER) + 1 ;     
      /* Padding leading with 0 */
      WHILE (WK_LEN_LABEL_NO < :WK_PURCHASE_LENGTH) DO
      BEGIN
         WK_H_PURCHASE_ORDER= WK_H_PURCHASE_ORDER || '0';      
         WK_LEN_LABEL_NO = WK_LEN_LABEL_NO + 1;
      END
      WK_H_PURCHASE_ORDER= WK_H_PURCHASE_ORDER || WK_PURCHASE_ORDER;      
   END
   WK_L_PURCHASE_ORDER = WK_H_PURCHASE_ORDER ;

   SELECT 1 FROM PURCHASE_ORDER
      WHERE PURCHASE_ORDER = :WK_H_PURCHASE_ORDER
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no order so insert it */
      INSERT INTO PURCHASE_ORDER (
         PURCHASE_ORDER, 
         REQUISITION_NO,
         PO_DATE,      
         PO_REVISION_NO,
         PO_STATUS,    
         COMMENTS,    
         PO_PRINTED, 
         USER_ID,   
         PERSON_ID,
         COMPANY_ID,
         DIVISION_ID)
      VALUES (
         :WK_H_PURCHASE_ORDER     ,
         :WK_H_REQUISITION_NO    ,
         :WK_H_PO_DATE          ,
         :WK_H_PO_REVISION_NO  ,
         :WK_H_PO_STATUS             ,
         :WK_H_COMMENTS             ,
         :WK_H_PO_PRINTED          ,
         :WK_H_USER_ID            ,
         :WK_H_PERSON_ID ,
         :WK_H_COMPANY_ID ,
         :WK_H_DIVISION_ID);
   END
   ELSE
   BEGIN
      UPDATE PURCHASE_ORDER SET
         REQUISITION_NO = :WK_H_REQUISITION_NO ,
         PO_DATE =     :WK_H_PO_DATE ,
         PO_REVISION_NO = :WK_H_PO_REVISION_NO  ,
         PO_STATUS =   :WK_H_PO_STATUS,
         COMMENTS =   :WK_H_COMMENTS ,
         PO_PRINTED = :WK_H_PO_PRINTED ,
         USER_ID =  :WK_H_USER_ID ,
        PERSON_ID = :WK_H_PERSON_ID ,
        COMPANY_ID = :WK_H_COMPANY_ID ,
        DIVISION_ID = :WK_H_DIVISION_ID 
         WHERE PURCHASE_ORDER = :WK_H_PURCHASE_ORDER ;
   END
   /* Get length for product */   
   SELECT MAX_LENGTH
   FROM PARAM
   WHERE DATA_ID = 'PROD_INTERNAL'
   INTO :WK_PROD_LENGTH;
   WK_LEN_LABEL_NO = STRLEN(WK_L_PROD_ID) ;     
   /* Padding leading with 0 */
   WHILE (WK_LEN_LABEL_NO < :WK_PROD_LENGTH) DO
   BEGIN
      WK_L_PROD_ID = '0' || WK_L_PROD_ID ;      
      WK_LEN_LABEL_NO = WK_LEN_LABEL_NO + 1;
   END

   WK_FOUND = 0;
   SELECT 1 FROM PURCHASE_ORDER_LINE
      WHERE PURCHASE_ORDER = :WK_L_PURCHASE_ORDER AND
            PO_LINE = :WK_L_PO_LINE
      INTO :WK_FOUND;
   IF (WK_FOUND = 0) THEN
   BEGIN
      /* no line so insert it */
      INSERT INTO PURCHASE_ORDER_LINE (
         PURCHASE_ORDER,              
         PO_LINE,                    
         REQUISITION_NO,            
         PROD_ID,                  
         PO_LINE_QTY,            
         UNIT_PRICE,            
         UOM_ORDER,            
         PO_LINE_DUE_DATE,    
         PO_LINE_STATUS,     
         COMMENTS,          
         GST_VALUE,        
         GST_RATE,        
         GST_CODE)        
      VALUES (
         :WK_L_PURCHASE_ORDER,              
         :WK_L_PO_LINE,                    
         :WK_L_REQUISITION_NO,            
         :WK_L_PROD_ID       ,           
         :WK_L_PO_LINE_QTY   ,         
         :WK_L_UNIT_PRICE    ,        
         :WK_L_UOM_ORDER     ,       
         :WK_L_PO_LINE_DUE_DATE,    
         :WK_L_PO_LINE_STATUS,     
         :WK_L_COMMENTS      ,    
         :WK_L_GST_VALUE     ,   
         :WK_L_GST_RATE      ,  
         :WK_L_GST_CODE );       
   END
   ELSE
   BEGIN
      UPDATE PURCHASE_ORDER_LINE SET
         REQUISITION_NO = :WK_L_REQUISITION_NO,            
         PROD_ID =        :WK_L_PROD_ID       ,           
         PO_LINE_QTY =    :WK_L_PO_LINE_QTY   ,         
         UNIT_PRICE =     :WK_L_UNIT_PRICE    ,        
         UOM_ORDER =      :WK_L_UOM_ORDER     ,       
         PO_LINE_DUE_DATE = :WK_L_PO_LINE_DUE_DATE,    
         PO_LINE_STATUS =   :WK_L_PO_LINE_STATUS,     
         COMMENTS =         :WK_L_COMMENTS    ,      
         GST_VALUE =      :WK_L_GST_VALUE     ,   
         GST_RATE =       :WK_L_GST_RATE      ,  
         GST_CODE =       :WK_L_GST_CODE         
      WHERE PURCHASE_ORDER = :WK_L_PURCHASE_ORDER AND           
         PO_LINE =        :WK_L_PO_LINE;                    
   END
END ^
 
CREATE TRIGGER RUN_TRANSACTION_EIND FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 58 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_DATE TIMESTAMP;
DECLARE VARIABLE WK_USER VARCHAR(10);
DECLARE VARIABLE WK_SUB_LOCN VARCHAR(10);
DECLARE VARIABLE WK_OBJECT VARCHAR(30);
DECLARE VARIABLE WK_DEVICE VARCHAR(2);
DECLARE VARIABLE WK_CARD VARCHAR(10);
DECLARE VARIABLE WK_FIRST_NAME VARCHAR(20);
DECLARE VARIABLE WK_LAST_NAME VARCHAR(25);
DECLARE VARIABLE WK_CLASS CHAR(1);
DECLARE VARIABLE WK_WH_ID CHAR(2);
DECLARE VARIABLE WK_LOCN_ID VARCHAR(10);
DECLARE VARIABLE WK_QTY INTEGER;
DECLARE VARIABLE WK_TITLE VARCHAR(12);
DECLARE VARIABLE WK_TITLE_DB VARCHAR(5);
DECLARE VARIABLE WK_REF VARCHAR(40);
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_DOB_X VARCHAR(10);
DECLARE VARIABLE WK_DOB_STR VARCHAR(10);
DECLARE VARIABLE WK_DOB_DT  TIMESTAMP;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'EIND') THEN
  BEGIN
     WK_FOUND = 0;
     WK_SUB_LOCN = NEW.SUB_LOCN_ID;
     WK_OBJECT = NEW.OBJECT;
     WK_CARD = substr(WK_OBJECT,1, 10);
     WK_FIRST_NAME = substr(WK_OBJECT,11, 30);
     WK_CLASS = NEW.TRN_CODE;
     WK_QTY = NEW.QTY;
     WK_WH_ID = NEW.WH_ID;
     WK_LOCN_ID = NEW.LOCN_ID;
     WK_TITLE = WK_WH_ID || WK_LOCN_ID;
     WK_TITLE_DB = substr(WK_TITLE,1,5);
     WK_REF = NEW.REFERENCE;
     WK_LAST_NAME = substr(WK_REF,1,25);
     WK_DATE = NEW.TRN_DATE;
     WK_USER = NEW.PERSON_ID;
     WK_DOB_X = ALLTRIM(WK_SUB_LOCN);
     IF (LEN(WK_DOB_X) = 8) THEN
     BEGIN
        WK_DOB_STR = SUBSTR(WK_DOB_X,5,6) || '-' ||   
           SUBSTR(WK_DOB_X,7,8) || '-' ||   
           SUBSTR(WK_DOB_X,1,4) ;  
        WK_DOB_DT = CAST(WK_DOB_STR AS DATE);
     END
     ELSE
     BEGIN
        WK_DOB_DT = NULL;
     END
     SELECT 1
       FROM EMPLOYEE
       WHERE EMPLOYEE_ID = :WK_CARD
       INTO :WK_FOUND;
     IF (WK_FOUND = 1) THEN
     BEGIN
        /* employee exists so update */
        UPDATE EMPLOYEE SET
           FIRST_NAME = :WK_FIRST_NAME,
           LAST_NAME = :WK_LAST_NAME,
           DOB = :WK_DOB_DT,
           TITLE = :WK_TITLE_DB,
           UPDATE_BY = :WK_USER,
           UPDATE_DATE = :WK_DATE
           WHERE EMPLOYEE_ID = :WK_CARD;
     END
     ELSE
     BEGIN
        /* no employee so add */
        INSERT INTO EMPLOYEE (
           EMPLOYEE_ID,
           FIRST_NAME,
           LAST_NAME,
           DOB,
           TITLE,
           CREATE_BY,
           CREATE_DATE)
           VALUES (
           :WK_CARD,
           :WK_FIRST_NAME,
           :WK_LAST_NAME,
           :WK_DOB_DT,
           :WK_TITLE_DB,
           :WK_USER,
           :WK_DATE);
     END
     WK_FOUND = 0;
     SELECT 1
       FROM PERSON
       WHERE PERSON_ID = :WK_CARD
       INTO :WK_FOUND;
     IF (WK_FOUND = 1) THEN
     BEGIN
        /* person exists so update */
        UPDATE PERSON SET
           FIRST_NAME = :WK_FIRST_NAME,
           LAST_NAME = :WK_LAST_NAME,
           TITLE = :WK_TITLE_DB
           WHERE PERSON_ID = :WK_CARD;
     END
     ELSE
     BEGIN
        /* no person so add */
        INSERT INTO PERSON (
           PERSON_ID,
           FIRST_NAME,
           LAST_NAME,
           TITLE,
           CREATE_DATE)
           VALUES (
           :WK_CARD,
           :WK_FIRST_NAME,
           :WK_LAST_NAME,
           :WK_TITLE,
           :WK_DATE);
     END
  END
 END
END^

In f.person.trig^

SET TERM ;^

