DROP TRIGGER ADD_SSN_PUCHASE_PRICE^

DROP   TRIGGER UPD_SSN_PUCHASE_PRICE^


CREATE PROCEDURE POP_SSN_DESCRIPTION (WK_SSN VARCHAR(30))      
AS
DECLARE VARIABLE WK_DUMMY VARCHAR(1);
DECLARE VARIABLE WK_DESCRIPTION VARCHAR(450);
DECLARE VARIABLE WK_DESCRIPTION2 VARCHAR(80);
DECLARE VARIABLE WK_TYPE VARCHAR(40);
DECLARE VARIABLE WK_GENERIC VARCHAR(40);
DECLARE VARIABLE WK_BRAND VARCHAR(40);
DECLARE VARIABLE WK_MODEL VARCHAR(40);
DECLARE VARIABLE WK_SERIAL_NUMBER VARCHAR(30);
BEGIN
   FOR SELECT SSN_TYPE, GENERIC, BRAND, MODEL, SERIAL_NUMBER  
       FROM SSN 
       WHERE SSN_ID = :WK_SSN
       INTO :WK_TYPE, :WK_GENERIC, :WK_BRAND, :WK_MODEL, :WK_SERIAL_NUMBER 
   DO
   BEGIN
/*
      WK_DESCRIPTION = ALLTRIM(WK_TYPE) || ' ' || ALLTRIM(WK_GENERIC) || ' ' || ALLTRIM(WK_BRAND) || ' ' || ALLTRIM(WK_MODEL) || ' ' || ALLTRIM(WK_SERIAL_NUMBER) || ' ' || ALLTRIM(WK_OTHER1) || ' ' || ALLTRIM(WK_OTHER2) || ' ' || ALLTRIM(WK_OTHER3); 	
*/
      WK_DESCRIPTION = '';
      IF (NOT WK_TYPE IS NULL) THEN
      BEGIN
         WK_DESCRIPTION = ALLTRIM(WK_TYPE) || ' ' ;
      END
      IF (NOT WK_GENERIC IS NULL) THEN
      BEGIN
         WK_DESCRIPTION = WK_DESCRIPTION || ALLTRIM(WK_GENERIC) || ' ' ;
      END
      IF (STRLEN(WK_DESCRIPTION) < 80) THEN
      BEGIN
         IF (NOT WK_BRAND IS NULL) THEN
         BEGIN
            WK_DESCRIPTION = WK_DESCRIPTION || ALLTRIM(WK_BRAND) || ' ' ;
         END
      END
      IF (STRLEN(WK_DESCRIPTION) < 80) THEN
      BEGIN
         IF (NOT WK_MODEL IS NULL) THEN
         BEGIN
            WK_DESCRIPTION = WK_DESCRIPTION || ALLTRIM(WK_MODEL)  ;
         END
      END
      IF (STRLEN(WK_DESCRIPTION) < 80) THEN
      BEGIN
         IF (NOT WK_SERIAL_NUMBER IS NULL) THEN
         BEGIN
            WK_DESCRIPTION = '[' || WK_DESCRIPTION || ALLTRIM(WK_SERIAL_NUMBER) || ']' ;
         END
      END
      WK_DESCRIPTION2 = SUBSTR(WK_DESCRIPTION,1,80);
      UPDATE SSN SET SSN_DESCRIPTION = :WK_DESCRIPTION2 WHERE SSN_ID = :WK_SSN;
   END
END^

CREATE TRIGGER ADD_PICK_ITEM_DESCRIPTION FOR PICK_ITEM 
ACTIVE AFTER INSERT POSITION 2
AS
DECLARE VARIABLE WK_SSN VARCHAR(30);
BEGIN
   WK_SSN = NEW.SSN_ID;
   IF (NOT WK_SSN IS NULL) THEN
   BEGIN
      EXECUTE PROCEDURE POP_SSN_DESCRIPTION :WK_SSN;
   END
END^

