CREATE TABLE PICK_ORDER_ITEM(
PICK_ORDER PICK_ORDER NOT NULL,
LAST_LINE_NO INTEGER,
PRIMARY KEY (PICK_ORDER))^

CREATE TRIGGER ADD_PICK_ORDER_LINE_NO FOR PICK_ORDER 
ACTIVE AFTER INSERT POSITION 1 
AS
DECLARE VARIABLE WK_ORDER VARCHAR(15);
BEGIN
WK_ORDER = NEW.PICK_ORDER;
INSERT INTO PICK_ORDER_ITEM (PICK_ORDER, LAST_LINE_NO) VALUES (:WK_ORDER, 0);
END^

