DROP TRIGGER ADD_SSN_PUCHASE_PRICE^

CREATE TRIGGER ADD_SSN_PUCHASE_PRICE FOR SSN            
ACTIVE BEFORE INSERT POSITION 1 
AS
DECLARE VARIABLE WK_DUMMY VARCHAR(1);
DECLARE VARIABLE WK_DESCRIPTION VARCHAR(400);
BEGIN
   IF (NEW.PURCHASE_PRICE IS NULL) THEN
   BEGIN
      WK_DUMMY = 'Y';
   END
   ELSE
   BEGIN
      WK_DESCRIPTION = ALLTRIM(NEW.SSN_TYPE) || ' ' || ALLTRIM(NEW.GENERIC) || ' ' || ALLTRIM(NEW.BRAND) || ' ' || ALLTRIM(NEW.MODEL) || '[' || ALLTRIM(NEW.SERIAL_NUMBER) || ']' ; 	
      NEW.SSN_DESCRIPTION = SUBSTR(WK_DESCRIPTION,1,80);
   END
END^

DROP   TRIGGER UPD_SSN_PUCHASE_PRICE^

CREATE TRIGGER UPD_SSN_PUCHASE_PRICE FOR SSN            
ACTIVE BEFORE UPDATE POSITION 1 
AS
DECLARE VARIABLE WK_UPDATE VARCHAR(1);
DECLARE VARIABLE WK_DESCRIPTION VARCHAR(400);
BEGIN
   WK_UPDATE = 'N';
   IF (NEW.PURCHASE_PRICE IS NULL) THEN
   BEGIN
      IF (OLD.PURCHASE_PRICE IS NULL) THEN
      BEGIN
         WK_UPDATE = 'N';
      END
      ELSE
      BEGIN
         WK_UPDATE = 'Y';
      END
   END
   ELSE
   BEGIN
      IF (OLD.PURCHASE_PRICE IS NULL) THEN
      BEGIN
         WK_UPDATE = 'Y';
      END
      ELSE
      BEGIN
         IF (NEW.PURCHASE_PRICE <> OLD.PURCHASE_PRICE) THEN
         BEGIN
            WK_UPDATE = 'Y';
         END
         ELSE
         BEGIN
            WK_UPDATE = 'N';
         END
      END
   END
   IF (WK_UPDATE = 'Y') THEN
   BEGIN
      WK_DESCRIPTION = ALLTRIM(NEW.SSN_TYPE) || ' ' || ALLTRIM(NEW.GENERIC) || ' ' || ALLTRIM(NEW.BRAND) || ' ' || ALLTRIM(NEW.MODEL) || '[' || ALLTRIM(NEW.SERIAL_NUMBER) || ']' ; 	
      NEW.SSN_DESCRIPTION = SUBSTR(WK_DESCRIPTION,1,80);
   END
END^

