/* Table: IMAGES, Owner: SYSDBA */
CREATE TABLE IMAGES (IMAGE_NO IMAGE_NO NOT NULL,
        IMAGE_LOC IMAGE_LOC,
        IMAGE IMAGE,
        DESCRIPTION DESCRIPTION,
        IMAGE_NAME IMAGE_NAME,
        IMAGE_ID PERSON NOT NULL,
        IMAGE_BLOB IMAGE,
        IMAGE_TYPE CODE_TWO,
        IMAGE_FORMAT IMAGE_FORMAT,
        IMAGE_SOURCE IMAGE_SOURCE,
        IMAGE_DATE IMAGE_DATE,
        CREATED_BY MDR_USER_ID,
CONSTRAINT IMAGES_PX PRIMARY KEY (IMAGE_NO));

