COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */



ALTER PROCEDURE RPT_DAILY_5_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  /* the total orders picking in progress */
SELECT  COUNT(DISTINCT(PICK_ITEM.PICK_ORDER))
FROM PICK_ITEM 
WHERE PICK_ITEM.PICK_LINE_STATUS IN ('AL','PG','PL') 
AND (PICK_ITEM.DESPATCH_LOCATION IS NULL)
AND (PICK_ITEM.PICK_STARTED <= MAXTIME(:THISSTART) )
  INTO
  :THISCOUNT;
  SUSPEND;
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* STORED PROCEDURES */



ALTER PROCEDURE RPT_DAILY_6_DATA 
(
  THISSTART TIMESTAMP,
  THISEND TIMESTAMP
)
RETURNS
(
  THISCOUNT INTEGER
)
AS
BEGIN
  /* PROCEDURE BODY */
  /* the total orders picked but not despatched */
  FOR
SELECT  COUNT(DISTINCT(PICK_ITEM.PICK_ORDER))
FROM PICK_ITEM 
WHERE PICK_ITEM.PICK_LINE_STATUS IN ('PL','DS') AND
      (PICK_ITEM.DESPATCH_LOCATION IS NOT NULL) 
AND (PICK_ITEM.PICK_STARTED <= MAXTIME(:THISSTART) )
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
/*
SELECT  COUNT(DISTINCT(PICK_ITEM.PICK_ORDER))
FROM PICK_ITEM 
LEFT OUTER JOIN PICK_ITEM P2 ON P2.PICK_ORDER = PICK_ITEM.PICK_ORDER
AND P2.PICK_LABEL_NO <> PICK_ITEM.PICK_LABEL_NO
AND P2.PICK_LINE_STATUS IN ('AL','PG','PL')
AND P2.DESPATCH_LOCATION IS NULL
WHERE PICK_ITEM.PICK_LINE_STATUS IN ('PL','DS') AND
      (PICK_ITEM.DESPATCH_LOCATION IS NOT NULL) AND
      (P2.PICK_LABEL_NO IS NULL)
*/
/*
SELECT  COUNT(DISTINCT(PICK_ITEM.PICK_ORDER))
FROM PICK_ORDER
INNER JOIN PICK_ITEM ON PICK_ORDER.PICK_ORDER = PICK_ITEM.PICK_ORDER
INNER JOIN SYS_USER ON PICK_ITEM.USER_ID = SYS_USER.USER_ID
WHERE (PICK_ORDER.ASSEMBLY_STARTED BETWEEN ZEROTIME(:THISSTART) AND MAXTIME(:THISEND))
  INTO
  :THISCOUNT
  DO
  BEGIN
  SUSPEND;
  END
*/
END
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
COMMIT WORK;
