/*
DROP TABLE IMAGES;
*/

CREATE GENERATOR EMP_IMAGE_GEN;

CREATE TABLE EMPLOYEE_IMAGE ( 
IMAGE_ID IMAGE_NO NOT NULL, 
IMAGE_CAPTURED IMAGE, 
IMAGE_TYPE CHAR(2), 
PERSON_ID PERSON, 
IMAGE_FORMAT VARCHAR(4), 
IMAGE_SOURCE VARCHAR(50), 
IMAGE_TITLE VARCHAR(50), 
CREATE_DATE DATE, 
CREATE_BY PERSON,
PRIMARY KEY (IMAGE_ID)
);

SET TERM ^;
CREATE PROCEDURE GET_EMP_IMAGE_ID RETURNS ( IMAGE_ID INTEGER )
 AS 
BEGIN 
   IMAGE_ID = GEN_ID(EMP_IMAGE_GEN, 1);
END^

SET TERM ;^


