COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 
DROP TRIGGER RUN_TRANSACTION_AUOB ^
DROP TRIGGER RUN_TRANSACTION_NIID ^
COMMIT^

CREATE TRIGGER RUN_TRANSACTION_AUOB FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 29 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
DECLARE VARIABLE WK_RECORD_ID INTEGER;
DECLARE VARIABLE WK_WH_ID CHAR(2);
DECLARE VARIABLE WK_LOCN_ID VARCHAR(10);
DECLARE VARIABLE WK_OBJECT VARCHAR(30);
DECLARE VARIABLE WK_TRN_TYPE VARCHAR(4);
DECLARE VARIABLE WK_TRN_CODE CHAR(1);
DECLARE VARIABLE WK_TRN_DATE TIMESTAMP;
DECLARE VARIABLE WK_REFERENCE VARCHAR(40);
DECLARE VARIABLE WK_QTY INTEGER;
DECLARE VARIABLE WK_PERSON_ID VARCHAR(10);
DECLARE VARIABLE WK_DEVICE_ID CHAR(2);
DECLARE VARIABLE WK_INSTANCE_ID VARCHAR(10);
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'AUOB') THEN
  BEGIN
    WK_RECORD_ID = NEW.RECORD_ID ;
    WK_WH_ID = NEW.WH_ID;
    WK_LOCN_ID = NEW.LOCN_ID;
    WK_OBJECT = NEW.OBJECT;
    WK_TRN_TYPE = NEW.TRN_TYPE;
    WK_TRN_CODE = NEW.TRN_CODE;
    WK_TRN_DATE = NEW.TRN_DATE;
    WK_REFERENCE = NEW.REFERENCE;
    WK_QTY = NEW.QTY;
    WK_PERSON_ID = NEW.PERSON_ID;
    WK_DEVICE_ID = NEW.DEVICE_ID;
    WK_INSTANCE_ID = NEW.INSTANCE_ID;
   EXECUTE PROCEDURE PC_AUOB (
    WK_RECORD_ID ,
    WK_WH_ID,
    WK_LOCN_ID,
    WK_OBJECT,
    WK_TRN_TYPE,
    WK_TRN_CODE,
    WK_TRN_DATE,
    WK_REFERENCE,
    WK_QTY,
    WK_PERSON_ID,
    WK_DEVICE_ID,
    WK_INSTANCE_ID);
   /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
  END
 END
END ^

CREATE TRIGGER RUN_TRANSACTION_NIID FOR TRANSACTIONS 
ACTIVE AFTER INSERT POSITION 30 
AS
DECLARE VARIABLE WK_AUTORUN INTEGER;
BEGIN
 WK_AUTORUN = GEN_ID(AUTOEXEC_TRANSACTIONS,0); 
 IF (WK_AUTORUN = 1) THEN
 BEGIN
  IF (NEW.TRN_TYPE = 'NIID') THEN
  BEGIN
   EXECUTE PROCEDURE PC_AUOB 
    NEW.RECORD_ID ,
    NEW.WH_ID,
    NEW.LOCN_ID,
    NEW.OBJECT,
    NEW.TRN_TYPE,
    NEW.TRN_CODE,
    NEW.TRN_DATE,
    NEW.REFERENCE,
    NEW.QTY,
    NEW.PERSON_ID,
    NEW.DEVICE_ID,
    NEW.INSTANCE_ID;
   /* EXECUTE PROCEDURE TRAN_ARCHIVE; */
  END
 END
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
