COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;
 

CREATE OR ALTER TRIGGER ADD_PRN_REQUEST_NP FOR PRINT_REQUESTS 
ACTIVE BEFORE INSERT POSITION 20 
AS
DECLARE VARIABLE WK_FOUND INTEGER;
DECLARE VARIABLE WK_GM_MESSAGE VARCHAR(10);
DECLARE VARIABLE WK_DATA_FIELDS INTEGER;
DECLARE VARIABLE WK_FIELD_NO INTEGER;
DECLARE VARIABLE WK_WORK_DATA VARCHAR(32000);
DECLARE VARIABLE WK_WORK_LABEL VARCHAR(32000);
DECLARE VARIABLE WK_WORK_FIELD VARCHAR(32000);
DECLARE VARIABLE WK_WORK_AT_END CHAR(1);
DECLARE VARIABLE WK_WH_ID VARCHAR(32000);
DECLARE VARIABLE WK_ISSN_PRINTER CHAR(2);
DECLARE VARIABLE WK_LOG_FILENAME VARCHAR(80) ;
DECLARE VARIABLE WK_LOG_RESULT   INTEGER;
BEGIN
   NEW.PRN_DATE = 'NOW';
   IF (NEW.MESSAGE_ID IS NULL OR NEW.MESSAGE_ID = '') THEN
   BEGIN
      WK_GM_MESSAGE = '';
      SELECT MESSAGE_ID 
      FROM GET_NEXT_MESSAGE 
      INTO :WK_GM_MESSAGE;
      NEW.MESSAGE_ID =  WK_GM_MESSAGE;
   END
   ELSE
   BEGIN
      WK_GM_MESSAGE = NEW.MESSAGE_ID;
   END
   IF (NEW.REQUEST_STATUS IS NULL OR NEW.REQUEST_STATUS = '') THEN
   BEGIN
      NEW.REQUEST_STATUS = 'NP';
   END

   IF (NEW.REQUEST_STATUS  = 'NP') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_NP';
   END
   IF (NEW.REQUEST_STATUS  = 'CP') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_CP';
   END
   IF (NEW.REQUEST_STATUS  = 'NQ') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_NQ';
   END
END ^

CREATE OR ALTER TRIGGER UPDATE_PRN_REQUEST_NP FOR PRINT_REQUESTS 
ACTIVE BEFORE UPDATE POSITION 20 
AS
BEGIN
   NEW.PRN_DATE = 'NOW';
   IF (NEW.REQUEST_STATUS = 'NP') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_NP';
   END
   IF (NEW.REQUEST_STATUS = 'CP') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_CP';
   END
   IF (NEW.REQUEST_STATUS = 'NQ') THEN
   BEGIN
      POST_EVENT 'PRN_REQUEST_NQ';
   END
END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
