ALTER TABLE GLOBAL_CONDITIONS ADD
  MATCH_OPERATOR VARCHAR(5);

INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (4, 'SV', 'C', 'START');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (3, 'MISSING', 'C', 'START');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (3, 'DAMAGED', 'C', 'START');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (2, 'FAULTY', 'C', 'START');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (2, 'NOT-TESTED', 'C', 'EQUAL');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (2, 'TESTED FAULTY', 'C', 'EQUAL');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (2, 'TESTED-FAULTY', 'C', 'EQUAL');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (2, 'DAMAGE', 'C', 'ANY');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (5, '-COA', 'C', 'ANY');
INSERT INTO GLOBAL_CONDITIONS (OTHER_NO, DESCRIPTION, RESULT, MATCH_OPERATOR) VALUES (5, '-CD', 'C', 'END');

