INSERT INTO SYS_EQUIP(DEVICE_ID, operating_zone) VALUES ('BA', 'Z1');
UPDATE SYS_USER SET ZONE_C='Z1' WHERE USER_ID='USERA';
UPDATE LOCATION SET ZONE_C='Z1' WHERE LOCN_ID STARTING 'A';
INSERT INTO ZONE(CODE,DESCRIPTION) VALUES('Z1','Abi group 1st Issue Zone');
INSERT INTO SYS_EQUIP(DEVICE_ID,WORKING_DIRECTORY) VALUES('PD','d:\asset.rf\PD\');


