ALTER TABLE CONTROL ADD DEFAULT_CONNOTE_PACK CHAR(1) DEFAULT 'C';
ALTER TABLE CONTROL ADD DEFAULT_CONNOTE_WEIGHT WEIGHT DEFAULT  1;
ALTER TABLE CONTROL ADD DEFAULT_CONNOTE_QTY_LABELS QTY DEFAULT  0;
ALTER TABLE CONTROL ADD ASSEMBLE_DESPATCH VALUE_TF;

CREATE DOMAIN CODE_6 VARCHAR(6);
CREATE DOMAIN CODE_255 VARCHAR(255);

ALTER TABLE CONTROL ADD ORDER_UPDATE CODE_255;

UPDATE CONTROL SET DEFAULT_CONNOTE_QTY_LABELS = 0, DEFAULT_CONNOTE_WEIGHT=1, DEFAULT_CONNOTE_PACK = 'C', ASSEMBLE_DESPATCH = 'F';
