COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/*
  SSN_ID VARCHAR(20),
  PERSON_ID VARCHAR(10),
  DEVICE_ID VARCHAR(2),
  OPERATOR VARCHAR(10)
*/

CREATE OR ALTER PROCEDURE ADD_LOAN_HIST (
  LOAN_ORDER_NO INTEGER,
  LOAN_ORDER_LINE_NO INTEGER,
  SSN_ID SSN_ID,
  PERSON_ID PERSON,
  LOAN_TYPE VARCHAR(2),
  STATUS VARCHAR(2),  
  LOAN_DATE TIMESTAMP,
  DUE_DATE TIMESTAMP,
  RETURN_DATE TIMESTAMP,
  DEVICE_ID DEVICE_ID,
  OPERATOR VARCHAR(10)
)  AS         
BEGIN       
    INSERT INTO LOAN_HISTORY   
       (LOAN_ORDER_NO, LOAN_ORDER_LINE_NO, SSN_ID, PERSON_ID, LOAN_TYPE, STATUS, 
        LOAN_DATE, DUE_DATE, RETURN_DATE, DEVICE_ID, OPERATOR)
    VALUES (:LOAN_ORDER_NO, :LOAN_ORDER_LINE_NO, :SSN_ID, :PERSON_ID, :LOAN_TYPE, :STATUS, 
        :LOAN_DATE, :DUE_DATE, :RETURN_DATE, :DEVICE_ID, :OPERATOR);             
  
END ^




SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
