COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/*
CREATE  OR ALTER PROCEDURE ADD_INSP_HIST (SSN_ID VARCHAR(20) ,
STATUS CHAR(1) ,
TYPE_DATE TIMESTAMP,
TYPE_CODE VARCHAR(40) ,
TYPE_HEADER_CODE VARCHAR(40) ,
TYPE_LINE_CODE VARCHAR(40) ,
DESCRIPTION VARCHAR(100) ,
PERSON_ID VARCHAR(10) ,
DEVICE_ID VARCHAR(2) )
*/

CREATE  OR ALTER PROCEDURE ADD_INSP_HIST (SSN_ID SSN_ID ,
STATUS CHAR(1) ,
TYPE_DATE TIMESTAMP,
TYPE_CODE VARCHAR(40) ,
TYPE_HEADER_CODE VARCHAR(40) ,
TYPE_LINE_CODE VARCHAR(40) ,
DESCRIPTION VARCHAR(100) ,
PERSON_ID PERSON ,
DEVICE_ID DEVICE_ID )
AS 
   
  DECLARE VARIABLE REC_ID INTEGER;
BEGIN
   /* Add inspection history */                                                                      
   REC_ID = GEN_ID(INSP_HIST_RECORD_ID, 1);  
   INSERT INTO INSP_HIST   
        (RECORD_ID, SSN_ID, STATUS, TYPE_DATE, TYPE_CODE, 
         TYPE_HEADER_CODE, TYPE_LINE_CODE, DESCRIPTION, DEVICE_ID, PERSON_ID)
   VALUES (:REC_ID, :SSN_ID, :STATUS, :TYPE_DATE, :TYPE_CODE, 
         :TYPE_HEADER_CODE, :TYPE_LINE_CODE, :DESCRIPTION, :DEVICE_ID, :PERSON_ID);

END ^


SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;
