ALTER TABLE CONTROL
ADD ALLOW_SSN_SUBSTITUTE_DEFAULT CODE_ONE;

ALTER TABLE LOAN_ORDER
ADD LOAN_TYPE CODE_TWO;

ALTER TABLE LOAN_ORDER
ADD RETURN_DATE DATETIME;

ALTER TABLE LOAN_ORDER
ADD PICK_ORDER PICK_ORDER;

ALTER TABLE PICK_ITEM
ADD ALLOW_SUBSTITUTE CODE_ONE;

ALTER TABLE PICK_ITEM
ADD ORIGINAL_SSN_ID SSN_ID;

ALTER TABLE PICK_ITEM
ADD RETURN_DATE DATETIME;

ALTER TABLE PICK_ORDER
ADD PERMANENT_TRANSFER CODE_ONE;

ALTER TABLE PICK_ORDER
ADD RETURN_DATE DATETIME;

SET TERM ^ ;

ALTER PROCEDURE DESPATCH_LOCN_LIST (
    LOCATION VARCHAR (10))
RETURNS (
    DESPATCH_LOCATION VARCHAR (10),
    PICK_ORDER VARCHAR (15),
    PERSON_ID VARCHAR (10),
    PICK_STATUS CHAR (2),
    CONTACT_NAME VARCHAR (50),
    PICK_PRIORITY INTEGER,
    PICK_DUE_DATE DATE,
    SHIP_VIA VARCHAR (10),
    CREATED_BY VARCHAR (10),
    PARTIAL_PICK_ALLOWED CHAR (1),
    SPECIAL_INSTRUCTIONS1 VARCHAR (255),
    SPECIAL_INSTRUCTIONS2 VARCHAR (255),
    CREATE_DATE DATE,
    CUSTOMER_PO_WO VARCHAR (20),
    INV_WITH_GOODS CHAR (1),
    PICK_ORDER_TYPE VARCHAR(2))
AS
BEGIN
/* Modified 22/07/2004 by Manuel to add PICK_ORDER_TYPE field to output. Thats All*/
   FOR SELECT
      Pick_Item_Detail.Despatch_Location , 
      pick_item.pick_order 
      from pick_item_detail 
      join pick_item on pick_item.pick_label_no = pick_item_detail.pick_label_no 
      Where pick_item_detail.Pick_Detail_Status = 'DS' 
       And Pick_Item_Detail.Despatch_Location = :LOCATION 
      group by Pick_Item_Detail.Despatch_Location, 
               pick_item.pick_order  
      INTO :DESPATCH_LOCATION, PICK_ORDER
   DO
   BEGIN
      SELECT PERSON_ID, PICK_STATUS, CONTACT_NAME, 
                 PICK_PRIORITY, PICK_DUE_DATE, SHIP_VIA, CREATED_BY, 
                 PARTIAL_PICK_ALLOWED, SPECIAL_INSTRUCTIONS1, SPECIAL_INSTRUCTIONS2, 
                 CREATE_DATE, CUSTOMER_PO_WO, INV_WITH_GOODS, PICK_ORDER_TYPE
           FROM PICK_ORDER
           WHERE PICK_ORDER = :PICK_ORDER
           INTO :PERSON_ID, :PICK_STATUS, :CONTACT_NAME, 
                 :PICK_PRIORITY, :PICK_DUE_DATE, :SHIP_VIA, :CREATED_BY, 
                 :PARTIAL_PICK_ALLOWED, :SPECIAL_INSTRUCTIONS1, :SPECIAL_INSTRUCTIONS2, 
                 :CREATE_DATE, :CUSTOMER_PO_WO, :INV_WITH_GOODS, :PICK_ORDER_TYPE;
       SUSPEND;
   END 
END
^

Set Term ; ^

