

SELECT
/* ------------------------PICK_ITEM --------------------- */
       PICK_ITEM.PICK_LABEL_NO      	  AS PI_PICK_LABEL_NO,
       PICK_ITEM.PICK_ORDER_LINE_NO  AS PI_PICK_ORDER_LINE_NO,
       PICK_ITEM.PROD_ID 		 AS PI_PROD_ID,   

/* ------------------------PROD_PROFILE--------------------- */
       PROD_PROFILE.SHORT_DESC 	  AS PP_SHORT_DESC,      
       PROD_PROFILE.PROD_ID 	AS PP_PROD_ID,          
/* -----------------------COMPANY ---------------------------- */
       COMPANY.NAME                 	AS COMPANY_NAME,
       COMPANY.ABN                  	AS COMPANY_ABN,
       COMPANY.ACN                  	AS COMPANY_ACN,
       COMPANY.INV_TEXT1            	AS COMPANY_INV_TEXT1,
       COMPANY.BANK_ID_NO1          	AS COMPANY_BANK_ID_NO1,
       COMPANY.BANK_BSB_TITLE1      	AS COMPANY_BANK_BSB_TITLE1,
       COMPANY.BANK_BSB_NO1         	AS COMPANY_BANK_BSB_NO1,
       COMPANY.BANK_AC_TITLE1       	AS COMPANY_BANK_AC_TITLE1,
       COMPANY.BANK_ACCOUNT_1       	AS COMPANY_BANK_ACCOUNT1,
       COMPANY.CREDIT_TO_TITLE1     	AS COMPANY_CREDIT_TO_TITLE1,
       COMPANY.CREDIT_TO_NAME1      	AS COMPANY_CREDIT_TO_NAME1,
       COMPANY.COMPANY_UDF11        	AS COMPANY_COMPANY_UDF11,
       COMPANY.COMPANY_UDF12        	AS COMPANY_COMPANY_UDF12,

/*--- PERSON WHERE PERSON_ID ='AITS' AND STATUS ='CU'-------- */
       PERSON.PHONE_NO               	AS PERSON_PHONE_NO,
       PERSON.FAX_NO                 	AS PERSON_FAX_NO,
       PERSON.EMAIL                  	AS PERSON_EMAIL,
       PERSON.WEB_SITE               	AS PERSON_WEB_SITE,

/*--- PERSON_ADDRESS alias f WHERE PERSON_ID ='AITS' AND ADDR_STATUS ='CU' AND ADDR_TYPE ='OF' Office -- */
   /* ---PERSON_ADDRESS_OF.ADDR_FIRST_NAME AS OF_P_OFFICE_ADDR_FIRST_NAME, ---------------------------------*/
        (SELECT FIRST 1 PERSON_ADDRESS_OF1.ADDR_FIRST_NAME
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF1
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF1.PERSON_ID AND PERSON_ADDRESS_OF1.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF1.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_FIRST_NAME,
    /* --PERSON_ADDRESS_OF.ADDR_LAST_NAME AS OF_P_OFFICE_ADDR_LAST_NAME, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF2.ADDR_LAST_NAME
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF2
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF2.PERSON_ID AND PERSON_ADDRESS_OF2.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF2.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_LAST_NAME,
    /* --PERSON_ADDRESS_OF.ADDR_LINE1 AS OF_P_OFFICE_ADDR_LINE1, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF3.ADDR_LINE1
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF3
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF3.PERSON_ID AND PERSON_ADDRESS_OF3.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF3.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_LINE1,
    /* --PERSON_ADDRESS_OF.ADDR_LINE2 AS OF_P_OFFICE_ADDR_LINE2, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF4.ADDR_LINE2
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF4
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF4.PERSON_ID AND PERSON_ADDRESS_OF4.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF4.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_LINE2,
    /* --PERSON_ADDRESS_OF.ADDR_SUBURB AS OF_P_OFFICE_ADDR_SUBURB, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF5.ADDR_SUBURB
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF5
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF5.PERSON_ID AND PERSON_ADDRESS_OF5.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF5.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_SUBURB,
    /* --PERSON_ADDRESS_OF.ADDR_CITY AS OF_P_OFFICE_ADDR_CITY, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF6.ADDR_CITY
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF6
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF6.PERSON_ID AND PERSON_ADDRESS_OF6.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF6.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_CITY,
    /* --PERSON_ADDRESS_OF.ADDR_STATE AS OF_P_OFFICE_ADDR_STATE, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF7.ADDR_STATE
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF7
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF7.PERSON_ID AND PERSON_ADDRESS_OF7.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF7.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_STATE,
    /* --PERSON_ADDRESS_OF.ADDR_POST_CODE AS OF_P_OFFICE_ADDR_POST_CODE, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF8.ADDR_POST_CODE
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF8
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF8.PERSON_ID AND PERSON_ADDRESS_OF8.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF8.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_POST_CODE,
    /* --PERSON_ADDRESS_OF.ADDR_COUNTRY AS OF_P_OFFICE_ADDR_COUNTRY, */
        (SELECT FIRST 1 PERSON_ADDRESS_OF9.ADDR_COUNTRY
         FROM PERSON_ADDRESS PERSON_ADDRESS_OF9
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_OF9.PERSON_ID AND PERSON_ADDRESS_OF9.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_OF9.ADDR_TYPE = 'OF'
        ) AS  OF_P_OFFICE_ADDR_COUNTRY,

/* ------ PERSON_ADDRESS WHERE PERSON_ID ='AITS' AND ADDR_STATUS ='CU' AND ADDR_TYPE ='MT'  Mail */
    /* --PERSON_ADDRESS_MT.ADDR_FIRST_NAME AS MT_P_MAIL_ADDR_FIRST_NAME, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT1.ADDR_FIRST_NAME
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT1
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT1.PERSON_ID AND PERSON_ADDRESS_MT1.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT1.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_FIRST_NAME,
    /* --PERSON_ADDRESS_MT.ADDR_LAST_NAME AS MT_P_MAIL_ADDR_LAST_NAME, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT2.ADDR_LAST_NAME
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT2
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT2.PERSON_ID AND PERSON_ADDRESS_MT2.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT2.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_LAST_NAME,
    /* --PERSON_ADDRESS_MT.ADDR_LINE1 AS MT_P_MAIL_ADDR_LINE1, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT3.ADDR_LINE1
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT3
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT3.PERSON_ID AND PERSON_ADDRESS_MT3.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT3.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_LINE1,
    /* --PERSON_ADDRESS_MT.ADDR_LINE2 AS MT_P_MAIL_ADDR_LINE2, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT4.ADDR_LINE2
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT4
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT4.PERSON_ID AND PERSON_ADDRESS_MT4.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT4.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_LINE2,
    /* --PERSON_ADDRESS_MT.ADDR_SUBURB AS MT_P_MAIL_ADDR_SUBURB, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT5.ADDR_SUBURB
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT5
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT5.PERSON_ID AND PERSON_ADDRESS_MT5.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT5.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_SUBURB,
    /* --PERSON_ADDRESS_MT.ADDR_CITY AS MT_P_MAIL_ADDR_CITY, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT6.ADDR_CITY
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT6
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT6.PERSON_ID AND PERSON_ADDRESS_MT6.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT6.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_CITY,
    /* --PERSON_ADDRESS_MT.ADDR_STATE AS MT_P_MAIL_ADDR_STATE, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT7.ADDR_STATE
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT7
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT7.PERSON_ID AND PERSON_ADDRESS_MT7.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT7.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_STATE,
    /* --PERSON_ADDRESS_MT.ADDR_POST_CODE AS MT_P_MAIL_ADDR_POST_CODE, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT8.ADDR_POST_CODE
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT8
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT8.PERSON_ID AND PERSON_ADDRESS_MT8.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT8.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_POST_CODE,
    /* --PERSON_ADDRESS_MT.ADDR_COUNTRY AS MT_P_MAIL_ADDR_COUNTRY, */
        (SELECT FIRST 1 PERSON_ADDRESS_MT9.ADDR_COUNTRY
         FROM PERSON_ADDRESS PERSON_ADDRESS_MT9
         WHERE PICK_ORDER.COMPANY_ID = PERSON_ADDRESS_MT9.PERSON_ID AND PERSON_ADDRESS_MT9.ADDR_STATUS = 'CU' AND PERSON_ADDRESS_MT9.ADDR_TYPE = 'MT'
        ) AS  MT_P_MAIL_ADDR_COUNTRY,

       PICK_ORDER.PICK_ORDER	          AS PO_PICK_ORDER,
       PICK_ORDER.PERSON_ID                          AS PO_PERSON_ID,
       PICK_ORDER.PICK_STATUS                      AS PO_PICK_STATUS,
       PICK_ORDER.CONTACT_NAME                 AS PO_CONTACT_NAME,
       PICK_ORDER.CUSTOMER_PO_WO             AS PO_CUSTOMER_PO_WO,
       PICK_ORDER.PICK_DUE_DATE                  AS PO_PICK_DUE_DATE,
       PICK_ORDER.SPECIAL_INSTRUCTIONS1      AS PO_SPECIAL_INSTRUCTIONS1,
       PICK_ORDER.TERMS                                  AS PO_TERMS,
       PICK_ORDER.CREATE_DATE                     AS PO_CREATE_DATE,
       PICK_ORDER.CREATED_BY                      AS PO_CREATED_BY,
       PICK_ORDER.PAYMENT_METHOD             AS PO_PAYMENT_METHOD,
       PICK_ORDER.SHIP_VIA	                          AS PO_SHIP_VIA,
       PICK_ORDER.SHIP_SERVICE   	         AS PO_SERVICE_TYPE,    /* e.g.EXP */

       COALESCE(PICK_ORDER.SUB_TOTAL_AMOUNT,0)       AS PO_SUB_TOTAL_AMOUNT,
       COALESCE(PICK_ORDER.AMOUNT_PAID,0)                  AS PO_AMOUNT_PAID,
       COALESCE(PICK_ORDER.FREIGHT,0)                            AS PO_FREIGHT,
       COALESCE(PICK_ORDER.ADMIN_FEE_RATE,0)            AS PO_ADMIN_FEE_RATE,
       COALESCE(PICK_ORDER.ADMIN_FEE_AMOUNT,0)       AS PO_ADMIN_FEE_AMOUNT,
       COALESCE(PICK_ORDER.TAX_AMOUNT,0)                   AS PO_TAX_AMOUNT,
       COALESCE(PICK_ORDER.TAX_RATE,0)                         AS PO_TAX_RATE,
       COALESCE(PICK_ORDER.DUE_AMOUNT ,0)                 AS PO_DUE_AMOUNT,
/* -------------Customer's Invoice To/Post To address is in PICK_ORDER.P_% Fields -------------- */
       PICK_ORDER.P_FIRST_NAME                         AS PO_P_FIRST_NAME,
       PICK_ORDER.P_LAST_NAME                           AS PO_P_LAST_NAME,
       PICK_ORDER.P_ADDRESS_LINE1                    AS PO_P_ADDRESS_LINE1,
       PICK_ORDER.P_ADDRESS_LINE2                    AS PO_P_ADDRESS_LINE2,
       PICK_ORDER.P_CITY                                       AS PO_P_CITY,
       PICK_ORDER.P_STATE                                   AS PO_P_STATE,
       PICK_ORDER.P_POST_CODE                          AS PO_P_POST_CODE,
       PICK_ORDER.P_COUNTRY                             AS PO_P_COUNTRY,
       PICK_ORDER.P_PHONE                                  AS PO_P_PHONE,
/* -------------Customer's Deliver  To address is in PICK_ORDER.D_% Fields------------ */
       PICK_ORDER.D_FIRST_NAME,
       PICK_ORDER.D_LAST_NAME,
       PICK_ORDER.D_ADDRESS_LINE1,
       PICK_ORDER.D_ADDRESS_LINE2,
       PICK_ORDER.D_CITY,
       PICK_ORDER.D_STATE ,
       PICK_ORDER.D_POST_CODE,
       PICK_ORDER.D_COUNTRY,
       PICK_ORDER.D_PHONE,

/* -----------------------Need Shipped Qty --------------- */
       CAST(COALESCE(PICK_ITEM.PICKED_QTY,0) as INTEGER)	AS PI_SHIPPED_QTY,

/* ----- Need Qty on BackOrder -> calculate PICK_ITEM.PICK_ORDER_QTY - PICK_ITEM.PICKED_QTY ------ */
      CAST( COALESCE(PICK_ITEM.PICK_ORDER_QTY,0) - COALESCE(PICK_ITEM.PICKED_QTY,0) as INTEGER)  
                                                 AS PI_BACK_ORDER,                                                                   
   
       CAST(COALESCE(PICK_ITEM.PICK_ORDER_QTY,0) as INTEGER) AS PI_PICK_ORDER_QTY,

       CAST(COALESCE(PICK_ITEM.SALE_PRICE,0) AS FLOAT) AS PI_SALE_PRICE,

       CAST(COALESCE(PICK_ITEM.SALE_PRICE,0) * (COALESCE(PICK_ITEM.PICK_ORDER_QTY,0) ) AS FLOAT)
		                 AS PI_EXTENSION_TOTAL,

     COALESCE(PICK_ITEM.DISCOUNT,0)                 AS PI_DISCOUNT,

/* Need Invoice Line Total is not calculated but read from PICK_ITEM record l */

      (COALESCE(PICK_ITEM.SALE_PRICE,0) * (COALESCE(PICK_ITEM.PICK_ORDER_QTY,0) ) ) * (1 - COALESCE(PICK_ITEM.DISCOUNT,0)/100)
                                                    AS PI_LINE_TOTAL,

     COALESCE(PICK_ITEM.TAX_RATE,0)                 AS PI_TAX_RATE,    
     PICK_ITEM.WARRANTY_TERM 		  AS PI_WARRANTY,

      ((COALESCE(PICK_ITEM.SALE_PRICE,0) * (COALESCE(PICK_ITEM.PICK_ORDER_QTY,0) )) * 
                    (1 - COALESCE(PICK_ITEM.DISCOUNT,0)/100) * COALESCE(PICK_ITEM.TAX_RATE,0)/100)
                    	                    AS PI_LINE_TAX_AMOUNT


FROM PICK_ITEM

LEFT OUTER JOIN PICK_ORDER  ON PICK_ITEM.PICK_ORDER = PICK_ORDER.PICK_ORDER
JOIN PROD_PROFILE           ON PICK_ITEM.PROD_ID               = PROD_PROFILE.PROD_ID
JOIN COMPANY                   ON COMPANY.COMPANY_ID           = PICK_ORDER.COMPANY_ID
JOIN PERSON                      ON COMPANY.COMPANY_ID          = PERSON.PERSON_ID AND PERSON.STATUS = 'CU'

WHERE PICK_ITEM.PICK_ORDER =  'S00018404'

ORDER BY  PICK_ITEM.PICK_ORDER_LINE_NO ; 


